// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Source: PROG.cbl
// Do not edit manually. Regenerate from COBOL source.
#![allow(unused_imports, unused_variables, dead_code, unused_parens, non_snake_case)]
#![recursion_limit = "2048"]

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::string_ops::*;
use cobol_runtime::chrono_shim::*;
use cobol_runtime::CobolInto;
use cobol_runtime::cobol_helpers::*;
use cobol_runtime::define_record;

define_record! {
    /// G
    pub struct G {
        /// X-2
        pub x_2: FixedString<2>,
        /// N-3
        pub n_3: Decimal,
        /// N-4
        pub n_4: Decimal,
    }
}


#[derive(Default)]
pub struct ProgramState {
    // --- WORKING-STORAGE SECTION ---
    /// WS: G (group)
    pub g: FixedString<9>,
    /// WS: X-2
    pub x_2: FixedString<2>,
    /// WS: N-3
    pub n_3: Decimal,
    /// WS: N-4
    pub n_4: Decimal,
    // --- Special registers ---
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}


/// Paragraph: _IMPLICIT_
fn p__implicit_(state: &mut ProgramState) {
    state.x_2 = format!("{}", "\\x00\\x00").cobol_into();
    if { let __v = format!("{}", state.n_3); __v.trim() != "" && __v.trim() != "0" } {
    }
    // IS NOT NUMERIC DISPLAY "3 0000 NG"
    if { let __v = format!("{}", state.n_4); __v.trim() != "" && __v.trim() != "0" } {
    }
    // IS NOT NUMERIC DISPLAY "4 0000 NG"
    state.x_2 = format!("{}", "\\x00\\x0C").cobol_into();
    if { let __v = format!("{}", state.n_3); __v.trim() != "" && __v.trim() != "0" } {
    }
    // IS NUMERIC DISPLAY "3 000c NG"
    if { let __v = format!("{}", state.n_4); __v.trim() != "" && __v.trim() != "0" } {
    }
    // IS NUMERIC DISPLAY "4 000c NG"
    state.x_2 = format!("{}", "\\x124").cobol_into();
    if { let __v = format!("{}", state.n_3); __v.trim() != "" && __v.trim() != "0" } {
    }
    // IS NOT NUMERIC DISPLAY "3 1234 NG"
    if { let __v = format!("{}", state.n_4); __v.trim() != "" && __v.trim() != "0" } {
    }
    // IS NOT NUMERIC DISPLAY "4 1234 NG"
    state.x_2 = format!("{}", "\\xFF\\xFF").cobol_into();
    if { let __v = format!("{}", state.n_3); __v.trim() != "" && __v.trim() != "0" } {
    }
    // IS NUMERIC DISPLAY "3 ffff NG"
    if { let __v = format!("{}", state.n_4); __v.trim() != "" && __v.trim() != "0" } {
    }
    // IS NUMERIC DISPLAY "4 ffff NG"
    std::process::exit(0);
}

fn main() {
    let mut state = ProgramState::default();
    p__implicit_(&mut state);
}
