// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Source: PROG.cbl
// Do not edit manually. Regenerate from COBOL source.
#![allow(unused_imports, unused_variables, dead_code, unused_parens, non_snake_case, invalid_value)]

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::string_ops::*;
use cobol_runtime::chrono_shim::*;
use cobol_runtime::CobolInto;
use cobol_runtime::cobol_helpers::*;
use cobol_runtime::define_record;


pub struct ProgramState {
    // --- WORKING-STORAGE SECTION ---
    /// WS: P-FIELD1
    pub p_field1: Decimal,
    /// WS: P-FIELD2
    pub p_field2: Decimal,
    // --- Special registers ---
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        unsafe { std::mem::MaybeUninit::zeroed().assume_init() }
    }
}

/// Paragraph: _IMPLICIT_
fn p__implicit_(state: &mut ProgramState) {
    state.p_field1 = format!("{}", 5000).cobol_into();
    { let _a: f64 = format!("{}", state.p_field1).trim().parse().unwrap_or(0.0); let _b: f64 = format!("{}", 5).trim().parse().unwrap_or(0.0); state.p_field1 = format!("{}", _a + _b).cobol_into(); }
    if format!("{}", state.p_field1).trim() != format!("{}", 5000).trim() {
        println!("{}", format!("{}", "Error: Add 5 to PIC 99PPP."));
    }
    // CALL 'dump' USING &mut state.p_field1
    { let _a: f64 = format!("{}", state.p_field1).trim().parse().unwrap_or(0.0); let _b: f64 = format!("{}", 5000).trim().parse().unwrap_or(0.0); state.p_field1 = format!("{}", _a + _b).cobol_into(); }
    if format!("{}", state.p_field1).trim() != format!("{}", 10000).trim() {
        println!("{}", format!("{}", "Error: Add 5000 to PIC 99PPP."));
    }
    // CALL 'dump' USING &mut state.p_field1
    state.p_field2 = format!("{}", 0.000550).cobol_into();
    { let _a: f64 = format!("{}", state.p_field2).trim().parse().unwrap_or(0.0); let _b: f64 = format!("{}", 0.000330).trim().parse().unwrap_or(0.0); state.p_field2 = format!("{}", _a + _b).cobol_into(); }
    if format!("{}", state.p_field2).trim() != format!("{}", 0.000880).trim() {
        println!("{}", format!("{}", "Error: Add 0.00033 to PIC PPP99."));
    }
    // CALL 'dump' USING &mut state.p_field2
    state.p_field2 = format!("{}", 0.000550).cobol_into();
    { let _a: f64 = format!("{}", state.p_field2).trim().parse().unwrap_or(0.0); let _b: f64 = format!("{}", 0.003000).trim().parse().unwrap_or(0.0); state.p_field2 = format!("{}", _a + _b).cobol_into(); }
    if format!("{}", state.p_field2).trim() != format!("{}", 0.000550).trim() {
        println!("{}", format!("{}", "Error: Add 0.00300 to PIC PPP99."));
    }
    // CALL 'dump' USING &mut state.p_field2
    std::process::exit(0);
}

fn main() {
    let mut state = ProgramState::default();
    p__implicit_(&mut state);
}
