// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Source: PROG.cbl
// Do not edit manually. Regenerate from COBOL source.
#![allow(unused_imports, unused_variables, dead_code, unused_parens, non_snake_case)]
#![recursion_limit = "2048"]

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::string_ops::*;
use cobol_runtime::chrono_shim::*;
use cobol_runtime::CobolInto;
use cobol_runtime::cobol_helpers::*;
use cobol_runtime::define_record;

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Tab {
    /// X
    pub x: Vec<FixedString<1>>,
}
impl std::fmt::Display for Tab {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self.x)
    }
}
impl From<&str> for Tab {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Tab {
    fn from(_s: String) -> Self { Self::default() }
}
impl Tab {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}


#[derive(Default)]
pub struct ProgramState {
    // --- WORKING-STORAGE SECTION ---
    /// WS: TAB (group)
    pub tab: FixedString<4>,
    /// WS: X
    pub x: Vec<FixedString<1>>,
    /// WS: N
    pub n: u8,
    // --- Special registers ---
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}


/// Paragraph: _IMPLICIT_
fn p__implicit_(state: &mut ProgramState) {
    for _elem in state.x.iter_mut() { *_elem = format!("{}", "B").cobol_into(); }
    if { let __v = format!("{:?}", state.x); __v.trim() != "" && __v.trim() != "0" } {
    }
    // ( 6 ) NOT EQUAL TO "B" THEN DISPLAY "Got X (6) = " X ( 6 ) ", expected B" END-DISPLAY STOP RUN
}

fn main() {
    let mut state = ProgramState::default();
    p__implicit_(&mut state);
}
