// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Source: PROG.cbl
// Do not edit manually. Regenerate from COBOL source.
#![allow(unused_imports, unused_variables, dead_code, unused_parens, non_snake_case)]

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::string_ops::*;
use cobol_runtime::chrono_shim::*;
use cobol_runtime::CobolInto;
use cobol_runtime::cobol_helpers::*;
use cobol_runtime::define_record;

define_record! {
    /// E
    pub struct E {
    }
}

define_record! {
    /// C
    pub struct C {
        /// D
        pub d: u8,
        /// E
        pub e: E,
    }
}

define_record! {
    /// A
    pub struct A {
        /// B
        pub b: u8,
        /// C
        pub c: C,
    }
}

define_record! {
    /// J
    pub struct J {
        /// K
        pub k: FixedString<1>,
        /// L
        pub l: u8,
    }
}

define_record! {
    /// INVALID-9
    pub struct Invalid9 {
    }
}

define_record! {
    /// P
    pub struct P {
        /// INVALID-9
        pub invalid_9: Invalid9,
    }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct O {
    /// P
    pub p: [P; 1],
}
impl std::fmt::Display for O {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self.p)
    }
}
impl From<&str> for O {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for O {
    fn from(_s: String) -> Self { Self::default() }
}
impl O {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct F {
    /// G
    pub g: FixedString<1>,
    /// I
    pub i: FixedString<1>,
    /// J
    pub j: [J; 5],
    /// M
    pub m: u8,
    /// O
    pub o: O,
}
impl std::fmt::Display for F {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{:?}{}{}", self.g, self.i, self.j, self.m, self.o)
    }
}
impl From<&str> for F {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for F {
    fn from(_s: String) -> Self { Self::default() }
}
impl F {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

define_record! {
    /// MY-STD-CONST
    pub struct MyStdConst {
    }
}


#[derive(Default)]
pub struct ProgramState {
    // --- WORKING-STORAGE SECTION ---
    /// WS: A (group)
    pub a: FixedString<2>,
    /// WS: B
    pub b: u8,
    /// WS: C (group)
    pub c: FixedString<1>,
    /// WS: D
    pub d: u8,
    /// WS: E (group)
    pub e: FixedString<1>,
    /// WS: VALID-1
    pub valid_1: FixedString<1>,
    /// WS: VALID-2
    pub valid_2: FixedString<1>,
    /// WS: INVALID-1
    pub invalid_1: FixedString<1>,
    /// WS: INVALID-2
    pub invalid_2: FixedString<1>,
    /// WS: INVALID-3
    pub invalid_3: FixedString<1>,
    /// WS: INVALID-4
    pub invalid_4: FixedString<1>,
    /// WS: F (group)
    pub f: FixedString<5>,
    /// WS: G
    pub g: FixedString<1>,
    /// WS: I
    pub i: FixedString<1>,
    /// WS: J (group)
    pub j: FixedString<2>,
    /// WS: K
    pub k: FixedString<1>,
    /// WS: L
    pub l: u8,
    /// WS: M
    pub m: u8,
    /// WS: N
    pub n: FixedString<1>,
    /// WS: O (group)
    pub o: FixedString<1>,
    /// WS: P (group)
    pub p: FixedString<1>,
    /// WS: VALID-3
    pub valid_3: FixedString<1>,
    /// WS: INVALID-5
    pub invalid_5: FixedString<1>,
    /// WS: INVALID-6
    pub invalid_6: FixedString<1>,
    /// WS: INVALID-7
    pub invalid_7: FixedString<1>,
    /// WS: INVALID-8
    pub invalid_8: FixedString<1>,
    /// WS: INVALID-9 (group)
    pub invalid_9: FixedString<1>,
    /// WS: MY-EXT-CONST
    pub my_ext_const: FixedString<1>,
    /// WS: INVALID-EC
    pub invalid_ec: FixedString<1>,
    /// WS: MY-STD-CONST (group)
    pub my_std_const: FixedString<1>,
    /// WS: INVALID-SC
    pub invalid_sc: FixedString<1>,
    // --- Special registers ---
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}


impl ProgramState {
    pub fn h(&self) -> bool { format!("{}", self.g).trim() == "a" }
}

/// Paragraph: _IMPLICIT_
fn p__implicit_(state: &mut ProgramState) {
    println!("{}", format!("{}", state.valid_2));
    if format!("{}", state.valid_1).trim() == format!("{}", 1).trim() {
        // CONTINUE
    }
}

fn main() {
    let mut state = ProgramState::default();
    p__implicit_(&mut state);
}
