// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Source: PROG.cbl
// Do not edit manually. Regenerate from COBOL source.
#![allow(unused_imports, unused_variables, dead_code, unused_parens, non_snake_case, invalid_value)]

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::string_ops::*;
use cobol_runtime::chrono_shim::*;
use cobol_runtime::CobolInto;
use cobol_runtime::cobol_helpers::*;
use cobol_runtime::define_record;


pub struct ProgramState {
    // --- Special registers ---
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        unsafe { std::mem::MaybeUninit::zeroed().assume_init() }
    }
}

/// Paragraph: _IMPLICIT_
fn p__implicit_(state: &mut ProgramState) {
    println!("{}", format!("{}", cobol_fn_pi()));
    println!("{}", format!("{}", cobol_fn_pi()));
    println!("{}", format!("{}", cobol_fn_pi(1)));
    println!("{}", format!("{}", cobol_fn_abs()));
    println!("{}", format!("{}", cobol_fn_abs(1)));
    println!("{}", format!("{}", cobol_fn_abs(1, 2)));
    println!("{}", format!("{}", cobol_fn_day_to_yyyyddd()));
    println!("{}", format!("{}", cobol_fn_day_to_yyyyddd(6000)));
    println!("{}", format!("{}", cobol_fn_day_to_yyyyddd(6000, 50)));
    println!("{}", format!("{}", cobol_fn_day_to_yyyyddd(6000, 50, 1600)));
    println!("{}", format!("{}", cobol_fn_day_to_yyyyddd(6000, 50, 1600, 500)));
    println!("{}", format!("{}", cobol_fn_max()));
    println!("{}", format!("{}", cobol_fn_max(6000)));
    println!("{}", format!("{}", cobol_fn_substitute("A", "B", "C", "D")));
    std::process::exit(0);
}

fn main() {
    let mut state = ProgramState::default();
    p__implicit_(&mut state);
}
