// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone)]
pub struct ProgramState {
    /// L1-1-2-S
    pub l1_1_2_s: u32,
    /// L1-1-2-1-S
    pub l1_1_2_1_s: u32,
    /// L1-2-S
    pub l1_2_s: u32,
    /// L1-3-S
    pub l1_3_s: u32,
    /// L1-3-2-S
    pub l1_3_2_s: u32,
    /// BUFFER
    pub buffer: FixedString<370>,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            l1_1_2_s: Default::default(),
            l1_1_2_1_s: Default::default(),
            l1_2_s: Default::default(),
            l1_3_s: Default::default(),
            l1_3_2_s: Default::default(),
            buffer: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// BUFFER
fn p_buffer(state: &mut ProgramState) {
    state.l1_1_2_s = 3 as u32;
    state.l1_1_2_1_s = 4 as u32;
    state.l1_2_s = 0 as u32;
    state.l1_3_s = 6 as u32;
    state.l1_3_2_s = 1 as u32;
    {
        let mut _p1 = (state.buffer).clone();
        let mut _p2 = (state.l1_1_2_s).clone();
        let mut _p3 = (state.l1_1_2_1_s).clone();
        let mut _p4 = (state.l1_2_s).clone();
        let mut _p5 = (state.l1_3_s).clone();
        let mut _p6 = (state.l1_3_2_s).clone();
        ibm_odo_test(&mut _p1, &mut _p2, &mut _p3, &mut _p4, &mut _p5, &mut _p6);
        state.buffer = _p1;
        state.l1_1_2_s = _p2;
        state.l1_1_2_1_s = _p3;
        state.l1_2_s = _p4;
        state.l1_3_s = _p5;
        state.l1_3_2_s = _p6;
    }
    state.buffer = FixedString::from_cobol_str(&format!("{}", "0123456789"));
    state.l1_1_2_s = 2 as u32;
    state.l1_1_2_1_s = 3 as u32;
    state.l1_2_s = 1 as u32;
    state.l1_3_s = 4 as u32;
    state.l1_3_2_s = 0 as u32;
    {
        let mut _p1 = (state.buffer).clone();
        let mut _p2 = (state.l1_1_2_s).clone();
        let mut _p3 = (state.l1_1_2_1_s).clone();
        let mut _p4 = (state.l1_2_s).clone();
        let mut _p5 = (state.l1_3_s).clone();
        let mut _p6 = (state.l1_3_2_s).clone();
        ibm_odo_test(&mut _p1, &mut _p2, &mut _p3, &mut _p4, &mut _p5, &mut _p6);
        state.buffer = _p1;
        state.l1_1_2_s = _p2;
        state.l1_1_2_1_s = _p3;
        state.l1_2_s = _p4;
        state.l1_3_s = _p5;
        state.l1_3_2_s = _p6;
    }
    { std::process::exit(0); }
}

/// PROG
fn p_prog(state: &mut ProgramState) {
}

/// DIVISION
fn p_division(state: &mut ProgramState) {
}

/// PROGRAM-ID
fn p_program_id(state: &mut ProgramState) {
}

/// IBM-ODO-TEST
fn p_ibm_odo_test(state: &mut ProgramState) {
}

/// DIVISION
fn p_division_2(state: &mut ProgramState) {
}

/// SECTION
fn p_section(state: &mut ProgramState) {
}

/// SECTION
fn p_section_2(state: &mut ProgramState) {
}

/// BASE
fn p_base(state: &mut ProgramState) {
}

/// TIMES
fn p_times(state: &mut ProgramState) {
}

/// L1-1
fn p_l1_1(state: &mut ProgramState) {
}

/// L1-1-2-S
fn p_l1_1_2_s(state: &mut ProgramState) {
}

/// L1-3-S
fn p_l1_3_s(state: &mut ProgramState) {
}

/// L1-3-1
fn p_l1_3_1(state: &mut ProgramState) {
}

/// L1-3-2-S
fn p_l1_3_2_s(state: &mut ProgramState) {
    // SKIP: unresolved display ref
    // SKIP: unresolved ref: state._unresolved_l1_3_2[(1 - 1) as usize][(5 - 1) as usize][(1 - 1) as usize] = ".".into();
    // SKIP: unresolved ref: state._unresolved_l1_2[(2 - 1) as usize][(1 - 1) as usize] = "--".into();
    // SKIP: unresolved ref: state._unresolved_l1_1_2_1[(2 - 1) as usize][(1 - 1) as usize][(5 - 1) as usize] = "+++".into();
    // SKIP: unresolved display ref
}

/// IBM-ODO-TEST
fn p_ibm_odo_test_2(state: &mut ProgramState) {
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// External: CALL 'IBM-ODO-TEST'
fn ibm_odo_test(_param1: &mut impl std::fmt::Debug, _param2: &mut impl std::fmt::Debug, _param3: &mut impl std::fmt::Debug, _param4: &mut impl std::fmt::Debug, _param5: &mut impl std::fmt::Debug, _param6: &mut impl std::fmt::Debug) {
    todo!("External subroutine 'IBM-ODO-TEST' not yet linked — implement or link the IBM-ODO-TEST module")
}

fn main() {
    let mut state = ProgramState::default();
    p_buffer(&mut state);
}

