// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct SuccessFlag {
    /// LIN-START
    pub lin_start: u32,
    /// LIN
    pub lin: u32,
}
impl std::fmt::Display for SuccessFlag {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.lin_start, self.lin)
    }
}
impl From<&str> for SuccessFlag {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for SuccessFlag {
    fn from(_s: String) -> Self { Self::default() }
}
impl SuccessFlag {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// SUCCESS-FLAG
    pub success_flag: SuccessFlag,
    /// LIN-START
    pub lin_start: u32,
    /// LIN
    pub lin: u32,
    /// SCR1
    pub scr1: FixedString<75>,
    /// SCR2
    pub scr2: FixedString<75>,
    /// GRAPHCONTROL
    pub graphcontrol: FixedString<50>,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            success_flag: Default::default(),
            lin_start: Default::default(),
            lin: Default::default(),
            scr1: FixedString::from_str("Enter \"y\" if you see line draw characters. "),
            scr2: FixedString::from_str("uses HIGHLIGHT, the second uses "),
            graphcontrol: FixedString::from_str("HIGH, GRAPHICS"),
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// TESTME
fn p_testme(state: &mut ProgramState) {
    state.success_flag.lin = 2 as u32;
    println!("{}{}", state.scr1, 2);
    state.success_flag.lin += 1 as u32;
    println!("{}{}{}", state.scr2, 2, "");
    state.success_flag.lin_start = 5 as u32;
    p_dspcol(state);
    state.success_flag.lin_start = 12 as u32;
    state.graphcontrol = "LOW BLINK FCOLOR=MAGENTA GRAPHICS".into();
    p_dspcol(state);
    // ACCEPT SUCCESS-FLAG (console input)
    if true /* AUTO-FIX: E0308: mismatched types */ {
        return;
    }
    return;
}

/// DSPCOL
fn p_dspcol(state: &mut ProgramState) {
    state.success_flag.lin = state.success_flag.lin_start as u32;
    println!("{}{}{}", "lqqqqwqqqqk", 5, "");
    state.success_flag.lin += 1 as u32;
    println!("{}{}{}", "x    x    x", 5, "");
    state.success_flag.lin += 1 as u32;
    println!("{}{}{}", "tqqqqnqqqqu", 5, "");
    state.success_flag.lin += 1 as u32;
    println!("{}{}{}", "x    x    x", 5, "");
    state.success_flag.lin += 1 as u32;
    println!("{}{}{}", "mqqqqvqqqqj", 5, "");
    state.success_flag.lin += 1 as u32;
    state.success_flag.lin = state.success_flag.lin_start as u32;
    println!("{}{}{}", "LQQQQWQQQQK", 20, "");
    state.success_flag.lin += 1 as u32;
    println!("{}{}{}", "X    X    X", 20, "");
    state.success_flag.lin += 1 as u32;
    println!("{}{}{}", "TQQQQNQQQQU", 20, "");
    state.success_flag.lin += 1 as u32;
    println!("{}{}{}", "X    X    X", 20, "");
    state.success_flag.lin += 1 as u32;
    println!("{}{}{}", "MQQQQVQQQQJ", 20, "");
}

fn main() {
    let mut state = ProgramState::default();
    p_testme(&mut state);
}

