// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.
#![allow(warnings)]

use cobol_runtime::field::*;
use std::collections::HashMap;

#[allow(unused_imports)]
use cobol_runtime::FixedString;
#[allow(unused_imports)]
use cobol_runtime::Decimal;
#[allow(unused_imports)]
use cobol_runtime::PackedDecimal;
#[allow(unused_imports)]
use cobol_runtime::FileStatus;
#[allow(unused_imports)]
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;
#[allow(unused_imports)]
use cobol_runtime::CobolNum;
#[allow(unused_imports)]
use cobol_runtime::CobolToF64;
#[allow(unused_imports)]
use cobol_runtime::CobolTrimmed;
#[allow(unused_imports)]
use cobol_runtime::DisplayWithWidth;
#[allow(unused_imports)]
use cobol_runtime::CobolInto;
#[allow(unused_imports)]
use cobol_runtime::coerce::Coerce;
#[allow(unused_imports)]
use cobol_runtime::screen::{ScreenField, SPos, screen_display};


pub struct ProgramState {
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
        }
    }
}

/// Paragraph: RECURSION-TEST
fn v2_recursion_test(record: &mut CobolRecord) {
    { let _v = 1_f64; let _t = record.get_f64("X__2"); record.set_f64("X__2", _t + _v); }
    { print!("{}", record.get_display("X__2")); use std::io::Write; std::io::stdout().flush().ok(); }
    if f64_cmp(record.get_f64("X__2"), 1_f64) == 0 {
    {
        
        record.set_bytes("MODULE-CALLER-ID", b"recursion-test");
        record.set_f64("NUMBER-OF-CALL-PARAMETERS", 1_f64);
        cobol_runtime::clear_omitted_params();
        { let _v = record.get_bytes("X__2").to_vec(); record.set_bytes("X__2", &_v); }
        v2_recursion_test(record);
        { let _v = record.get_bytes("X__2").to_vec(); record.set_bytes("X__2", &_v); }
    }
    }
}

/// Paragraph: CANCEL-TEST
fn v2_cancel_test(record: &mut CobolRecord) {
    if cobol_runtime::check_and_clear_cancelled("CANCEL-TEST") {
    record.set_f64("X", 1_f64);
    }
    { print!("{}", record.get_display("X")); use std::io::Write; std::io::stdout().flush().ok(); }
    { let _v = 1_f64; let _t = record.get_f64("X"); record.set_f64("X", _t + _v); }
}

fn main() {
    let mut record = CobolRecord::new(631, vec![
        FieldDescriptor { name: "PROG-PTR".into(), offset: 0, size: 8, field_type: FieldType::Binary64, pic_scale: 0, pic_digits: 8, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: true, pic_clause_digits: 0 },
        FieldDescriptor { name: "NUM".into(), offset: 8, size: 1, field_type: FieldType::NumericDisplay, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "X".into(), offset: 9, size: 1, field_type: FieldType::NumericDisplay, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "N".into(), offset: 10, size: 1, field_type: FieldType::NumericDisplay, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "X__2".into(), offset: 11, size: 1, field_type: FieldType::NumericDisplay, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "TALLY".into(), offset: 12, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "RETURN-CODE".into(), offset: 16, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SORT-RETURN".into(), offset: 20, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "NUMBER-OF-CALL-PARAMETERS".into(), offset: 24, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LINAGE-COUNTER".into(), offset: 28, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LINE-COUNTER".into(), offset: 32, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "PAGE-COUNTER".into(), offset: 36, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SYSTEM-OFFSET".into(), offset: 40, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-CODE".into(), offset: 44, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "JSON-CODE".into(), offset: 48, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LIN".into(), offset: 52, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COL".into(), offset: 56, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COB-CRT-STATUS".into(), offset: 60, size: 4, field_type: FieldType::NumericDisplay, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "DEBUG-ITEM".into(), offset: 64, size: 86, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 86, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COB-CURRENT-DATE".into(), offset: 150, size: 26, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 26, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-STATUS".into(), offset: 176, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-FILE".into(), offset: 207, size: 30, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 30, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-LOCATION".into(), offset: 237, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-STATEMENT".into(), offset: 268, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "MODULE-CALLER-ID".into(), offset: 299, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "WHEN-COMPILED".into(), offset: 330, size: 16, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 16, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-EVENT".into(), offset: 346, size: 30, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 30, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-TEXT".into(), offset: 376, size: 255, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 255, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },]);
    let record = &mut record;
    record.set_i64("PROG-PTR", 0);
    record.set_f64("NUM", 0_f64);
    record.set_f64("X", 1_f64);
    { let now = cobol_runtime::chrono_shim::Local::now(); let wc = now.format("%d/%m/%y%H.%M.%S").to_string(); record.set_raw_string("WHEN-COMPILED", &wc); }
    {
        
        record.set_bytes("MODULE-CALLER-ID", b"prog");
        record.set_f64("NUMBER-OF-CALL-PARAMETERS", 1_f64);
        cobol_runtime::clear_omitted_params();
        { let _v = record.get_bytes("NUM").to_vec(); record.set_bytes("X__2", &_v); }
        v2_recursion_test(record);
        { let _v = record.get_bytes("X__2").to_vec(); record.set_bytes("NUM", &_v); }
    }
    { println!("{}", "<".to_string()); use std::io::Write; std::io::stdout().flush().ok(); }
     record.set_bytes("MODULE-CALLER-ID", b"prog"); record.set_f64("NUMBER-OF-CALL-PARAMETERS", 0_f64); v2_cancel_test(record);
     record.set_bytes("MODULE-CALLER-ID", b"prog"); record.set_f64("NUMBER-OF-CALL-PARAMETERS", 0_f64); v2_cancel_test(record);
    cobol_runtime::cancel_program("CANCEL-TEST");
     record.set_bytes("MODULE-CALLER-ID", b"prog"); record.set_f64("NUMBER-OF-CALL-PARAMETERS", 0_f64); v2_cancel_test(record);
    { println!("{}", "<".to_string()); use std::io::Write; std::io::stdout().flush().ok(); }
    { record.set_i64("PROG-PTR", 1); cobol_runtime::set_program_pointer("PROG-PTR", "RECURSION-TEST"); }
    if { let _l = record.get_display_unsigned("PROG-PTR"); let _r = "0000000000000000".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) == format!("{:<w$}", _r, w = _w) } {
    { eprintln!("{}", "address of recursion-prog not set".to_string()); use std::io::Write; std::io::stdout().flush().ok(); }
    } else {
    record.set_f64("PROG-PTR", 0.0_f64);
    }
    { record.set_i64("PROG-PTR", 1); cobol_runtime::set_program_pointer("PROG-PTR", "CANCEL-TEST"); }
    if { let _l = record.get_display_unsigned("PROG-PTR"); let _r = "0000000000000000".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) == format!("{:<w$}", _r, w = _w) } {
    { eprintln!("{}", "address of cancel-prog not set".to_string()); use std::io::Write; std::io::stdout().flush().ok(); }
    } else {
    record.set_f64("PROG-PTR", 0.0_f64);
    }
}

