// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone)]
pub struct ProgramState {
    /// Y
    pub y: FixedString<20>,
    /// Z
    pub z: FixedString<20>,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            y: Default::default(),
            z: FixedString::from_cobol_str("ALL"),
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// Y
fn p_y(state: &mut ProgramState) {
    {
        let mut _str_ptr: usize = 1;
        string_append(state.z.as_bytes_mut(), &mut _str_ptr, state.y.as_bytes());
    }
    if &format!("{}", state.z) != &"zz1114446665defxxzz_".to_string() {
        println!("{}", state.z);
        { std::process::exit(0); }
    }
}

fn main() {
    let mut state = ProgramState::default();
    p_y(&mut state);
}

