// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone)]
pub struct ProgramState {
    /// X
    pub x: FixedString<1>,
    /// Y
    pub y: u32,
    /// Z
    pub z: u32,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            x: Default::default(),
            y: Default::default(),
            z: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// X
fn p_x(state: &mut ProgramState) {
    state.y = 12 as u32;
    state.z = 34 as u32;
    {
        let mut _p1 = (state.x).clone();
        let mut _p2 = (state.y).clone();
        let mut _p3 = (state.z).clone();
        callee(&mut _p1, &mut _p2, &mut _p3);
        state.x = _p1;
        state.y = _p2;
        state.z = _p3;
    }
    if ((&format!("{}", state.x) != &"X".to_string()) || (state.y != 56)) || (state.z != 34) {
        println!("{}{}{}{}{}{}", "X = ", state.x, " Y = ", state.y, " Z = ", state.z);
    }
    { std::process::exit(0); }
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// External: CALL 'CALLEE'
fn callee(_param1: &mut impl std::fmt::Debug, _param2: &mut impl std::fmt::Debug, _param3: &mut impl std::fmt::Debug) {
    todo!("External subroutine 'CALLEE' not yet linked — implement or link the CALLEE module")
}

fn main() {
    let mut state = ProgramState::default();
    p_x(&mut state);
}

