// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct FSeqRecord {
    /// F-SEQ-DATA
    pub f_seq_data: FixedString<5>,
}
impl std::fmt::Display for FSeqRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.f_seq_data)
    }
}
impl From<&str> for FSeqRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for FSeqRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl FSeqRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct FSeqFile {
    /// F-SEQ-RECORD
    pub f_seq_record: FSeqRecord,
}
impl std::fmt::Display for FSeqFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.f_seq_record)
    }
}
impl From<&str> for FSeqFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for FSeqFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl FSeqFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct FTxtRecord {
    /// F-TXT-DATA
    pub f_txt_data: FixedString<10>,
}
impl std::fmt::Display for FTxtRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.f_txt_data)
    }
}
impl From<&str> for FTxtRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for FTxtRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl FTxtRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct FTxtFile {
    /// F-TXT-RECORD
    pub f_txt_record: FTxtRecord,
}
impl std::fmt::Display for FTxtFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.f_txt_record)
    }
}
impl From<&str> for FTxtFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for FTxtFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl FTxtFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Opcode {
    /// OP-QUERY-FILE
    pub op_query_file: FixedString<1>,
    /// OP-OPEN-INPUT
    pub op_open_input: FixedString<1>,
    /// OP-OPEN-OUTPUT
    pub op_open_output: FixedString<1>,
    /// OP-OPEN-I-O
    pub op_open_i_o: FixedString<1>,
    /// OP-WRITE
    pub op_write: FixedString<1>,
    /// OP-RELEASE
    pub op_release: FixedString<1>,
    /// OP-REWRITE
    pub op_rewrite: FixedString<1>,
    /// OP-READ-NEXT
    pub op_read_next: FixedString<1>,
    /// OP-START-EQUAL
    pub op_start_equal: FixedString<1>,
    /// OP-CLOSE
    pub op_close: FixedString<1>,
}
impl std::fmt::Display for Opcode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}", self.op_query_file, self.op_open_input, self.op_open_output, self.op_open_i_o, self.op_write, self.op_release, self.op_rewrite, self.op_read_next, self.op_start_equal, self.op_close)
    }
}
impl From<&str> for Opcode {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Opcode {
    fn from(_s: String) -> Self { Self::default() }
}
impl Opcode {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// FD group: F-SEQ-RECORD
    pub f_seq_record: FixedString<5>,
    /// FD: F-SEQ-DATA
    pub f_seq_data: FixedString<5>,
    /// FD group: F-TXT-RECORD
    pub f_txt_record: FixedString<10>,
    /// FD: F-TXT-DATA
    pub f_txt_data: FixedString<10>,
    /// F-SEQ-STATUS
    pub f_seq_status: FixedString<2>,
    /// F-TXT-STATUS
    pub f_txt_status: FixedString<2>,
    /// OPCODE
    pub opcode: Opcode,
    /// FCD
    pub fcd: FixedString<1>,
    /// EX-FILENAME
    pub ex_filename: FixedString<260>,
    /// EX-RECORD-BUFFER
    pub ex_record_buffer: FixedString<32767>,
    /// File status for F-SEQ-FILE
    pub _fs_f_seq_file: FileStatus,
    /// File handle for F-SEQ-FILE
    pub _fh_f_seq_file: CobolFile,
    /// File status for F-TXT-FILE
    pub _fs_f_txt_file: FileStatus,
    /// File handle for F-TXT-FILE
    pub _fh_f_txt_file: CobolFile,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            f_seq_record: Default::default(),
            f_seq_data: Default::default(),
            f_txt_record: Default::default(),
            f_txt_data: Default::default(),
            f_seq_status: Default::default(),
            f_txt_status: Default::default(),
            opcode: Default::default(),
            fcd: Default::default(),
            ex_filename: Default::default(),
            ex_record_buffer: Default::default(),
            _fs_f_seq_file: FileStatus::Success,
            _fh_f_seq_file: CobolFile::Closed,
            _fs_f_txt_file: FileStatus::Success,
            _fh_f_txt_file: CobolFile::Closed,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// MAIN-RTN
fn p_main_rtn(state: &mut ProgramState) {
    f_seq_file_open_output(state);
    state.f_seq_data = "SEQ01".into();
    f_seq_record_write(state);
    state.f_seq_data = "SEQ02".into();
    f_seq_record_write(state);
    state.f_seq_data = "SEQ03".into();
    f_seq_record_write(state);
    state.f_seq_data = "SEQ04".into();
    f_seq_record_write(state);
    state.f_seq_data = "SEQ05".into();
    f_seq_record_write(state);
    f_seq_file_close(state);
    f_txt_file_open_output(state);
    state.f_txt_data = "TXTA123456".into();
    f_txt_record_write(state);
    state.f_txt_data = "TXTB123456".into();
    f_txt_record_write(state);
    state.f_txt_data = "TXTC123456".into();
    f_txt_record_write(state);
    state.f_txt_data = "TXTD123456".into();
    f_txt_record_write(state);
    f_txt_file_close(state);
    state.fcd = FixedString::low_values();
    // SKIP: unresolved ref: state._unresolved_fcd_version = state._unresolved_fcd__version_number.clone();
    // SKIP: unresolved ref: state._unresolved_fcd_filename_address = &state.ex_filename as *const _ as usize;
    // SKIP: unresolved ref: state._unresolved_fcd_name_length = 80;
    // SKIP: unresolved ref: state._unresolved_fcd_record_address = &state.ex_record_buffer as *const _ as usize;
    // SKIP: unresolved ref: state._unresolved_fcd_organization = state._unresolved_fcd__sequential_org.clone();
    state.ex_filename = "F-SEQ".into();
    {
        let _bytes: &[u8] = b"  ";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+1); state.opcode.op_query_file = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
        if _len > 1 { let _end = _len.min(1+1); state.opcode.op_open_input = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        if _len > 2 { let _end = _len.min(2+1); state.opcode.op_open_output = FixedString::from(String::from_utf8_lossy(&_bytes[2.._end])); }
        if _len > 3 { let _end = _len.min(3+1); state.opcode.op_open_i_o = FixedString::from(String::from_utf8_lossy(&_bytes[3.._end])); }
        if _len > 4 { let _end = _len.min(4+1); state.opcode.op_write = FixedString::from(String::from_utf8_lossy(&_bytes[4.._end])); }
        if _len > 5 { let _end = _len.min(5+1); state.opcode.op_release = FixedString::from(String::from_utf8_lossy(&_bytes[5.._end])); }
        if _len > 6 { let _end = _len.min(6+1); state.opcode.op_rewrite = FixedString::from(String::from_utf8_lossy(&_bytes[6.._end])); }
        if _len > 7 { let _end = _len.min(7+1); state.opcode.op_read_next = FixedString::from(String::from_utf8_lossy(&_bytes[7.._end])); }
        if _len > 8 { let _end = _len.min(8+1); state.opcode.op_start_equal = FixedString::from(String::from_utf8_lossy(&_bytes[8.._end])); }
        if _len > 9 { let _end = _len.min(9+1); state.opcode.op_close = FixedString::from(String::from_utf8_lossy(&_bytes[9.._end])); }
    }
    // SKIP: unresolved ref: state._unresolved_fcd_access_mode = state._unresolved_fcd__dynamic_access.clone();
    // SKIP: unresolved ref: state._unresolved_fcd_current_rec_len = 5;
    // SKIP: unresolved ref: state._unresolved_fcd_min_rec_length = 5;
    // SKIP: unresolved ref: state._unresolved_fcd_max_rec_length = 5;
    {
        let mut _p1 = (state.opcode).clone();
        let mut _p2 = (state.fcd).clone();
        extfh(&mut _p1, &mut _p2);
        state.opcode = _p1;
        state.fcd = _p2;
    }
    // SKIP: unresolved display ref
    {
        let _bytes: &[u8] = b"  ";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+1); state.opcode.op_query_file = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
        if _len > 1 { let _end = _len.min(1+1); state.opcode.op_open_input = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        if _len > 2 { let _end = _len.min(2+1); state.opcode.op_open_output = FixedString::from(String::from_utf8_lossy(&_bytes[2.._end])); }
        if _len > 3 { let _end = _len.min(3+1); state.opcode.op_open_i_o = FixedString::from(String::from_utf8_lossy(&_bytes[3.._end])); }
        if _len > 4 { let _end = _len.min(4+1); state.opcode.op_write = FixedString::from(String::from_utf8_lossy(&_bytes[4.._end])); }
        if _len > 5 { let _end = _len.min(5+1); state.opcode.op_release = FixedString::from(String::from_utf8_lossy(&_bytes[5.._end])); }
        if _len > 6 { let _end = _len.min(6+1); state.opcode.op_rewrite = FixedString::from(String::from_utf8_lossy(&_bytes[6.._end])); }
        if _len > 7 { let _end = _len.min(7+1); state.opcode.op_read_next = FixedString::from(String::from_utf8_lossy(&_bytes[7.._end])); }
        if _len > 8 { let _end = _len.min(8+1); state.opcode.op_start_equal = FixedString::from(String::from_utf8_lossy(&_bytes[8.._end])); }
        if _len > 9 { let _end = _len.min(9+1); state.opcode.op_close = FixedString::from(String::from_utf8_lossy(&_bytes[9.._end])); }
    }
    // SKIP: unresolved ref: state._unresolved_fcd_file_status = "00".into();
    // SKIP: unresolved condition
    {
        let _bytes: &[u8] = b"  ";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+1); state.opcode.op_query_file = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
        if _len > 1 { let _end = _len.min(1+1); state.opcode.op_open_input = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        if _len > 2 { let _end = _len.min(2+1); state.opcode.op_open_output = FixedString::from(String::from_utf8_lossy(&_bytes[2.._end])); }
        if _len > 3 { let _end = _len.min(3+1); state.opcode.op_open_i_o = FixedString::from(String::from_utf8_lossy(&_bytes[3.._end])); }
        if _len > 4 { let _end = _len.min(4+1); state.opcode.op_write = FixedString::from(String::from_utf8_lossy(&_bytes[4.._end])); }
        if _len > 5 { let _end = _len.min(5+1); state.opcode.op_release = FixedString::from(String::from_utf8_lossy(&_bytes[5.._end])); }
        if _len > 6 { let _end = _len.min(6+1); state.opcode.op_rewrite = FixedString::from(String::from_utf8_lossy(&_bytes[6.._end])); }
        if _len > 7 { let _end = _len.min(7+1); state.opcode.op_read_next = FixedString::from(String::from_utf8_lossy(&_bytes[7.._end])); }
        if _len > 8 { let _end = _len.min(8+1); state.opcode.op_start_equal = FixedString::from(String::from_utf8_lossy(&_bytes[8.._end])); }
        if _len > 9 { let _end = _len.min(9+1); state.opcode.op_close = FixedString::from(String::from_utf8_lossy(&_bytes[9.._end])); }
    }
    {
        let mut _p1 = (state.opcode).clone();
        let mut _p2 = (state.fcd).clone();
        extfh(&mut _p1, &mut _p2);
        state.opcode = _p1;
        state.fcd = _p2;
    }
    // SKIP: unresolved display ref
    // SKIP: unresolved ref: state._unresolved_fcd_organization = state._unresolved_fcd__line_sequential_org.clone();
    state.ex_filename = "F-TXT".into();
    {
        let _bytes: &[u8] = b"  ";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+1); state.opcode.op_query_file = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
        if _len > 1 { let _end = _len.min(1+1); state.opcode.op_open_input = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        if _len > 2 { let _end = _len.min(2+1); state.opcode.op_open_output = FixedString::from(String::from_utf8_lossy(&_bytes[2.._end])); }
        if _len > 3 { let _end = _len.min(3+1); state.opcode.op_open_i_o = FixedString::from(String::from_utf8_lossy(&_bytes[3.._end])); }
        if _len > 4 { let _end = _len.min(4+1); state.opcode.op_write = FixedString::from(String::from_utf8_lossy(&_bytes[4.._end])); }
        if _len > 5 { let _end = _len.min(5+1); state.opcode.op_release = FixedString::from(String::from_utf8_lossy(&_bytes[5.._end])); }
        if _len > 6 { let _end = _len.min(6+1); state.opcode.op_rewrite = FixedString::from(String::from_utf8_lossy(&_bytes[6.._end])); }
        if _len > 7 { let _end = _len.min(7+1); state.opcode.op_read_next = FixedString::from(String::from_utf8_lossy(&_bytes[7.._end])); }
        if _len > 8 { let _end = _len.min(8+1); state.opcode.op_start_equal = FixedString::from(String::from_utf8_lossy(&_bytes[8.._end])); }
        if _len > 9 { let _end = _len.min(9+1); state.opcode.op_close = FixedString::from(String::from_utf8_lossy(&_bytes[9.._end])); }
    }
    // SKIP: unresolved ref: state._unresolved_fcd_access_mode = state._unresolved_fcd__dynamic_access.clone();
    // SKIP: unresolved ref: state._unresolved_fcd_current_rec_len = 10;
    // SKIP: unresolved ref: state._unresolved_fcd_min_rec_length = 10;
    // SKIP: unresolved ref: state._unresolved_fcd_max_rec_length = 10;
    {
        let mut _p1 = (state.opcode).clone();
        let mut _p2 = (state.fcd).clone();
        extfh(&mut _p1, &mut _p2);
        state.opcode = _p1;
        state.fcd = _p2;
    }
    // SKIP: unresolved display ref
    {
        let _bytes: &[u8] = b"  ";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+1); state.opcode.op_query_file = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
        if _len > 1 { let _end = _len.min(1+1); state.opcode.op_open_input = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        if _len > 2 { let _end = _len.min(2+1); state.opcode.op_open_output = FixedString::from(String::from_utf8_lossy(&_bytes[2.._end])); }
        if _len > 3 { let _end = _len.min(3+1); state.opcode.op_open_i_o = FixedString::from(String::from_utf8_lossy(&_bytes[3.._end])); }
        if _len > 4 { let _end = _len.min(4+1); state.opcode.op_write = FixedString::from(String::from_utf8_lossy(&_bytes[4.._end])); }
        if _len > 5 { let _end = _len.min(5+1); state.opcode.op_release = FixedString::from(String::from_utf8_lossy(&_bytes[5.._end])); }
        if _len > 6 { let _end = _len.min(6+1); state.opcode.op_rewrite = FixedString::from(String::from_utf8_lossy(&_bytes[6.._end])); }
        if _len > 7 { let _end = _len.min(7+1); state.opcode.op_read_next = FixedString::from(String::from_utf8_lossy(&_bytes[7.._end])); }
        if _len > 8 { let _end = _len.min(8+1); state.opcode.op_start_equal = FixedString::from(String::from_utf8_lossy(&_bytes[8.._end])); }
        if _len > 9 { let _end = _len.min(9+1); state.opcode.op_close = FixedString::from(String::from_utf8_lossy(&_bytes[9.._end])); }
    }
    // SKIP: unresolved ref: state._unresolved_fcd_file_status = "00".into();
    // SKIP: unresolved condition
    {
        let _bytes: &[u8] = b"  ";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+1); state.opcode.op_query_file = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
        if _len > 1 { let _end = _len.min(1+1); state.opcode.op_open_input = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        if _len > 2 { let _end = _len.min(2+1); state.opcode.op_open_output = FixedString::from(String::from_utf8_lossy(&_bytes[2.._end])); }
        if _len > 3 { let _end = _len.min(3+1); state.opcode.op_open_i_o = FixedString::from(String::from_utf8_lossy(&_bytes[3.._end])); }
        if _len > 4 { let _end = _len.min(4+1); state.opcode.op_write = FixedString::from(String::from_utf8_lossy(&_bytes[4.._end])); }
        if _len > 5 { let _end = _len.min(5+1); state.opcode.op_release = FixedString::from(String::from_utf8_lossy(&_bytes[5.._end])); }
        if _len > 6 { let _end = _len.min(6+1); state.opcode.op_rewrite = FixedString::from(String::from_utf8_lossy(&_bytes[6.._end])); }
        if _len > 7 { let _end = _len.min(7+1); state.opcode.op_read_next = FixedString::from(String::from_utf8_lossy(&_bytes[7.._end])); }
        if _len > 8 { let _end = _len.min(8+1); state.opcode.op_start_equal = FixedString::from(String::from_utf8_lossy(&_bytes[8.._end])); }
        if _len > 9 { let _end = _len.min(9+1); state.opcode.op_close = FixedString::from(String::from_utf8_lossy(&_bytes[9.._end])); }
    }
    {
        let mut _p1 = (state.opcode).clone();
        let mut _p2 = (state.fcd).clone();
        extfh(&mut _p1, &mut _p2);
        state.opcode = _p1;
        state.fcd = _p2;
    }
    // SKIP: unresolved display ref
}

/// MAIN-EXT
fn p_main_ext(state: &mut ProgramState) {
    { let _ = state._fh_f_seq_file.close();
        let _ = state._fh_f_txt_file.close();
        std::process::exit(0); }
}

/// STUB: p__unnamed
fn p__unnamed(state: &mut ProgramState) {
    // SKIP: unresolved ref
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT F-SEQ-FILE
fn f_seq_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("F_SEQ_FILE").unwrap_or("f_seq_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_f_seq_file = handle; state._fs_f_seq_file = FileStatus::Success; }
        Err(_) => { state._fs_f_seq_file = FileStatus::Error("35".to_string()); }
    }
    state.f_seq_status = FixedString::from(format!("{}", state._fs_f_seq_file));
}

/// OPEN OUTPUT F-SEQ-FILE
fn f_seq_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("F_SEQ_FILE").unwrap_or("f_seq_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_f_seq_file = handle; state._fs_f_seq_file = FileStatus::Success; }
        Err(_) => { state._fs_f_seq_file = FileStatus::Error("35".to_string()); }
    }
    state.f_seq_status = FixedString::from(format!("{}", state._fs_f_seq_file));
}

/// READ F-SEQ-FILE
fn f_seq_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_f_seq_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(5);
            if _len > 0 { let _end = _len.min(0+5); state.f_seq_data = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_f_seq_file = FileStatus::Success;
    state.f_seq_status = FixedString::from(format!("{}", state._fs_f_seq_file));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_f_seq_file = FileStatus::AtEnd;
    state.f_seq_status = FixedString::from(format!("{}", state._fs_f_seq_file));
        }
        Err(e) => {
            state._fs_f_seq_file = e.clone();
    state.f_seq_status = FixedString::from(format!("{}", state._fs_f_seq_file));
        }
    }
    Ok(())
}

/// WRITE to F-SEQ-FILE
fn f_seq_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 5];
    { let _src = state.f_seq_data.as_bytes(); let _end = (0+5).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_f_seq_file.write_record(&_buf) {
        Ok(()) => state._fs_f_seq_file = FileStatus::Success,
        Err(e) => state._fs_f_seq_file = e,
    }
}

/// CLOSE F-SEQ-FILE
fn f_seq_file_close(state: &mut ProgramState) {
    match state._fh_f_seq_file.close() {
        Ok(()) => state._fs_f_seq_file = FileStatus::Success,
        Err(e) => state._fs_f_seq_file = e,
    }
    state.f_seq_status = FixedString::from(format!("{}", state._fs_f_seq_file));
}

/// OPEN I-O F-SEQ-FILE
fn f_seq_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("F_SEQ_FILE").unwrap_or("f_seq_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_f_seq_file = handle; state._fs_f_seq_file = FileStatus::Success; }
        Err(_) => { state._fs_f_seq_file = FileStatus::Error("35".to_string()); }
    }
    state.f_seq_status = FixedString::from(format!("{}", state._fs_f_seq_file));
}

/// OPEN EXTEND F-SEQ-FILE
fn f_seq_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("F_SEQ_FILE").unwrap_or("f_seq_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_f_seq_file = handle; state._fs_f_seq_file = FileStatus::Success; }
        Err(_) => { state._fs_f_seq_file = FileStatus::Error("35".to_string()); }
    }
    state.f_seq_status = FixedString::from(format!("{}", state._fs_f_seq_file));
}

/// OPEN INPUT F-TXT-FILE
fn f_txt_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("F_TXT_FILE").unwrap_or("f_txt_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_f_txt_file = handle; state._fs_f_txt_file = FileStatus::Success; }
        Err(_) => { state._fs_f_txt_file = FileStatus::Error("35".to_string()); }
    }
    state.f_txt_status = FixedString::from(format!("{}", state._fs_f_txt_file));
}

/// OPEN OUTPUT F-TXT-FILE
fn f_txt_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("F_TXT_FILE").unwrap_or("f_txt_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_f_txt_file = handle; state._fs_f_txt_file = FileStatus::Success; }
        Err(_) => { state._fs_f_txt_file = FileStatus::Error("35".to_string()); }
    }
    state.f_txt_status = FixedString::from(format!("{}", state._fs_f_txt_file));
}

/// READ F-TXT-FILE
fn f_txt_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_f_txt_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(10);
            if _len > 0 { let _end = _len.min(0+10); state.f_txt_data = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_f_txt_file = FileStatus::Success;
    state.f_txt_status = FixedString::from(format!("{}", state._fs_f_txt_file));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_f_txt_file = FileStatus::AtEnd;
    state.f_txt_status = FixedString::from(format!("{}", state._fs_f_txt_file));
        }
        Err(e) => {
            state._fs_f_txt_file = e.clone();
    state.f_txt_status = FixedString::from(format!("{}", state._fs_f_txt_file));
        }
    }
    Ok(())
}

/// WRITE to F-TXT-FILE
fn f_txt_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 10];
    { let _src = state.f_txt_data.as_bytes(); let _end = (0+10).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_f_txt_file.write_record(&_buf) {
        Ok(()) => state._fs_f_txt_file = FileStatus::Success,
        Err(e) => state._fs_f_txt_file = e,
    }
}

/// CLOSE F-TXT-FILE
fn f_txt_file_close(state: &mut ProgramState) {
    match state._fh_f_txt_file.close() {
        Ok(()) => state._fs_f_txt_file = FileStatus::Success,
        Err(e) => state._fs_f_txt_file = e,
    }
    state.f_txt_status = FixedString::from(format!("{}", state._fs_f_txt_file));
}

/// OPEN I-O F-TXT-FILE
fn f_txt_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("F_TXT_FILE").unwrap_or("f_txt_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_f_txt_file = handle; state._fs_f_txt_file = FileStatus::Success; }
        Err(_) => { state._fs_f_txt_file = FileStatus::Error("35".to_string()); }
    }
    state.f_txt_status = FixedString::from(format!("{}", state._fs_f_txt_file));
}

/// OPEN EXTEND F-TXT-FILE
fn f_txt_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("F_TXT_FILE").unwrap_or("f_txt_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_f_txt_file = handle; state._fs_f_txt_file = FileStatus::Success; }
        Err(_) => { state._fs_f_txt_file = FileStatus::Error("35".to_string()); }
    }
    state.f_txt_status = FixedString::from(format!("{}", state._fs_f_txt_file));
}

/// WRITE F-SEQ-RECORD
fn f_seq_record_write(state: &mut ProgramState) {
    // Write F-SEQ-RECORD via f_seq_file_write (byte buffer)
    f_seq_file_write(state);
}

/// WRITE F-TXT-RECORD
fn f_txt_record_write(state: &mut ProgramState) {
    // Write F-TXT-RECORD via f_txt_file_write (byte buffer)
    f_txt_file_write(state);
}

/// External: CALL 'EXTFH'
fn extfh(_param1: &mut impl std::fmt::Debug, _param2: &mut impl std::fmt::Debug) {
    todo!("External subroutine 'EXTFH' not yet linked — implement or link the EXTFH module")
}

fn main() {
    let mut state = ProgramState::default();
    p_main_rtn(&mut state);
}

