// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone)]
pub struct ProgramState {
    /// P2
    pub p2: FixedString<3>,
    /// LINKAGE: P1
    pub p1: FixedString<1>,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            p2: Default::default(),
            p1: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// P1
fn p_p1(state: &mut ProgramState) {
    state.p2 = FixedString::copy_from(&state.p1);
    if &format!("{}", state.p2) != &"OK ".to_string() {
        println!("{}", state.p2);
        state.p1 = FixedString::spaces();
    }
}

/// PROGRAM
fn p_program(state: &mut ProgramState) {
}

fn main() {
    let mut state = ProgramState::default();
    p_p1(&mut state);
}

