// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone)]
pub struct ProgramState {
    /// X-ZZZN
    pub x_zzzn: FixedString<4>,
    /// XZN-RED
    pub xzn_red: FixedString<4>,
    /// X-ZZZP
    pub x_zzzp: FixedString<4>,
    /// XZP-RED
    pub xzp_red: FixedString<4>,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            x_zzzn: Default::default(),
            xzn_red: Default::default(),
            x_zzzp: Default::default(),
            xzp_red: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// X-ZZZN
fn p_x_zzzn(state: &mut ProgramState) {
    if &format!("{}", state.xzn_red) != &"  1-".to_string() {
        println!("{}{}{}", "(", state.x_zzzn, ")");
        state.x_zzzn = FixedString::from_cobol_str("0");
        if &format!("{}", state.xzn_red) != &"    ".to_string() {
            println!("{}{}{}", "(", state.x_zzzn, ")");
            state.x_zzzn = FixedString::from_cobol_str("1");
            if &format!("{}", state.xzn_red) != &"  1 ".to_string() {
                println!("{}{}{}", "(", state.x_zzzn, ")");
                state.x_zzzp = FixedString::from_cobol_str("-1");
                if &format!("{}", state.xzp_red) != &"  1-".to_string() {
                    println!("{}{}{}", "(", state.x_zzzp, ")");
                    state.x_zzzp = FixedString::from_cobol_str("0");
                    if &format!("{}", state.xzp_red) != &"    ".to_string() {
                        println!("{}{}{}", "(", state.x_zzzp, ")");
                        state.x_zzzp = FixedString::from_cobol_str("1");
                        if &format!("{}", state.xzp_red) != &"  1+".to_string() {
                            println!("{}{}{}", "(", state.x_zzzp, ")");
                            { std::process::exit(0); }
                        }
                    }
                }
            }
        }
    }
}

fn main() {
    let mut state = ProgramState::default();
    p_x_zzzn(&mut state);
}

