// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.
#![allow(warnings)]

use cobol_runtime::field::*;
use std::collections::HashMap;

#[allow(unused_imports)]
use cobol_runtime::FixedString;
#[allow(unused_imports)]
use cobol_runtime::Decimal;
#[allow(unused_imports)]
use cobol_runtime::PackedDecimal;
#[allow(unused_imports)]
use cobol_runtime::FileStatus;
#[allow(unused_imports)]
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;
#[allow(unused_imports)]
use cobol_runtime::CobolNum;
#[allow(unused_imports)]
use cobol_runtime::CobolToF64;
#[allow(unused_imports)]
use cobol_runtime::CobolTrimmed;
#[allow(unused_imports)]
use cobol_runtime::DisplayWithWidth;
#[allow(unused_imports)]
use cobol_runtime::CobolInto;
#[allow(unused_imports)]
use cobol_runtime::coerce::Coerce;
#[allow(unused_imports)]
use cobol_runtime::screen::{ScreenField, SPos, screen_display};


pub struct ProgramState {
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
        }
    }
}

/// Paragraph: MAIN
fn v2_main(record: &mut CobolRecord) {
    v2_do_check(record);
    { use std::io::Write; let _ = std::io::stdout().flush();  { let _snapshot = cobol_runtime::get_exit_handlers(); for _handler in &_snapshot { if !cobol_runtime::is_exit_handler_registered(_handler) { continue; } match _handler.to_uppercase().as_str() { "MAIN" => { v2_main(record); } "DO-CHECK" => { v2_do_check(record); } _ => {} } } } cobol_runtime::maybe_dump_record(record, "run_functions_011_FUNCTION_HEX-OF_and_HEX-TO-CHAR"); std::process::exit(record.get_f64("RETURN-CODE") as i32); }
}

/// Paragraph: DO-CHECK
fn v2_do_check(record: &mut CobolRecord) {
    record.fill_bytes("HEXX", b"-");
    {
    let _into_name: &str = "HEXX";
    let mut _result = String::new();
    _result.push_str(&{ let _bytes = record.get_bytes("X"); _bytes.iter().map(|b| format!("{:02X}", b)).collect::<String>() });
    let _into_size = record.get_field(_into_name).map_or(0, |f| f.size);
    let _overflow = _result.len() > _into_size;
    if !_overflow {
    { let mut _buf = record.get_display(_into_name).into_bytes(); while _buf.len() < _into_size { _buf.push(b' '); } let _wlen = _result.len().min(_into_size); for _i in 0.._wlen { _buf[_i] = _result.as_bytes()[_i]; } record.set_bytes(_into_name, &_buf[.._into_size]); }
    }
    }
    if { let _l = record.get_display("HEXX"); let _r = "20303132--".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    if record.get_i64("FILLER") == 0 {
    { println!("{}{}", "UNEXPECTED HEX-VALUE OF '0012': ".to_string(), record.get_display("HEXX")); use std::io::Write; std::io::stdout().flush().ok(); }
    }
    }
    record.fill_bytes("HEXX", b"-");
    {
    let _into_name: &str = "HEXX";
    let mut _result = String::new();
    _result.push_str(&{ let _bytes = record.get_bytes("Y"); _bytes.iter().map(|b| format!("{:02X}", b)).collect::<String>() });
    let _into_size = record.get_field(_into_name).map_or(0, |f| f.size);
    let _overflow = _result.len() > _into_size;
    if !_overflow {
    { let mut _buf = record.get_display(_into_name).into_bytes(); while _buf.len() < _into_size { _buf.push(b' '); } let _wlen = _result.len().min(_into_size); for _i in 0.._wlen { _buf[_i] = _result.as_bytes()[_i]; } record.set_bytes(_into_name, &_buf[.._into_size]); }
    }
    }
    if { let _l = record.get_display("HEXX"); let _r = "48492E20--".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    if record.get_i64("FILLER") == 0 {
    { println!("{}{}", "UNEXPECTED HEX-VALUE OF 'HI! ': ".to_string(), record.get_display("HEXX")); use std::io::Write; std::io::stdout().flush().ok(); }
    }
    }
    record.fill_bytes("HEXX", b"-");
    {
    let _into_name: &str = "HEXX";
    let mut _result = String::new();
    _result.push_str(&{ let _bytes = record.get_bytes("BIN"); _bytes.iter().map(|b| format!("{:02X}", b)).collect::<String>() });
    let _into_size = record.get_field(_into_name).map_or(0, |f| f.size);
    let _overflow = _result.len() > _into_size;
    if !_overflow {
    { let mut _buf = record.get_display(_into_name).into_bytes(); while _buf.len() < _into_size { _buf.push(b' '); } let _wlen = _result.len().min(_into_size); for _i in 0.._wlen { _buf[_i] = _result.as_bytes()[_i]; } record.set_bytes(_into_name, &_buf[.._into_size]); }
    }
    }
    if { let _l = record.get_display("HEXX"); let _r = "0000000C--".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    if record.get_i64("FILLER") == 0 {
    { println!("{}{}", "UNEXPECTED HEX-VALUE OF BIN 12: ".to_string(), record.get_display("HEXX")); use std::io::Write; std::io::stdout().flush().ok(); }
    }
    }
    record.fill_bytes("HEXX", b"-");
    {
    let _into_name: &str = "HEXX";
    let mut _result = String::new();
    _result.push_str(&{ let _bytes = record.get_bytes("PAC"); _bytes.iter().map(|b| format!("{:02X}", b)).collect::<String>() });
    let _into_size = record.get_field(_into_name).map_or(0, |f| f.size);
    let _overflow = _result.len() > _into_size;
    if !_overflow {
    { let mut _buf = record.get_display(_into_name).into_bytes(); while _buf.len() < _into_size { _buf.push(b' '); } let _wlen = _result.len().min(_into_size); for _i in 0.._wlen { _buf[_i] = _result.as_bytes()[_i]; } record.set_bytes(_into_name, &_buf[.._into_size]); }
    }
    }
    if { let _l = record.get_display("HEXX"); let _r = "01234F----".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    if record.get_i64("FILLER") == 0 {
    { println!("{}{}", "UNEXPECTED HEX-VALUE OF PACKED 1234: ".to_string(), record.get_display("HEXX")); use std::io::Write; std::io::stdout().flush().ok(); }
    }
    }
    record.fill_bytes("HEXX", b"-");
    {
    let _into_name: &str = "HEXX";
    let mut _result = String::new();
    _result.push_str(&{ let _s = String::from_utf8_lossy(&[0x30u8, 0x31u8, 0x00u8]).to_string(); _s.as_bytes().iter().map(|b| format!("{:02X}", b)).collect::<String>() });
    let _into_size = record.get_field(_into_name).map_or(0, |f| f.size);
    let _overflow = _result.len() > _into_size;
    if !_overflow {
    { let mut _buf = record.get_display(_into_name).into_bytes(); while _buf.len() < _into_size { _buf.push(b' '); } let _wlen = _result.len().min(_into_size); for _i in 0.._wlen { _buf[_i] = _result.as_bytes()[_i]; } record.set_bytes(_into_name, &_buf[.._into_size]); }
    }
    }
    if { let _l = record.get_display("HEXX"); let _r = "303100----".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    if record.get_i64("FILLER") == 0 {
    { println!("{}{}", "UNEXPECTED HEX-VALUE OF z'01': ".to_string(), record.get_display("HEXX")); use std::io::Write; std::io::stdout().flush().ok(); }
    }
    }
    record.fill_bytes("HEXX", b"-");
    {
    let _into_name: &str = "HEXX";
    let mut _result = String::new();
    _result.push_str(&{ let _s = " ".to_string(); _s.as_bytes().iter().map(|b| format!("{:02X}", b)).collect::<String>() });
    let _into_size = record.get_field(_into_name).map_or(0, |f| f.size);
    let _overflow = _result.len() > _into_size;
    if !_overflow {
    { let mut _buf = record.get_display(_into_name).into_bytes(); while _buf.len() < _into_size { _buf.push(b' '); } let _wlen = _result.len().min(_into_size); for _i in 0.._wlen { _buf[_i] = _result.as_bytes()[_i]; } record.set_bytes(_into_name, &_buf[.._into_size]); }
    }
    }
    if { let _l = record.get_display("HEXX"); let _r = "20--------".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    if record.get_i64("FILLER") == 0 {
    { println!("{}{}", "UNEXPECTED HEX-VALUE OF ' ': ".to_string(), record.get_display("HEXX")); use std::io::Write; std::io::stdout().flush().ok(); }
    }
    }
    record.fill_bytes("HEXX", b"-");
    {
    let _into_name: &str = "HEXX";
    let mut _result = String::new();
    _result.push_str(&"0020".to_string());
    let _into_size = record.get_field(_into_name).map_or(0, |f| f.size);
    let _overflow = _result.len() > _into_size;
    if !_overflow {
    { let mut _buf = record.get_display(_into_name).into_bytes(); while _buf.len() < _into_size { _buf.push(b' '); } let _wlen = _result.len().min(_into_size); for _i in 0.._wlen { _buf[_i] = _result.as_bytes()[_i]; } record.set_bytes(_into_name, &_buf[.._into_size]); }
    }
    }
    if { let _l = record.get_display("HEXX"); let _r = "0020------".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    if record.get_i64("FILLER") == 0 {
    { println!("{}{}", "UNEXPECTED HEX-VALUE OF n' ': ".to_string(), record.get_display("HEXX")); use std::io::Write; std::io::stdout().flush().ok(); }
    }
    }
    record.fill_bytes("HEXX", b"-");
    {
    let _into_name: &str = "HEXX";
    let mut _result = String::new();
    _result.push_str(&{ let _s = String::from_utf8_lossy(&[0x30u8, 0x31u8, 0x00u8]).to_string(); _s.as_bytes().iter().map(|b| format!("{:02X}", b)).collect::<String>() });
    let _into_size = record.get_field(_into_name).map_or(0, |f| f.size);
    let _overflow = _result.len() > _into_size;
    if !_overflow {
    { let mut _buf = record.get_display(_into_name).into_bytes(); while _buf.len() < _into_size { _buf.push(b' '); } let _wlen = _result.len().min(_into_size); for _i in 0.._wlen { _buf[_i] = _result.as_bytes()[_i]; } record.set_bytes(_into_name, &_buf[.._into_size]); }
    }
    }
    if { let _l = { let _h = record.get_refmod("HEXX", 1i64 as usize, 6i64 as usize); let _t = _h.trim(); let _bytes: Vec<u8> = (0.._t.len()/2).filter_map(|i| u8::from_str_radix(&_t[i*2..i*2+2], 16).ok()).collect(); unsafe { String::from_utf8_unchecked(_bytes) } }; let _r = String::from_utf8_lossy(&[0x30u8, 0x31u8, 0x00u8]).to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    if record.get_i64("FILLER") == 0 {
    { println!("{}{}", "UNEXPECTED CHAR VALUE, does not match z'01': ".to_string(), record.get_refmod("HEXX", 1i64 as usize, 6i64 as usize)); use std::io::Write; std::io::stdout().flush().ok(); }
    }
    }
    record.fill_bytes("HEXX", b"-");
    {
    let _into_name: &str = "HEXX";
    let mut _result = String::new();
    _result.push_str(&{ let _h = "3132".to_string(); let _t = _h.trim(); let _bytes: Vec<u8> = (0.._t.len()/2).filter_map(|i| u8::from_str_radix(&_t[i*2..i*2+2], 16).ok()).collect(); unsafe { String::from_utf8_unchecked(_bytes) } });
    let _into_size = record.get_field(_into_name).map_or(0, |f| f.size);
    let _overflow = _result.len() > _into_size;
    if !_overflow {
    { let mut _buf = record.get_display(_into_name).into_bytes(); while _buf.len() < _into_size { _buf.push(b' '); } let _wlen = _result.len().min(_into_size); for _i in 0.._wlen { _buf[_i] = _result.as_bytes()[_i]; } record.set_bytes(_into_name, &_buf[.._into_size]); }
    }
    }
    if !(({ let _lb = record.get_refmod("HEXX", 1i64 as usize, 2i64 as usize).as_bytes().to_vec(); let _rb: &[u8] = &[0x31u8, 0x32u8]; let _w = _lb.len().max(_rb.len()); let mut _lp = _lb.to_vec(); _lp.resize(_w, 0x20); let mut _rp = _rb.to_vec(); _rp.resize(_w, 0x20); _lp == _rp } && { let _l = record.get_refmod("HEXX", 3i64 as usize, usize::MAX); let _r = "--------".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) == format!("{:<w$}", _r, w = _w) })) {
    if record.get_i64("FILLER") == 0 {
    { println!("{}{}", "UNEXPECTED CHAR VALUE, expected 12-* got: ".to_string(), record.get_display("HEXX")); use std::io::Write; std::io::stdout().flush().ok(); }
    }
    }
    record.fill_bytes("HEXX", b"-");
    {
    let _into_name: &str = "HEXX";
    let mut _result = String::new();
    _result.push_str(&{ let _h = "3132".to_string(); let _t = _h.trim(); let _bytes: Vec<u8> = (0.._t.len()/2).filter_map(|i| u8::from_str_radix(&_t[i*2..i*2+2], 16).ok()).collect(); unsafe { String::from_utf8_unchecked(_bytes) } });
    let _into_size = record.get_field(_into_name).map_or(0, |f| f.size);
    let _overflow = _result.len() > _into_size;
    if !_overflow {
    { let mut _buf = record.get_display(_into_name).into_bytes(); while _buf.len() < _into_size { _buf.push(b' '); } let _wlen = _result.len().min(_into_size); for _i in 0.._wlen { _buf[_i] = _result.as_bytes()[_i]; } record.set_bytes(_into_name, &_buf[.._into_size]); }
    }
    }
    if !(({ let _lb = record.get_refmod("HEXX", 1i64 as usize, 2i64 as usize).as_bytes().to_vec(); let _rb: &[u8] = &[0x31u8, 0x32u8]; let _w = _lb.len().max(_rb.len()); let mut _lp = _lb.to_vec(); _lp.resize(_w, 0x20); let mut _rp = _rb.to_vec(); _rp.resize(_w, 0x20); _lp == _rp } && { let _l = record.get_refmod("HEXX", 3i64 as usize, usize::MAX); let _r = "--------".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) == format!("{:<w$}", _r, w = _w) })) {
    if record.get_i64("FILLER") == 0 {
    { println!("{}{}", "UNEXPECTED CHAR VALUE, expected 12-* got: ".to_string(), record.get_display("HEXX")); use std::io::Write; std::io::stdout().flush().ok(); }
    }
    }
}

fn main() {
    let mut record = CobolRecord::new(654, vec![
        FieldDescriptor { name: "X".into(), offset: 0, size: 4, field_type: FieldType::Group, pic_scale: 0, pic_digits: 0, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER".into(), offset: 0, size: 1, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__2".into(), offset: 1, size: 3, field_type: FieldType::NumericDisplay, pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "Y".into(), offset: 4, size: 4, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "BIN".into(), offset: 8, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "PAC".into(), offset: 12, size: 3, field_type: FieldType::Packed, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "N9".into(), offset: 15, size: 2, field_type: FieldType::NumericDisplay, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "NX".into(), offset: 17, size: 4, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 0, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "HEXX".into(), offset: 21, size: 10, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 10, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__3".into(), offset: 31, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 10, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "TALLY".into(), offset: 35, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "RETURN-CODE".into(), offset: 39, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SORT-RETURN".into(), offset: 43, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "NUMBER-OF-CALL-PARAMETERS".into(), offset: 47, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LINAGE-COUNTER".into(), offset: 51, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LINE-COUNTER".into(), offset: 55, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "PAGE-COUNTER".into(), offset: 59, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SYSTEM-OFFSET".into(), offset: 63, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-CODE".into(), offset: 67, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "JSON-CODE".into(), offset: 71, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LIN".into(), offset: 75, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COL".into(), offset: 79, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COB-CRT-STATUS".into(), offset: 83, size: 4, field_type: FieldType::NumericDisplay, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "DEBUG-ITEM".into(), offset: 87, size: 86, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 86, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COB-CURRENT-DATE".into(), offset: 173, size: 26, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 26, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-STATUS".into(), offset: 199, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-FILE".into(), offset: 230, size: 30, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 30, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-LOCATION".into(), offset: 260, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-STATEMENT".into(), offset: 291, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "MODULE-CALLER-ID".into(), offset: 322, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "WHEN-COMPILED".into(), offset: 353, size: 16, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 16, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-EVENT".into(), offset: 369, size: 30, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 30, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-TEXT".into(), offset: 399, size: 255, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 255, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },]);
    let record = &mut record;
    record.fill_field("FILLER", 0x20);
    record.set_f64("FILLER__2", 12_f64);
    record.set_bytes("Y", b"HI.");
    record.set_f64("BIN", 12_f64);
    record.set_f64("PAC", 1234_f64);
    record.set_f64("N9", 12_f64);
    record.set_bytes("NX", &[0x01, 0x4E, 0x21]);
    record.set_f64("FILLER__3", 0_f64);
    { let now = cobol_runtime::chrono_shim::Local::now(); let wc = now.format("%d/%m/%y%H.%M.%S").to_string(); record.set_raw_string("WHEN-COMPILED", &wc); }
    v2_main(record);
    v2_do_check(record);
}

