// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct Rec {
    /// A
    pub a: FixedString<3>,
    /// B
    pub b: FixedString<3>,
    /// C
    pub c: C,
}
impl std::fmt::Display for Rec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.a, self.b, self.c)
    }
}
impl From<&str> for Rec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Rec {
    fn from(_s: String) -> Self { Self::default() }
}
impl Rec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct C {
    /// D
    pub d: FixedString<3>,
}
impl std::fmt::Display for C {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.d)
    }
}
impl From<&str> for C {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for C {
    fn from(_s: String) -> Self { Self::default() }
}
impl C {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Employee {
    /// ID
    pub id: u32,
    /// NAME
    pub name: FixedString<10>,
    /// DEPT
    pub dept: FixedString<10>,
}
impl std::fmt::Display for Employee {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.id, self.name, self.dept)
    }
}
impl From<&str> for Employee {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Employee {
    fn from(_s: String) -> Self { Self::default() }
}
impl Employee {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// NAMESPACE-STR
    pub namespace_str: FixedString<100>,
    /// PREFIX-STR
    pub prefix_str: FixedString<100>,
    /// OUT
    pub out: FixedString<200>,
    /// REC
    pub rec: Rec,
    /// A
    pub a: FixedString<3>,
    /// B
    pub b: FixedString<3>,
    /// C
    pub c: C,
    /// D
    pub d: FixedString<3>,
    /// 0SPECIALTAGNAME
    pub p_0specialtagname: FixedString<3>,
    /// EMPLOYEE
    pub employee: Employee,
    /// ID
    pub id: u32,
    /// NAME
    pub name: FixedString<10>,
    /// DEPT
    pub dept: FixedString<10>,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            namespace_str: FixedString::from_cobol_str("http://www.w3.org/1999/xhtml"),
            prefix_str: FixedString::from_cobol_str("pre"),
            out: Default::default(),
            rec: Default::default(),
            a: Default::default(),
            b: Default::default(),
            c: Default::default(),
            d: Default::default(),
            p_0specialtagname: FixedString::from_cobol_str("abc"),
            employee: Default::default(),
            id: Default::default(),
            name: Default::default(),
            dept: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// ATTRIBUTES
fn p_attributes(state: &mut ProgramState) {
    if &format!("{}", state.out) != &"<c d=\" \"/>".to_string() {
        println!("{}{}", "Test 3 failed: ", state.out);
    }
    state.rec.a = FixedString::from_cobol_str(&format!("{}", "A"));
    // SKIP: unresolved ref
    if &format!("{}", state.out) != &"<rec>AAABBB<c>CCC</c></rec>".to_string() {
        println!("{}{}", "Test 4 failed: ", state.out);
    }
    // XML GENERATE OUT FROM REC
    // AUTO-FIX SKIP: unresolved module: state.out = serde_xml_rs::to_string(&state.rec).unwrap_or_default().into();
    // XML GENERATE OUT FROM EMPLOYEE
    // AUTO-FIX SKIP: unresolved module: state.out = serde_xml_rs::to_string(&state.employee).unwrap_or_default().into();
}

fn main() {
    let mut state = ProgramState::default();
    p_attributes(&mut state);
}

