// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.
#![allow(warnings)]

use cobol_runtime::field::*;
use std::collections::HashMap;

#[allow(unused_imports)]
use cobol_runtime::FixedString;
#[allow(unused_imports)]
use cobol_runtime::Decimal;
#[allow(unused_imports)]
use cobol_runtime::PackedDecimal;
#[allow(unused_imports)]
use cobol_runtime::FileStatus;
#[allow(unused_imports)]
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;
#[allow(unused_imports)]
use cobol_runtime::CobolNum;
#[allow(unused_imports)]
use cobol_runtime::CobolToF64;
#[allow(unused_imports)]
use cobol_runtime::CobolTrimmed;
#[allow(unused_imports)]
use cobol_runtime::DisplayWithWidth;
#[allow(unused_imports)]
use cobol_runtime::CobolInto;
#[allow(unused_imports)]
use cobol_runtime::coerce::Coerce;
#[allow(unused_imports)]
use cobol_runtime::screen::{ScreenField, SPos, screen_display};


pub struct ProgramState {
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
        }
    }
}

/// Paragraph: S
fn v2_s(record: &mut CobolRecord) {
}

/// Paragraph: SHOW
fn v2_show(record: &mut CobolRecord) {
    { println!("{}{}{}{}{}{}{}", "EBCDIC LIT ".to_string(), record.get_display("T"), " FAILED: X = ".to_string(), "".to_string(), record.get_display("X"), "".to_string(), "".to_string()); use std::io::Write; std::io::stdout().flush().ok(); }
    record.set_f64("S", 1_f64);
}

fn main() {
    let mut record = CobolRecord::new(635, vec![
        FieldDescriptor { name: "X".into(), offset: 0, size: 11, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 11, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "T".into(), offset: 11, size: 1, field_type: FieldType::NumericDisplay, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "S".into(), offset: 12, size: 4, field_type: FieldType::Float32, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "TALLY".into(), offset: 16, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "RETURN-CODE".into(), offset: 20, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SORT-RETURN".into(), offset: 24, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "NUMBER-OF-CALL-PARAMETERS".into(), offset: 28, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LINAGE-COUNTER".into(), offset: 32, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LINE-COUNTER".into(), offset: 36, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "PAGE-COUNTER".into(), offset: 40, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SYSTEM-OFFSET".into(), offset: 44, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-CODE".into(), offset: 48, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "JSON-CODE".into(), offset: 52, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LIN".into(), offset: 56, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COL".into(), offset: 60, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COB-CRT-STATUS".into(), offset: 64, size: 4, field_type: FieldType::NumericDisplay, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "DEBUG-ITEM".into(), offset: 68, size: 86, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 86, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COB-CURRENT-DATE".into(), offset: 154, size: 26, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 26, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-STATUS".into(), offset: 180, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-FILE".into(), offset: 211, size: 30, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 30, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-LOCATION".into(), offset: 241, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-STATEMENT".into(), offset: 272, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "MODULE-CALLER-ID".into(), offset: 303, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "WHEN-COMPILED".into(), offset: 334, size: 16, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 16, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-EVENT".into(), offset: 350, size: 30, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 30, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-TEXT".into(), offset: 380, size: 255, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 255, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },]);
    let record = &mut record;
    record.set_f64("S", 0.0);
    { let now = cobol_runtime::chrono_shim::Local::now(); let wc = now.format("%d/%m/%y%H.%M.%S").to_string(); record.set_raw_string("WHEN-COMPILED", &wc); }
    record.set_f64("T", 1_f64);
    record.set_bytes("X", b"foobarBAZ");
    if { let _l = record.get_display("X"); let _r = "foobarBAZ".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    v2_show(record);
    }
    record.set_f64("T", 2_f64);
    record.set_bytes("X", b"  foobarBAZ");
    if { let _l = record.get_display("X"); let _r = "  foobarBAZ".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    v2_show(record);
    }
    record.set_f64("T", 3_f64);
    record.set_bytes("X", b" foobarBAZ");
    if { let _l = record.get_display("X"); let _r = " foobarBAZ".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    v2_show(record);
    }
    record.set_f64("T", 4_f64);
    record.set_bytes("X", b"[!]");
    if { let _l = record.get_display("X"); let _r = "[!]".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    v2_show(record);
    }
    { use std::io::Write; let _ = std::io::stdout().flush();  { let _snapshot = cobol_runtime::get_exit_handlers(); for _handler in &_snapshot { if !cobol_runtime::is_exit_handler_registered(_handler) { continue; } match _handler.to_uppercase().as_str() { "S" => { v2_s(record); } "SHOW" => { v2_show(record); } _ => {} } } } cobol_runtime::end_of_program_prompt(); cobol_runtime::maybe_dump_record(record, "run_extensions_105_GCOS_literals_with_EBCDIC_symbols__run_"); std::process::exit(record.get_f64("RETURN-CODE") as i32); }
    v2_s(record);
    v2_show(record);
}

