// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.
#![allow(warnings)]

use cobol_runtime::field::*;
use std::collections::HashMap;

#[allow(unused_imports)]
use cobol_runtime::FixedString;
#[allow(unused_imports)]
use cobol_runtime::Decimal;
#[allow(unused_imports)]
use cobol_runtime::PackedDecimal;
#[allow(unused_imports)]
use cobol_runtime::FileStatus;
#[allow(unused_imports)]
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;
#[allow(unused_imports)]
use cobol_runtime::CobolNum;
#[allow(unused_imports)]
use cobol_runtime::CobolToF64;
#[allow(unused_imports)]
use cobol_runtime::CobolTrimmed;
#[allow(unused_imports)]
use cobol_runtime::DisplayWithWidth;
#[allow(unused_imports)]
use cobol_runtime::CobolInto;
#[allow(unused_imports)]
use cobol_runtime::coerce::Coerce;
#[allow(unused_imports)]
use cobol_runtime::screen::{ScreenField, SPos, screen_display};


pub struct ProgramState {
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
        }
    }
}

fn main() {
    let mut record = CobolRecord::new(1396, vec![
        FieldDescriptor { name: "DUMMY".into(), offset: 0, size: 10, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 10, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SUCCESS-FLAG".into(), offset: 10, size: 1, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SCR".into(), offset: 11, size: 766, field_type: FieldType::Group, pic_scale: 0, pic_digits: 0, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER".into(), offset: 11, size: 80, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 80, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__2".into(), offset: 91, size: 80, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 80, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__3".into(), offset: 171, size: 80, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 80, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__4".into(), offset: 251, size: 71, field_type: FieldType::Group, pic_scale: 0, pic_digits: 0, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__5".into(), offset: 251, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__6".into(), offset: 259, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__7".into(), offset: 267, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__8".into(), offset: 275, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__9".into(), offset: 283, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__10".into(), offset: 291, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__11".into(), offset: 299, size: 15, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 15, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__12".into(), offset: 314, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__13".into(), offset: 322, size: 71, field_type: FieldType::Group, pic_scale: 0, pic_digits: 0, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__14".into(), offset: 322, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__15".into(), offset: 330, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__16".into(), offset: 338, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__17".into(), offset: 346, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__18".into(), offset: 354, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__19".into(), offset: 362, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__20".into(), offset: 370, size: 15, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 15, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__21".into(), offset: 385, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__22".into(), offset: 393, size: 1, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__23".into(), offset: 394, size: 80, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 80, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__24".into(), offset: 474, size: 80, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 80, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__25".into(), offset: 554, size: 80, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 80, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__26".into(), offset: 634, size: 71, field_type: FieldType::Group, pic_scale: 0, pic_digits: 0, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__27".into(), offset: 634, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__28".into(), offset: 642, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__29".into(), offset: 650, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__30".into(), offset: 658, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__31".into(), offset: 666, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__32".into(), offset: 674, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__33".into(), offset: 682, size: 15, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 15, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__34".into(), offset: 697, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__35".into(), offset: 705, size: 71, field_type: FieldType::Group, pic_scale: 0, pic_digits: 0, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__36".into(), offset: 705, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__37".into(), offset: 713, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__38".into(), offset: 721, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__39".into(), offset: 729, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__40".into(), offset: 737, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__41".into(), offset: 745, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__42".into(), offset: 753, size: 15, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 15, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__43".into(), offset: 768, size: 8, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 8, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SUCCESS-FIELD".into(), offset: 776, size: 1, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "TALLY".into(), offset: 777, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "RETURN-CODE".into(), offset: 781, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SORT-RETURN".into(), offset: 785, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "NUMBER-OF-CALL-PARAMETERS".into(), offset: 789, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LINAGE-COUNTER".into(), offset: 793, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LINE-COUNTER".into(), offset: 797, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "PAGE-COUNTER".into(), offset: 801, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SYSTEM-OFFSET".into(), offset: 805, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-CODE".into(), offset: 809, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "JSON-CODE".into(), offset: 813, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LIN".into(), offset: 817, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COL".into(), offset: 821, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COB-CRT-STATUS".into(), offset: 825, size: 4, field_type: FieldType::NumericDisplay, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "DEBUG-ITEM".into(), offset: 829, size: 86, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 86, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COB-CURRENT-DATE".into(), offset: 915, size: 26, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 26, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-STATUS".into(), offset: 941, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-FILE".into(), offset: 972, size: 30, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 30, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-LOCATION".into(), offset: 1002, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-STATEMENT".into(), offset: 1033, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "MODULE-CALLER-ID".into(), offset: 1064, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "WHEN-COMPILED".into(), offset: 1095, size: 16, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 16, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-EVENT".into(), offset: 1111, size: 30, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 30, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-TEXT".into(), offset: 1141, size: 255, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 255, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },]);
    let record = &mut record;
    record.set_bytes("FILLER", &[0x45, 0x6E, 0x74, 0x65, 0x72, 0x20, 0x22, 0x79, 0x22, 0x20, 0x69, 0x66, 0x20, 0x74, 0x68, 0x65, 0x20, 0x74, 0x65, 0x78, 0x74, 0x20, 0x62, 0x65, 0x6C, 0x6F, 0x77, 0x20, 0x6D, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x20, 0x74, 0x68, 0x65, 0x20, 0x63, 0x6F, 0x6C, 0x6F, 0x75, 0x72, 0x20, 0x6F, 0x66, 0x20, 0x74, 0x68, 0x65, 0x20, 0x62, 0x61, 0x63, 0x6B, 0x67, 0x72, 0x6F, 0x75, 0x6E, 0x64, 0x2F, 0x74, 0x65, 0x78, 0x74, 0x2E]);
    record.set_bytes("FILLER__2", b"Note: the black text is on white background/the white background has black text");
    record.set_bytes("FILLER__3", b"to make the text visible.");
    record.set_bytes("FILLER__5", b"Black");
    record.set_bytes("FILLER__6", b"Blue");
    record.set_bytes("FILLER__7", b"Green");
    record.set_bytes("FILLER__8", b"Cyan");
    record.set_bytes("FILLER__9", b"Red");
    record.set_bytes("FILLER__10", b"Magenta");
    record.set_bytes("FILLER__11", b"Brown/Yellow");
    record.set_bytes("FILLER__12", b"White");
    record.set_bytes("FILLER__14", b"Black");
    record.set_bytes("FILLER__15", b"Blue");
    record.set_bytes("FILLER__16", b"Green");
    record.set_bytes("FILLER__17", b"Cyan");
    record.set_bytes("FILLER__18", b"Red");
    record.set_bytes("FILLER__19", b"Magenta");
    record.set_bytes("FILLER__20", b"Brown/Yellow");
    record.set_bytes("FILLER__21", b"White");
    record.set_bytes("FILLER__23", &[0x54, 0x68, 0x65, 0x20, 0x66, 0x6F, 0x6C, 0x6C, 0x6F, 0x77, 0x69, 0x6E, 0x67, 0x20, 0x69, 0x73, 0x20, 0x74, 0x68, 0x65, 0x20, 0x73, 0x61, 0x6D, 0x65, 0x20, 0x61, 0x73, 0x20, 0x61, 0x62, 0x6F, 0x76, 0x65, 0x2C, 0x20, 0x77, 0x69, 0x74, 0x68, 0x20, 0x22, 0x65, 0x78, 0x74, 0x65, 0x6E, 0x64, 0x65, 0x64, 0x22, 0x20, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x20, 0x73, 0x65, 0x74, 0x3B]);
    record.set_bytes("FILLER__24", b"this should have the same effect as otherwise highlighted for the first line");
    record.set_bytes("FILLER__25", b"and blinking for the second one.");
    record.set_bytes("FILLER__27", b"Black");
    record.set_bytes("FILLER__28", b"Blue");
    record.set_bytes("FILLER__29", b"Green");
    record.set_bytes("FILLER__30", b"Cyan");
    record.set_bytes("FILLER__31", b"Red");
    record.set_bytes("FILLER__32", b"Magenta");
    record.set_bytes("FILLER__33", b"Brown/Yellow");
    record.set_bytes("FILLER__34", b"White");
    record.set_bytes("FILLER__36", b"Black");
    record.set_bytes("FILLER__37", b"Blue");
    record.set_bytes("FILLER__38", b"Green");
    record.set_bytes("FILLER__39", b"Cyan");
    record.set_bytes("FILLER__40", b"Red");
    record.set_bytes("FILLER__41", b"Magenta");
    record.set_bytes("FILLER__42", b"Brown/Yellow");
    record.set_bytes("FILLER__43", b"White");
    { let now = cobol_runtime::chrono_shim::Local::now(); let wc = now.format("%d/%m/%y%H.%M.%S").to_string(); record.set_raw_string("WHEN-COMPILED", &wc); }
    cobol_runtime::screen_declare_screen_section();
    {
    let mut _sf: Vec<ScreenField> = Vec::new();
    _sf.push(ScreenField { line: SPos::Abs(1), col: SPos::Abs(1), content: "Enter \"y\" if the text below matches the colour of the background/text.".to_string(), width: 80, ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(2), col: SPos::Abs(1), content: "Note: the black text is on white background/the white background has black text".to_string(), width: 80, ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(3), col: SPos::Abs(1), content: "to make the text visible.".to_string(), width: 80, ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(1), content: "Black".to_string(), width: 8, fg_color: Some(0), bg_color: Some(7), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(10), content: "Blue".to_string(), width: 8, fg_color: Some(1), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(19), content: "Green".to_string(), width: 8, fg_color: Some(2), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(28), content: "Cyan".to_string(), width: 8, fg_color: Some(3), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(37), content: "Red".to_string(), width: 8, fg_color: Some(4), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(46), content: "Magenta".to_string(), width: 8, fg_color: Some(5), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(55), content: "Brown/Yellow".to_string(), width: 15, fg_color: Some(6), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(71), content: "White".to_string(), width: 8, fg_color: Some(7), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(1), content: "Black".to_string(), width: 8, fg_color: Some(7), bg_color: Some(0), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(10), content: "Blue".to_string(), width: 8, bg_color: Some(1), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(19), content: "Green".to_string(), width: 8, bg_color: Some(2), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(28), content: "Cyan".to_string(), width: 8, bg_color: Some(3), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(37), content: "Red".to_string(), width: 8, bg_color: Some(4), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(46), content: "Magenta".to_string(), width: 8, bg_color: Some(5), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(55), content: "Brown/Yellow".to_string(), width: 15, bg_color: Some(6), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(71), content: "White".to_string(), width: 8, fg_color: Some(0), bg_color: Some(7), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(7), col: SPos::Abs(1), content: "The following is the same as above, with \"extended\" attributes set;".to_string(), width: 80, ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(8), col: SPos::Abs(1), content: "this should have the same effect as otherwise highlighted for the first line".to_string(), width: 80, ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(9), col: SPos::Abs(1), content: "and blinking for the second one.".to_string(), width: 80, ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(1), content: "Black".to_string(), width: 8, fg_color: Some(8), bg_color: Some(0), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(10), content: "Blue".to_string(), width: 8, fg_color: Some(9), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(19), content: "Green".to_string(), width: 8, fg_color: Some(10), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(28), content: "Cyan".to_string(), width: 8, fg_color: Some(11), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(37), content: "Red".to_string(), width: 8, fg_color: Some(12), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(46), content: "Magenta".to_string(), width: 8, fg_color: Some(13), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(55), content: "Brown/Yellow".to_string(), width: 15, fg_color: Some(14), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(71), content: "White".to_string(), width: 8, fg_color: Some(15), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(1), content: "Black".to_string(), width: 8, fg_color: Some(15), bg_color: Some(8), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(10), content: "Blue".to_string(), width: 8, bg_color: Some(9), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(19), content: "Green".to_string(), width: 8, bg_color: Some(10), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(28), content: "Cyan".to_string(), width: 8, bg_color: Some(11), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(37), content: "Red".to_string(), width: 8, bg_color: Some(12), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(46), content: "Magenta".to_string(), width: 8, bg_color: Some(13), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(55), content: "Brown/Yellow".to_string(), width: 15, bg_color: Some(14), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(71), content: "White".to_string(), width: 8, fg_color: Some(8), bg_color: Some(15), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(13), col: SPos::Abs(1), content: "Y".to_string(), width: 1, ..Default::default() });
    screen_display(&_sf);
    }
    { use std::io::Write; let _ = std::io::stdout().flush(); }
    {
    let mut _sf: Vec<ScreenField> = Vec::new();
    _sf.push(ScreenField { line: SPos::Abs(1), col: SPos::Abs(1), content: "Enter \"y\" if the text below matches the colour of the background/text.".to_string(), width: 80, ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(2), col: SPos::Abs(1), content: "Note: the black text is on white background/the white background has black text".to_string(), width: 80, ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(3), col: SPos::Abs(1), content: "to make the text visible.".to_string(), width: 80, ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(1), content: "Black".to_string(), width: 8, fg_color: Some(0), bg_color: Some(7), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(10), content: "Blue".to_string(), width: 8, fg_color: Some(1), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(19), content: "Green".to_string(), width: 8, fg_color: Some(2), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(28), content: "Cyan".to_string(), width: 8, fg_color: Some(3), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(37), content: "Red".to_string(), width: 8, fg_color: Some(4), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(46), content: "Magenta".to_string(), width: 8, fg_color: Some(5), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(55), content: "Brown/Yellow".to_string(), width: 15, fg_color: Some(6), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(4), col: SPos::Abs(71), content: "White".to_string(), width: 8, fg_color: Some(7), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(1), content: "Black".to_string(), width: 8, fg_color: Some(7), bg_color: Some(0), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(10), content: "Blue".to_string(), width: 8, bg_color: Some(1), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(19), content: "Green".to_string(), width: 8, bg_color: Some(2), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(28), content: "Cyan".to_string(), width: 8, bg_color: Some(3), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(37), content: "Red".to_string(), width: 8, bg_color: Some(4), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(46), content: "Magenta".to_string(), width: 8, bg_color: Some(5), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(55), content: "Brown/Yellow".to_string(), width: 15, bg_color: Some(6), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(5), col: SPos::Abs(71), content: "White".to_string(), width: 8, fg_color: Some(0), bg_color: Some(7), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(7), col: SPos::Abs(1), content: "The following is the same as above, with \"extended\" attributes set;".to_string(), width: 80, ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(8), col: SPos::Abs(1), content: "this should have the same effect as otherwise highlighted for the first line".to_string(), width: 80, ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(9), col: SPos::Abs(1), content: "and blinking for the second one.".to_string(), width: 80, ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(1), content: "Black".to_string(), width: 8, fg_color: Some(8), bg_color: Some(0), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(10), content: "Blue".to_string(), width: 8, fg_color: Some(9), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(19), content: "Green".to_string(), width: 8, fg_color: Some(10), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(28), content: "Cyan".to_string(), width: 8, fg_color: Some(11), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(37), content: "Red".to_string(), width: 8, fg_color: Some(12), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(46), content: "Magenta".to_string(), width: 8, fg_color: Some(13), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(55), content: "Brown/Yellow".to_string(), width: 15, fg_color: Some(14), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(10), col: SPos::Abs(71), content: "White".to_string(), width: 8, fg_color: Some(15), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(1), content: "Black".to_string(), width: 8, fg_color: Some(15), bg_color: Some(8), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(10), content: "Blue".to_string(), width: 8, bg_color: Some(9), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(19), content: "Green".to_string(), width: 8, bg_color: Some(10), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(28), content: "Cyan".to_string(), width: 8, bg_color: Some(11), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(37), content: "Red".to_string(), width: 8, bg_color: Some(12), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(46), content: "Magenta".to_string(), width: 8, bg_color: Some(13), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(55), content: "Brown/Yellow".to_string(), width: 15, bg_color: Some(14), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(11), col: SPos::Abs(71), content: "White".to_string(), width: 8, fg_color: Some(8), bg_color: Some(15), ..Default::default() });
    _sf.push(ScreenField { line: SPos::Abs(13), col: SPos::Abs(1), content: "Y".to_string(), width: 1, is_input: true, ..Default::default() });
    screen_display(&_sf);
    }
    print!("\x1b[13;1H");
    print!("\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m\x1b[m");
    { use std::io::Write; let _ = std::io::stdout().flush(); }
    { let _scr_input_raw = cobol_runtime::accept_line_no_echo();
    let _scr_input: &str = &_scr_input_raw;
    record.set_bytes("SUCCESS-FLAG", _scr_input.as_bytes());
    }
    record.set_f64("COB-CRT-STATUS", 0.0);
    if ({ let _cond_v = record.get_display("SUCCESS-FLAG").trim_end_matches(' ').to_string(); _cond_v == "Y" || _cond_v == "y" } && f64_cmp(record.get_f64("COB-CRT-STATUS"), 0_f64) == 0) {
    { use std::io::Write; let _ = std::io::stdout().flush(); record.set_f64("RETURN-CODE", 0_f64); cobol_runtime::maybe_dump_record(record, "run_manual_screen_017_SCREEN_BACKGROUND-___FOREGROUND-COLOUR"); std::process::exit(0_f64 as i32); }
    } else {
    { use std::io::Write; let _ = std::io::stdout().flush(); record.set_f64("RETURN-CODE", 1_f64); cobol_runtime::maybe_dump_record(record, "run_manual_screen_017_SCREEN_BACKGROUND-___FOREGROUND-COLOUR"); std::process::exit(1_f64 as i32); }
    }
}

