// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.
#![allow(warnings)]

use cobol_runtime::field::*;
use std::collections::HashMap;

#[allow(unused_imports)]
use cobol_runtime::FixedString;
#[allow(unused_imports)]
use cobol_runtime::Decimal;
#[allow(unused_imports)]
use cobol_runtime::PackedDecimal;
#[allow(unused_imports)]
use cobol_runtime::FileStatus;
#[allow(unused_imports)]
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;
#[allow(unused_imports)]
use cobol_runtime::CobolNum;
#[allow(unused_imports)]
use cobol_runtime::CobolToF64;
#[allow(unused_imports)]
use cobol_runtime::CobolTrimmed;
#[allow(unused_imports)]
use cobol_runtime::DisplayWithWidth;
#[allow(unused_imports)]
use cobol_runtime::CobolInto;
#[allow(unused_imports)]
use cobol_runtime::coerce::Coerce;
#[allow(unused_imports)]
use cobol_runtime::screen::{ScreenField, SPos, screen_display};


pub struct ProgramState {
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
        }
    }
}

/// Paragraph: 000-MAIN
fn v2_p_000_main(record: &mut CobolRecord) {
    v2_p_100_open(record);
    { record.set_f64("I", 1_f64); while !(f64_cmp(record.get_f64("I"), 10_f64) > 0) {
    cobol_move(record, "I", "DISPLAY-A1-ZZ9");
    cobol_move(record, "DISPLAY-A1-ZZ9", "FCD-RECORD");
    record.set_f64("FCD-CURRENT-REC-LEN", 10_f64);
    if (f64_cmp(record.get_f64("I"), 3_f64) == 0 || f64_cmp(record.get_f64("I"), 5_f64) == 0) {
    { let _val = "Have a great day"; record.set_refmod("FCD-RECORD", 5i64 as usize, 20i64 as usize, _val.as_bytes()); }
    record.set_f64("FCD-CURRENT-REC-LEN", 25_f64);
    }
    if f64_cmp(record.get_f64("I"), 8_f64) == 0 {
    { let _val = "Enjoy the show"; record.set_refmod("FCD-RECORD", 5i64 as usize, 20i64 as usize, _val.as_bytes()); }
    record.set_f64("FCD-CURRENT-REC-LEN", 19_f64);
    }
    v2_p_300_write(record);
    if cobol_runtime::check_perform_exit() { break; }
    record.set_f64("I", record.get_f64("I") + 1_f64);
    } }
    v2_p_400_close(record);
    record.set_bytes("ACTION-CODE", &[0xFA, 0x00]);
    v2_p_800_call_extfh(record);
    { println!("{}{}{}", "Listing ".to_string(), record.get_display("WS-FCD-DDNAME"), ".".to_string()); use std::io::Write; std::io::stdout().flush().ok(); }
    { record.set_f64("I", 1_f64); while !(f64_cmp(record.get_f64("I"), 10_f64) > 0) {
    v2_p_350_read(record);
    { println!("{}{}{}{}", record.get_display("FCD-CURRENT-REC-LEN"), ": ".to_string(), record.get_refmod("FCD-RECORD", 1i64 as usize, record.get_i64("FCD-CURRENT-REC-LEN") as usize), " :".to_string()); use std::io::Write; std::io::stdout().flush().ok(); }
    if cobol_runtime::check_perform_exit() { break; }
    record.set_f64("I", record.get_f64("I") + 1_f64);
    } }
    v2_p_400_close(record);
    { use std::io::Write; let _ = std::io::stdout().flush();  { let _snapshot = cobol_runtime::get_exit_handlers(); for _handler in &_snapshot { if !cobol_runtime::is_exit_handler_registered(_handler) { continue; } match _handler.to_uppercase().as_str() { "000-MAIN" => { v2_p_000_main(record); } "100-OPEN" => { v2_p_100_open(record); } "300-WRITE" => { v2_p_300_write(record); } "350-READ" => { v2_p_350_read(record); } "400-CLOSE" => { v2_p_400_close(record); } "800-CALL-EXTFH" => { v2_p_800_call_extfh(record); } _ => {} } } } cobol_runtime::end_of_program_prompt(); cobol_runtime::maybe_dump_record(record, "run_file_087_EXTFH__auto-conversion_FCD2__-__FCD3_on_32bit"); std::process::exit(record.get_f64("RETURN-CODE") as i32); }
}

/// Paragraph: 100-OPEN
fn v2_p_100_open(record: &mut CobolRecord) {
    record.set_bytes("WS-FCD-DDNAME", b"TESTOUT");
    { let len = record.length_of("FCD-MAP") as f64; record.set_f64("WS-FCD-SIZE", len); }
    { println!("{}{}{}", "FCD SIZE ".to_string(), record.get_display("WS-FCD-SIZE"), ".".to_string()); use std::io::Write; std::io::stdout().flush().ok(); }
    { println!("{}{}{}", "Writing ".to_string(), record.get_display("WS-FCD-DDNAME"), ".".to_string()); use std::io::Write; std::io::stdout().flush().ok(); }
    if { let _l = record.get_display_unsigned("WS-FCD-PTR"); let _r = "0000000000000000".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) == format!("{:<w$}", _r, w = _w) } {
    record.allocate_based("WS-FCD-SIZE");
    record.set_address_of("FCD-MAP", { let _pv = record.get_i64("WS-FCD-PTR"); if _pv > 0 { (_pv - 1) as usize } else if _pv < 0 { usize::MAX } else { usize::MAX } });
    record.fill_field("FCD-MAP", 0x00);
    cobol_move(record, "WS-FCD-SIZE", "FCD-LENGTH");
    record.set_f64("FCD-VERSION", 0_f64);
    record.set_bytes("FCD-FILE-STATUS", b"00");
    record.set_f64("FCD-ACCESS-MODE", 128_f64);
    record.set_f64("FCD-OPEN-MODE", 128_f64);
    record.set_f64("FCD-OTHER-FLAGS", 16_f64);
    record.set_f64("FCD-HANDLE", 0.0_f64);
    record.set_f64("FCD-NAME-LENGTH", 8_f64);
    record.set_i64("FCD-FILENAME-ADDRESS", record.address_of_ptr("WS-FCD-DDNAME") as i64);
    record.set_f64("FCD-KEY-DEF-ADDRESS", 0.0_f64);
    record.set_f64("FCD-LOCKTYPES", 64_f64);
    } else {
    record.set_address_of("FCD-MAP", { let _pv = record.get_i64("WS-FCD-PTR"); if _pv > 0 { (_pv - 1) as usize } else if _pv < 0 { usize::MAX } else { usize::MAX } });
    if f64_cmp(record.get_f64("FCD-OPEN-MODE"), 128_f64) != 0 {
    { println!("{}", "ERRROR - FILE ALREADY OPEN".to_string()); use std::io::Write; std::io::stdout().flush().ok(); }
    { use std::io::Write; let _ = std::io::stdout().flush();  { let _snapshot = cobol_runtime::get_exit_handlers(); for _handler in &_snapshot { if !cobol_runtime::is_exit_handler_registered(_handler) { continue; } match _handler.to_uppercase().as_str() { "000-MAIN" => { v2_p_000_main(record); } "100-OPEN" => { v2_p_100_open(record); } "300-WRITE" => { v2_p_300_write(record); } "350-READ" => { v2_p_350_read(record); } "400-CLOSE" => { v2_p_400_close(record); } "800-CALL-EXTFH" => { v2_p_800_call_extfh(record); } _ => {} } } } cobol_runtime::end_of_program_prompt(); cobol_runtime::maybe_dump_record(record, "run_file_087_EXTFH__auto-conversion_FCD2__-__FCD3_on_32bit"); std::process::exit(record.get_f64("RETURN-CODE") as i32); }
    }
    }
    record.set_f64("FCD-ORGANIZATION", 0_f64);
    record.set_f64("FCD-RECORDING-MODE", 0_f64);
    record.set_f64("FCD-MIN-REC-LENGTH", 10_f64);
    record.set_f64("FCD-MAX-REC-LENGTH", 50_f64);
    record.set_i64("FCD-RECORD-ADDRESS", record.address_of_ptr("FCD-RECORD") as i64);
    record.set_f64("FCD-FILENAME-ADDRESS", 0.0_f64);
    record.set_bytes("ACTION-CODE", &[0xFA, 0x01]);
    v2_p_800_call_extfh(record);
    record.set_i64("FCD-RECORD-ADDRESS", record.address_of_ptr("FCD-RECORD") as i64);
    record.set_i64("FCD-FILENAME-ADDRESS", record.address_of_ptr("WS-FCD-DDNAME") as i64);
    record.set_bytes("ACTION-CODE", &[0xFA, 0x01]);
    v2_p_800_call_extfh(record);
}

/// Paragraph: 300-WRITE
fn v2_p_300_write(record: &mut CobolRecord) {
    record.set_bytes("ACTION-CODE", &[0xFA, 0xF3]);
    v2_p_800_call_extfh(record);
}

/// Paragraph: 350-READ
fn v2_p_350_read(record: &mut CobolRecord) {
    record.set_bytes("ACTION-CODE", &[0xFA, 0xF5]);
    v2_p_800_call_extfh(record);
}

/// Paragraph: 400-CLOSE
fn v2_p_400_close(record: &mut CobolRecord) {
    record.set_bytes("ACTION-CODE", &[0xFA, 0x80]);
    v2_p_800_call_extfh(record);
}

/// Paragraph: 800-CALL-EXTFH
fn v2_p_800_call_extfh(record: &mut CobolRecord) {
    record.set_bytes("FCD-FILE-STATUS", b"00");
    cobol_runtime::extfh::call(record, "ACTION-CODE", "FCD-MAP");
    if { let _l = record.get_display("FCD-STATUS-KEY-1"); let _r = "0".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) != format!("{:<w$}", _r, w = _w) } {
    if { let _l = record.get_display("FCD-STATUS-KEY-1"); let _r = "9".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) == format!("{:<w$}", _r, w = _w) } {
    if f64_cmp(record.get_f64("FCD-BINARY"), 161_f64) == 0 {
    { println!("{}{}", "EXTFH Status: 9/".to_string(), record.get_display("FCD-BINARY")); use std::io::Write; std::io::stdout().flush().ok(); }
    { println!("{}", "FCD2 is not accepted!".to_string()); use std::io::Write; std::io::stdout().flush().ok(); }
    { use std::io::Write; let _ = std::io::stdout().flush();  { let _snapshot = cobol_runtime::get_exit_handlers(); for _handler in &_snapshot { if !cobol_runtime::is_exit_handler_registered(_handler) { continue; } match _handler.to_uppercase().as_str() { "000-MAIN" => { v2_p_000_main(record); } "100-OPEN" => { v2_p_100_open(record); } "300-WRITE" => { v2_p_300_write(record); } "350-READ" => { v2_p_350_read(record); } "400-CLOSE" => { v2_p_400_close(record); } "800-CALL-EXTFH" => { v2_p_800_call_extfh(record); } _ => {} } } } cobol_runtime::end_of_program_prompt(); cobol_runtime::maybe_dump_record(record, "run_file_087_EXTFH__auto-conversion_FCD2__-__FCD3_on_32bit"); std::process::exit(record.get_f64("RETURN-CODE") as i32); }
    }
    { println!("{}{}", "EXTFH Status: 9/".to_string(), record.get_display("FCD-BINARY")); use std::io::Write; std::io::stdout().flush().ok(); }
    if f64_cmp(record.get_f64("FCD-BINARY"), 141_f64) == 0 {
    { println!("{}", "FCD2 is missing value(s)!".to_string()); use std::io::Write; std::io::stdout().flush().ok(); }
    }
    } else {
    { println!("{}{}", "EXTFH Status: ".to_string(), record.get_display("FCD-FILE-STATUS")); use std::io::Write; std::io::stdout().flush().ok(); }
    }
    }
    if ({ let _l = record.get_display("FCD-STATUS-KEY-1"); let _r = "9".to_string(); let _w = _l.len().max(_r.len()); format!("{:<w$}", _l, w = _w) == format!("{:<w$}", _r, w = _w) } && f64_cmp(record.get_f64("FCD-BINARY"), 199_f64) == 0) {
    record.set_bytes("FCD-FILE-STATUS", b"10");
    }
}

fn main() {
    let mut record = CobolRecord::new(1366, vec![
        FieldDescriptor { name: "I".into(), offset: 0, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "WS-FCD-DDNAME".into(), offset: 2, size: 10, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 10, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "WS-FCD-PTR".into(), offset: 12, size: 8, field_type: FieldType::Binary64, pic_scale: 0, pic_digits: 8, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: true, pic_clause_digits: 0 },
        FieldDescriptor { name: "WS-FCD-SIZE".into(), offset: 20, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 4 },
        FieldDescriptor { name: "WS-FCD-FLAGS".into(), offset: 22, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 4 },
        FieldDescriptor { name: "DISPLAY-BYTE".into(), offset: 24, size: 3, field_type: FieldType::Group, pic_scale: 0, pic_digits: 0, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "DISPLAY-XXX".into(), offset: 24, size: 3, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "DISPLAY-ZZ9".into(), offset: 24, size: 3, field_type: FieldType::EditedNumeric("ZZ9".into()), pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "ACTION-CODE".into(), offset: 27, size: 2, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "DISPLAY-A1-XXX".into(), offset: 29, size: 3, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "DISPLAY-A1-ZZ9".into(), offset: 29, size: 3, field_type: FieldType::EditedNumeric("ZZ9".into()), pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "DISPLAY-A2-XXX".into(), offset: 32, size: 3, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "DISPLAY-A2-ZZ9".into(), offset: 32, size: 3, field_type: FieldType::EditedNumeric("ZZ9".into()), pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-FILENAME".into(), offset: 35, size: 80, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 80, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-RECORD".into(), offset: 115, size: 512, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 0, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-MAP".into(), offset: 627, size: 120, field_type: FieldType::Group, pic_scale: 0, pic_digits: 0, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-FILE-STATUS".into(), offset: 627, size: 2, field_type: FieldType::Group, pic_scale: 0, pic_digits: 0, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-STATUS-KEY-1".into(), offset: 627, size: 1, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-STATUS-KEY-2".into(), offset: 628, size: 1, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-BINARY".into(), offset: 628, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-LENGTH".into(), offset: 629, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-VERSION".into(), offset: 631, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-ORGANIZATION".into(), offset: 632, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-ACCESS-MODE".into(), offset: 633, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-OPEN-MODE".into(), offset: 634, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER".into(), offset: 635, size: 2, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-BLOCK-SIZE".into(), offset: 637, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-NAME-LENGTH".into(), offset: 638, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-RELADDR-BIG".into(), offset: 640, size: 8, field_type: FieldType::Binary64, pic_scale: 0, pic_digits: 20, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__2".into(), offset: 648, size: 1, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-TRANS-LOG".into(), offset: 649, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__3".into(), offset: 650, size: 1, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 1, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-LOCK-MODE".into(), offset: 651, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-OTHER-FLAGS".into(), offset: 652, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__4".into(), offset: 653, size: 2, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-HANDLE".into(), offset: 655, size: 8, field_type: FieldType::Binary64, pic_scale: 0, pic_digits: 8, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: true, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-PERCENT".into(), offset: 663, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-REC-COUNT-SET".into(), offset: 663, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-STATUS-TYPE".into(), offset: 664, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-FILE-FORMAT".into(), offset: 665, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__5".into(), offset: 666, size: 3, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-MAX-REC-LENGTH".into(), offset: 669, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__6".into(), offset: 671, size: 2, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-MVS-FLAGS".into(), offset: 673, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-RELATIVE-KEY".into(), offset: 674, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-RECORDING-MODE".into(), offset: 678, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-CURRENT-REC-LEN".into(), offset: 679, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-MIN-REC-LENGTH".into(), offset: 681, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-KEY-ID".into(), offset: 683, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-LINE-COUNT".into(), offset: 683, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FILLER__7".into(), offset: 683, size: 2, field_type: FieldType::Group, pic_scale: 0, pic_digits: 0, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-USE-FILES".into(), offset: 683, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-GIVE-FILES".into(), offset: 684, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-KEY-LENGTH".into(), offset: 685, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-RECORD-ADDRESS".into(), offset: 687, size: 8, field_type: FieldType::Binary64, pic_scale: 0, pic_digits: 8, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: true, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-FILENAME-ADDRESS".into(), offset: 695, size: 8, field_type: FieldType::Binary64, pic_scale: 0, pic_digits: 8, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: true, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-KEY-DEF-ADDRESS".into(), offset: 703, size: 8, field_type: FieldType::Binary64, pic_scale: 0, pic_digits: 8, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: true, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-COL-SEQ-ADDRESS".into(), offset: 711, size: 8, field_type: FieldType::Binary64, pic_scale: 0, pic_digits: 8, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: true, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-RELADDR-OFFSET".into(), offset: 719, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-RELADDR".into(), offset: 719, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-FILDEF-ADDRESS".into(), offset: 719, size: 8, field_type: FieldType::Binary64, pic_scale: 0, pic_digits: 8, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: true, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-NLS-ID".into(), offset: 723, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-DATA-COMPRESS".into(), offset: 725, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-SESSION-ID".into(), offset: 726, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-FS-FILE-ID".into(), offset: 730, size: 2, field_type: FieldType::Binary16, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-MAX-REL-KEY".into(), offset: 732, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-FLAGS-1".into(), offset: 736, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-BLOCKING".into(), offset: 737, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-ADDITIONAL-STATUS".into(), offset: 737, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-LOCKTYPES".into(), offset: 738, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-FS-FLAGS".into(), offset: 739, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-CONFIG-FLAGS".into(), offset: 740, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-MISC-FLAGS".into(), offset: 741, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-CONFIG-FLAGS2".into(), offset: 742, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-IDXCACHE-SIZE".into(), offset: 743, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-IDXCACHE-BUFFS".into(), offset: 744, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 2, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-INTERNAL-FLAGS-1".into(), offset: 745, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "FCD-INTERNAL-FLAGS-2".into(), offset: 746, size: 1, field_type: FieldType::Binary8, pic_scale: 0, pic_digits: 3, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "TALLY".into(), offset: 747, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "RETURN-CODE".into(), offset: 751, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SORT-RETURN".into(), offset: 755, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "NUMBER-OF-CALL-PARAMETERS".into(), offset: 759, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LINAGE-COUNTER".into(), offset: 763, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LINE-COUNTER".into(), offset: 767, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "PAGE-COUNTER".into(), offset: 771, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "SYSTEM-OFFSET".into(), offset: 775, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-CODE".into(), offset: 779, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "JSON-CODE".into(), offset: 783, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 9, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "LIN".into(), offset: 787, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COL".into(), offset: 791, size: 4, field_type: FieldType::Binary32, pic_scale: 0, pic_digits: 5, is_signed: true, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COB-CRT-STATUS".into(), offset: 795, size: 4, field_type: FieldType::NumericDisplay, pic_scale: 0, pic_digits: 4, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "DEBUG-ITEM".into(), offset: 799, size: 86, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 86, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "COB-CURRENT-DATE".into(), offset: 885, size: 26, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 26, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-STATUS".into(), offset: 911, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-FILE".into(), offset: 942, size: 30, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 30, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-LOCATION".into(), offset: 972, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "EXCEPTION-STATEMENT".into(), offset: 1003, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "MODULE-CALLER-ID".into(), offset: 1034, size: 31, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 31, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "WHEN-COMPILED".into(), offset: 1065, size: 16, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 16, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-EVENT".into(), offset: 1081, size: 30, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 30, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },
        FieldDescriptor { name: "XML-TEXT".into(), offset: 1111, size: 255, field_type: FieldType::AlphaNumeric, pic_scale: 0, pic_digits: 255, is_signed: false, justified_right: false, blank_when_zero: false, p_factor: 0, sign_leading: false, sign_separate: false, is_pointer: false, pic_clause_digits: 0 },]);
    let record = &mut record;
    record.fill_field("WS-FCD-DDNAME", 0x20);
    record.set_i64("WS-FCD-PTR", 0);
    record.set_f64("WS-FCD-SIZE", 0_f64);
    record.set_f64("WS-FCD-FLAGS", 0_f64);
    record.set_bytes("FCD-FILENAME", b"test.out");
    record.fill_field("FCD-RECORD", 0x20);
    { let now = cobol_runtime::chrono_shim::Local::now(); let wc = now.format("%d/%m/%y%H.%M.%S").to_string(); record.set_raw_string("WHEN-COMPILED", &wc); }
    v2_p_000_main(record);
    v2_p_100_open(record);
    v2_p_300_write(record);
    v2_p_350_read(record);
    v2_p_400_close(record);
    v2_p_800_call_extfh(record);
}

