// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct TestRec {
    /// TESTKEY-P1
    pub testkey_p1: FixedString<4>,
    /// TESTKEY-P2
    pub testkey_p2: u32,
    /// TESTDATA
    pub testdata: FixedString<4>,
    /// TESTKEY-P3
    pub testkey_p3: FixedString<4>,
    /// TESTKEY-P4
    pub testkey_p4: FixedString<4>,
    /// TESTKEY-P5
    pub testkey_p5: FixedString<4>,
}
impl std::fmt::Display for TestRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}", self.testkey_p1, self.testkey_p2, self.testdata, self.testkey_p3, self.testkey_p4, self.testkey_p5)
    }
}
impl From<&str> for TestRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TestRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl TestRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TestFile {
    /// TEST-REC
    pub test_rec: TestRec,
}
impl std::fmt::Display for TestFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.test_rec)
    }
}
impl From<&str> for TestFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TestFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl TestFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// FD group: TEST-REC
    pub test_rec: FixedString<24>,
    /// FD: TESTKEY-P1
    pub testkey_p1: FixedString<4>,
    /// FD: TESTKEY-P2
    pub testkey_p2: u32,
    /// FD: TESTDATA
    pub testdata: FixedString<4>,
    /// FD: TESTKEY-P3
    pub testkey_p3: FixedString<4>,
    /// FD: TESTKEY-P4
    pub testkey_p4: FixedString<4>,
    /// FD: TESTKEY-P5
    pub testkey_p5: FixedString<4>,
    /// File status for TEST-FILE
    pub _fs_test_file: FileStatus,
    /// File handle for TEST-FILE
    pub _fh_test_file: CobolFile,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            test_rec: Default::default(),
            testkey_p1: Default::default(),
            testkey_p2: Default::default(),
            testdata: Default::default(),
            testkey_p3: Default::default(),
            testkey_p4: Default::default(),
            testkey_p5: Default::default(),
            _fs_test_file: FileStatus::Success,
            _fh_test_file: CobolFile::Closed,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// RUN
fn p_run(state: &mut ProgramState) {
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT TEST-FILE
fn test_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("TEST_FILE").unwrap_or("test_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_test_file = handle; state._fs_test_file = FileStatus::Success; }
        Err(_) => { state._fs_test_file = FileStatus::Error("35".to_string()); }
    }
}

/// OPEN OUTPUT TEST-FILE
fn test_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("TEST_FILE").unwrap_or("test_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_test_file = handle; state._fs_test_file = FileStatus::Success; }
        Err(_) => { state._fs_test_file = FileStatus::Error("35".to_string()); }
    }
}

/// READ TEST-FILE
fn test_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_test_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(24);
            if _len > 0 { let _end = _len.min(0+4); state.testkey_p1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 4 { let _end = _len.min(4+4); let _s = String::from_utf8_lossy(&_bytes[4.._end]).trim().to_string(); state.testkey_p2 = _s.parse().unwrap_or_default(); }
            if _len > 8 { let _end = _len.min(8+4); state.testdata = FixedString::from(String::from_utf8_lossy(&_bytes[8.._end])); }
            if _len > 12 { let _end = _len.min(12+4); state.testkey_p3 = FixedString::from(String::from_utf8_lossy(&_bytes[12.._end])); }
            if _len > 16 { let _end = _len.min(16+4); state.testkey_p4 = FixedString::from(String::from_utf8_lossy(&_bytes[16.._end])); }
            if _len > 20 { let _end = _len.min(20+4); state.testkey_p5 = FixedString::from(String::from_utf8_lossy(&_bytes[20.._end])); }
            state._fs_test_file = FileStatus::Success;
        }
        Err(FileStatus::AtEnd) => {
            state._fs_test_file = FileStatus::AtEnd;
        }
        Err(e) => {
            state._fs_test_file = e.clone();
        }
    }
    Ok(())
}

/// WRITE to TEST-FILE
fn test_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 24];
    { let _src = state.testkey_p1.as_bytes(); let _end = (0+4).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    { let _s = format!("{:>width$}", state.testkey_p2, width = 4); let _b = _s.as_bytes(); let _cl = _b.len().min(4); _buf[4..4+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _src = state.testdata.as_bytes(); let _end = (8+4).min(_buf.len()); let _cl = _src.len().min(_end-8); _buf[8..8+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.testkey_p3.as_bytes(); let _end = (12+4).min(_buf.len()); let _cl = _src.len().min(_end-12); _buf[12..12+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.testkey_p4.as_bytes(); let _end = (16+4).min(_buf.len()); let _cl = _src.len().min(_end-16); _buf[16..16+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.testkey_p5.as_bytes(); let _end = (20+4).min(_buf.len()); let _cl = _src.len().min(_end-20); _buf[20..20+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_test_file.write_record(&_buf) {
        Ok(()) => state._fs_test_file = FileStatus::Success,
        Err(e) => state._fs_test_file = e,
    }
}

/// CLOSE TEST-FILE
fn test_file_close(state: &mut ProgramState) {
    match state._fh_test_file.close() {
        Ok(()) => state._fs_test_file = FileStatus::Success,
        Err(e) => state._fs_test_file = e,
    }
}

/// OPEN I-O TEST-FILE
fn test_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("TEST_FILE").unwrap_or("test_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_test_file = handle; state._fs_test_file = FileStatus::Success; }
        Err(_) => { state._fs_test_file = FileStatus::Error("35".to_string()); }
    }
}

/// OPEN EXTEND TEST-FILE
fn test_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("TEST_FILE").unwrap_or("test_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_test_file = handle; state._fs_test_file = FileStatus::Success; }
        Err(_) => { state._fs_test_file = FileStatus::Error("35".to_string()); }
    }
}

fn main() {
    let mut state = ProgramState::default();
    p_run(&mut state);
}

