// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataCollection {
    /// DATA-ITEMS-A
    pub data_items_a: DataItemsA,
    /// VOLATILE
    pub volatile: Volatile,
    /// DATA-ITEMS-B
    pub data_items_b: DataItemsB,
    /// DATA-ITEMS-C
    pub data_items_c: DataItemsC,
}
impl std::fmt::Display for DataCollection {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.data_items_a, self.volatile, self.data_items_b, self.data_items_c)
    }
}
impl From<&str> for DataCollection {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataCollection {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataCollection {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataItemsA {
    /// DATA-A1
    pub data_a1: i32,
    /// DATA-A2
    pub data_a2: i32,
}
impl std::fmt::Display for DataItemsA {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.data_a1, self.data_a2)
    }
}
impl From<&str> for DataItemsA {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataItemsA {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataItemsA {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Volatile {
    /// DATA-FILLER
    pub data_filler: i32,
}
impl std::fmt::Display for Volatile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.data_filler)
    }
}
impl From<&str> for Volatile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Volatile {
    fn from(_s: String) -> Self { Self::default() }
}
impl Volatile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataItemsB {
    /// DATA-B1
    pub data_b1: i32,
    /// DATA-B2
    pub data_b2: i32,
}
impl std::fmt::Display for DataItemsB {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.data_b1, self.data_b2)
    }
}
impl From<&str> for DataItemsB {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataItemsB {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataItemsB {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataItemsC {
    /// DATA-C1
    pub data_c1: i32,
    /// DATA-C2
    pub data_c2: i32,
}
impl std::fmt::Display for DataItemsC {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.data_c1, self.data_c2)
    }
}
impl From<&str> for DataItemsC {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataItemsC {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataItemsC {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Xmyrec {
    /// XFLD1
    pub xfld1: u32,
}
impl std::fmt::Display for Xmyrec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.xfld1)
    }
}
impl From<&str> for Xmyrec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Xmyrec {
    fn from(_s: String) -> Self { Self::default() }
}
impl Xmyrec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// DATA-COLLECTION
    pub data_collection: DataCollection,
    /// DATA-ITEMS-A
    pub data_items_a: DataItemsA,
    /// DATA-A1
    pub data_a1: i32,
    /// DATA-A2
    pub data_a2: i32,
    /// VOLATILE
    pub volatile: Volatile,
    /// DATA-FILLER
    pub data_filler: i32,
    /// DATA-ITEMS-B
    pub data_items_b: DataItemsB,
    /// DATA-B1
    pub data_b1: i32,
    /// DATA-B2
    pub data_b2: i32,
    /// DATA-ITEMS-C
    pub data_items_c: DataItemsC,
    /// DATA-C1
    pub data_c1: i32,
    /// DATA-C2
    pub data_c2: i32,
    /// STEP
    pub step: u32,
    /// LINKAGE: XMYREC
    pub xmyrec: Xmyrec,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            data_collection: Default::default(),
            data_items_a: Default::default(),
            data_a1: Default::default(),
            data_a2: Default::default(),
            volatile: Default::default(),
            data_filler: Default::default(),
            data_items_b: Default::default(),
            data_b1: Default::default(),
            data_b2: Default::default(),
            data_items_c: Default::default(),
            data_c1: Default::default(),
            data_c2: Default::default(),
            step: 0u32,
            xmyrec: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// DATA-ITEMS-C
fn p_data_items_c(state: &mut ProgramState) {
    { std::process::exit(0); }
}

fn main() {
    let mut state = ProgramState::default();
    p_data_items_c(&mut state);
}

