// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone)]
pub struct ProgramState {
    /// LINKAGE: FUNC-IN
    pub func_in: FixedString<15>,
    /// LINKAGE: FUNC-SUB
    pub func_sub: FixedString<1>,
    /// LINKAGE: FUNC-OUT
    pub func_out: FixedString<15>,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            func_in: Default::default(),
            func_sub: Default::default(),
            func_out: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// FUNC-OUT
fn p_func_out(state: &mut ProgramState) {
    state.func_out = FixedString::copy_from(&state.func_in);
    {
        inspect_replace_all(state.func_out.as_bytes_mut(), b"%", state.func_sub.as_bytes(), None, None);
    }
}

/// SUBSTITUTE
fn p_substitute(state: &mut ProgramState) {
}

/// DIVISION
fn p_division(state: &mut ProgramState) {
}

/// PROGRAM-ID
fn p_program_id(state: &mut ProgramState) {
}

/// PROG
fn p_prog(state: &mut ProgramState) {
}

/// DIVISION
fn p_division_2(state: &mut ProgramState) {
}

/// SECTION
fn p_section(state: &mut ProgramState) {
}

/// REPOSITORY
fn p_repository(state: &mut ProgramState) {
}

/// SUBSTITUTE
fn p_substitute_2(state: &mut ProgramState) {
}

/// DIVISION
fn p_division_3(state: &mut ProgramState) {
    println!("{}", " % C%O%B%O%L % ");
    println!("{}", " % C%O%B%O%L % ");
}

/// PROG
fn p_prog_2(state: &mut ProgramState) {
}

fn main() {
    let mut state = ProgramState::default();
    p_func_out(&mut state);
}

