// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct TestRec {
    /// TEST-P1
    pub test_p1: FixedString<4>,
    /// TEST-P2
    pub test_p2: i32,
}
impl std::fmt::Display for TestRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.test_p1, self.test_p2)
    }
}
impl From<&str> for TestRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TestRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl TestRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TestFile {
    /// TEST-REC
    pub test_rec: TestRec,
}
impl std::fmt::Display for TestFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.test_rec)
    }
}
impl From<&str> for TestFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TestFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl TestFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// FD group: TEST-REC
    pub test_rec: FixedString<8>,
    /// FD: TEST-P1
    pub test_p1: FixedString<4>,
    /// FD: TEST-P2
    pub test_p2: i32,
    /// SOME-REC
    pub some_rec: FixedString<4>,
    /// File status for TEST-FILE
    pub _fs_test_file: FileStatus,
    /// File handle for TEST-FILE
    pub _fh_test_file: CobolFile,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            test_rec: Default::default(),
            test_p1: Default::default(),
            test_p2: Default::default(),
            some_rec: Default::default(),
            _fs_test_file: FileStatus::Success,
            _fh_test_file: CobolFile::Closed,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// TEST-FILE
fn p_test_file(state: &mut ProgramState) {
    some_val_write(state);
    some_rec_write(state);
    test_rec_write(state);
    test_rec_write(state);
    test_file_write(state);
    file_write(state);
}

/// TEST-REC
fn p_test_rec(state: &mut ProgramState) {
    file_write(state);
}

/// TEST-FILE
fn p_test_file_2(state: &mut ProgramState) {
    file_write(state);
}

/// TEST-REC
fn p_test_rec_2(state: &mut ProgramState) {
    file_write(state);
}

/// SOME-REC
fn p_some_rec(state: &mut ProgramState) {
    // REWRITE SOME-VAL
    // REWRITE SOME-REC
    // REWRITE TEST-REC
    // AUTO-FIX SKIP: array length 8≠4: state.test_rec = state.some_rec;  // REWRITE FROM
    // REWRITE TEST-FILE
    // REWRITE FILE
}

/// TEST-REC
fn p_test_rec_3(state: &mut ProgramState) {
    // REWRITE FILE
}

/// TEST-FILE
fn p_test_file_3(state: &mut ProgramState) {
    // REWRITE FILE
}

/// TEST-REC
fn p_test_rec_4(state: &mut ProgramState) {
    // REWRITE FILE
}

/// SOME-REC
fn p_some_rec_2(state: &mut ProgramState) {
    test_file_close(state);
    { let _ = state._fh_test_file.close();
        std::process::exit(0); }
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT TEST-FILE
fn test_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("TEST_FILE").unwrap_or("test_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_test_file = handle; state._fs_test_file = FileStatus::Success; }
        Err(_) => { state._fs_test_file = FileStatus::Error("35".to_string()); }
    }
}

/// OPEN OUTPUT TEST-FILE
fn test_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("TEST_FILE").unwrap_or("test_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_test_file = handle; state._fs_test_file = FileStatus::Success; }
        Err(_) => { state._fs_test_file = FileStatus::Error("35".to_string()); }
    }
}

/// READ TEST-FILE
fn test_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_test_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(6);
            if _len > 0 { let _end = _len.min(0+4); state.test_p1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 4 { let _end = _len.min(4+2); let _s = String::from_utf8_lossy(&_bytes[4.._end]).trim().to_string(); state.test_p2 = _s.parse().unwrap_or_default(); }
            state._fs_test_file = FileStatus::Success;
        }
        Err(FileStatus::AtEnd) => {
            state._fs_test_file = FileStatus::AtEnd;
        }
        Err(e) => {
            state._fs_test_file = e.clone();
        }
    }
    Ok(())
}

/// WRITE to TEST-FILE
fn test_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 6];
    { let _src = state.test_p1.as_bytes(); let _end = (0+4).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    { let _s = format!("{:>width$}", state.test_p2, width = 2); let _b = _s.as_bytes(); let _cl = _b.len().min(2); _buf[4..4+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    match state._fh_test_file.write_record(&_buf) {
        Ok(()) => state._fs_test_file = FileStatus::Success,
        Err(e) => state._fs_test_file = e,
    }
}

/// CLOSE TEST-FILE
fn test_file_close(state: &mut ProgramState) {
    match state._fh_test_file.close() {
        Ok(()) => state._fs_test_file = FileStatus::Success,
        Err(e) => state._fs_test_file = e,
    }
}

/// OPEN I-O TEST-FILE
fn test_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("TEST_FILE").unwrap_or("test_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_test_file = handle; state._fs_test_file = FileStatus::Success; }
        Err(_) => { state._fs_test_file = FileStatus::Error("35".to_string()); }
    }
}

/// OPEN EXTEND TEST-FILE
fn test_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("TEST_FILE").unwrap_or("test_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_test_file = handle; state._fs_test_file = FileStatus::Success; }
        Err(_) => { state._fs_test_file = FileStatus::Error("35".to_string()); }
    }
}

/// WRITE SOME-VAL
fn some_val_write(state: &mut ProgramState) {
    // Write SOME-VAL via some_val_write (byte buffer)
    some_val_write(state);
}

/// WRITE SOME-REC
fn some_rec_write(state: &mut ProgramState) {
    // Write SOME-REC via some_rec_write (byte buffer)
    some_rec_write(state);
}

/// WRITE TEST-REC
fn test_rec_write(state: &mut ProgramState) {
    // Write TEST-REC via test_file_write (byte buffer)
    test_file_write(state);
}

/// WRITE FILE
fn file_write(state: &mut ProgramState) {
    // Write FILE via file_write (byte buffer)
    file_write(state);
}

/// WRITE TEST-FILE
fn test_file_write_dup2(state: &mut ProgramState) {
    // Write TEST-FILE via test_file_write (byte buffer)
    test_file_write(state);
}

fn main() {
    let mut state = ProgramState::default();
    p_test_file(&mut state);
}

