// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct F {
    /// HS
    pub hs: FixedString<2>,
}
impl std::fmt::Display for F {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.hs)
    }
}
impl From<&str> for F {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for F {
    fn from(_s: String) -> Self { Self::default() }
}
impl F {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct G {
    /// G-REC
    pub g_rec: FixedString<1>,
}
impl std::fmt::Display for G {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.g_rec)
    }
}
impl From<&str> for G {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for G {
    fn from(_s: String) -> Self { Self::default() }
}
impl G {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct H {
    /// H-REC
    pub h_rec: FixedString<1>,
}
impl std::fmt::Display for H {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.h_rec)
    }
}
impl From<&str> for H {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for H {
    fn from(_s: String) -> Self { Self::default() }
}
impl H {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct J {
    /// J-REC
    pub j_rec: FixedString<1>,
}
impl std::fmt::Display for J {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.j_rec)
    }
}
impl From<&str> for J {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for J {
    fn from(_s: String) -> Self { Self::default() }
}
impl J {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct K {
    /// K-REC
    pub k_rec: FixedString<1>,
}
impl std::fmt::Display for K {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.k_rec)
    }
}
impl From<&str> for K {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for K {
    fn from(_s: String) -> Self { Self::default() }
}
impl K {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct L {
    /// L-REC
    pub l_rec: FixedString<1>,
}
impl std::fmt::Display for L {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.l_rec)
    }
}
impl From<&str> for L {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for L {
    fn from(_s: String) -> Self { Self::default() }
}
impl L {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct M {
    /// M-REC
    pub m_rec: FixedString<1>,
}
impl std::fmt::Display for M {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.m_rec)
    }
}
impl From<&str> for M {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for M {
    fn from(_s: String) -> Self { Self::default() }
}
impl M {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct N {
    /// N-REC
    pub n_rec: FixedString<1>,
}
impl std::fmt::Display for N {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.n_rec)
    }
}
impl From<&str> for N {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for N {
    fn from(_s: String) -> Self { Self::default() }
}
impl N {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct O {
    /// O-REC
    pub o_rec: FixedString<1>,
}
impl std::fmt::Display for O {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.o_rec)
    }
}
impl From<&str> for O {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for O {
    fn from(_s: String) -> Self { Self::default() }
}
impl O {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct P {
    /// P-REC
    pub p_rec: FixedString<1>,
}
impl std::fmt::Display for P {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.p_rec)
    }
}
impl From<&str> for P {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for P {
    fn from(_s: String) -> Self { Self::default() }
}
impl P {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Q {
    /// Q-REC
    pub q_rec: FixedString<1>,
}
impl std::fmt::Display for Q {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.q_rec)
    }
}
impl From<&str> for Q {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Q {
    fn from(_s: String) -> Self { Self::default() }
}
impl Q {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct R {
    /// R-REC
    pub r_rec: FixedString<1>,
}
impl std::fmt::Display for R {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.r_rec)
    }
}
impl From<&str> for R {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for R {
    fn from(_s: String) -> Self { Self::default() }
}
impl R {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct X {
    /// Y
    pub y: u32,
    /// Z
    pub z: [FixedString<2>; 1],
    /// OS
    pub os: FixedString<2>,
    /// Z2
    pub z2: [FixedString<2>; 1],
}
impl std::fmt::Display for X {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.y, self.os)
    }
}
impl From<&str> for X {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for X {
    fn from(_s: String) -> Self { Self::default() }
}
impl X {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// FD: HS
    pub hs: FixedString<2>,
    /// FD: G-REC
    pub g_rec: FixedString<1>,
    /// FD: H-REC
    pub h_rec: FixedString<1>,
    /// FD: J-REC
    pub j_rec: FixedString<1>,
    /// FD: K-REC
    pub k_rec: FixedString<1>,
    /// FD: L-REC
    pub l_rec: FixedString<1>,
    /// FD: M-REC
    pub m_rec: FixedString<1>,
    /// FD: N-REC
    pub n_rec: FixedString<1>,
    /// FD: O-REC
    pub o_rec: FixedString<1>,
    /// FD: P-REC
    pub p_rec: FixedString<1>,
    /// FD: Q-REC
    pub q_rec: FixedString<1>,
    /// FD: R-REC
    pub r_rec: FixedString<1>,
    /// FS
    pub fs: FixedString<2>,
    /// GS
    pub gs: u32,
    /// JS
    pub js: u32,
    /// KS
    pub ks: FixedString<2>,
    /// LS
    pub ls: Decimal /* 0,2 Unsigned */,
    /// MS
    pub ms: u32,
    /// NS
    pub ns: FixedString<3>,
    /// X
    pub x: X,
    /// Y
    pub y: u32,
    /// Z
    pub z: [FixedString<2>; 1],
    /// OS
    pub os: FixedString<2>,
    /// Z2
    pub z2: [FixedString<2>; 1],
    /// RS
    pub rs: FixedString<1>,
    /// FILE STATUS: PS
    pub ps: FixedString<2>,
    /// FILE STATUS: NON-EXISTENT
    pub non_existent: FixedString<2>,
    /// File status for F
    pub _fs_f: FileStatus,
    /// File handle for F
    pub _fh_f: CobolFile,
    /// File status for G
    pub _fs_g: FileStatus,
    /// File handle for G
    pub _fh_g: CobolFile,
    /// File status for H
    pub _fs_h: FileStatus,
    /// File handle for H
    pub _fh_h: CobolFile,
    /// File status for J
    pub _fs_j: FileStatus,
    /// File handle for J
    pub _fh_j: CobolFile,
    /// File status for K
    pub _fs_k: FileStatus,
    /// File handle for K
    pub _fh_k: CobolFile,
    /// File status for L
    pub _fs_l: FileStatus,
    /// File handle for L
    pub _fh_l: CobolFile,
    /// File status for M
    pub _fs_m: FileStatus,
    /// File handle for M
    pub _fh_m: CobolFile,
    /// File status for N
    pub _fs_n: FileStatus,
    /// File handle for N
    pub _fh_n: CobolFile,
    /// File status for O
    pub _fs_o: FileStatus,
    /// File handle for O
    pub _fh_o: CobolFile,
    /// File status for P
    pub _fs_p: FileStatus,
    /// File handle for P
    pub _fh_p: CobolFile,
    /// File status for Q
    pub _fs_q: FileStatus,
    /// File handle for Q
    pub _fh_q: CobolFile,
    /// File status for R
    pub _fs_r: FileStatus,
    /// File handle for R
    pub _fh_r: CobolFile,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            hs: Default::default(),
            g_rec: Default::default(),
            h_rec: Default::default(),
            j_rec: Default::default(),
            k_rec: Default::default(),
            l_rec: Default::default(),
            m_rec: Default::default(),
            n_rec: Default::default(),
            o_rec: Default::default(),
            p_rec: Default::default(),
            q_rec: Default::default(),
            r_rec: Default::default(),
            fs: Default::default(),
            gs: Default::default(),
            js: Default::default(),
            ks: Default::default(),
            ls: Default::default(),
            ms: Default::default(),
            ns: Default::default(),
            x: Default::default(),
            y: Default::default(),
            z: Default::default(),
            os: Default::default(),
            z2: Default::default(),
            rs: Default::default(),
            ps: Default::default(),
            non_existent: Default::default(),
            _fs_f: FileStatus::Success,
            _fh_f: CobolFile::Closed,
            _fs_g: FileStatus::Success,
            _fh_g: CobolFile::Closed,
            _fs_h: FileStatus::Success,
            _fh_h: CobolFile::Closed,
            _fs_j: FileStatus::Success,
            _fh_j: CobolFile::Closed,
            _fs_k: FileStatus::Success,
            _fh_k: CobolFile::Closed,
            _fs_l: FileStatus::Success,
            _fh_l: CobolFile::Closed,
            _fs_m: FileStatus::Success,
            _fh_m: CobolFile::Closed,
            _fs_n: FileStatus::Success,
            _fh_n: CobolFile::Closed,
            _fs_o: FileStatus::Success,
            _fh_o: CobolFile::Closed,
            _fs_p: FileStatus::Success,
            _fh_p: CobolFile::Closed,
            _fs_q: FileStatus::Success,
            _fh_q: CobolFile::Closed,
            _fs_r: FileStatus::Success,
            _fh_r: CobolFile::Closed,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// PROG
fn p_prog(state: &mut ProgramState) {
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT F
fn f_open_input(state: &mut ProgramState) {
    let path = std::env::var("F").unwrap_or("f.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_f = handle; state._fs_f = FileStatus::Success; }
        Err(_) => { state._fs_f = FileStatus::Error("35".to_string()); }
    }
    state.fs = FixedString::from(format!("{}", state._fs_f));
}

/// OPEN OUTPUT F
fn f_open_output(state: &mut ProgramState) {
    let path = std::env::var("F").unwrap_or("f.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_f = handle; state._fs_f = FileStatus::Success; }
        Err(_) => { state._fs_f = FileStatus::Error("35".to_string()); }
    }
    state.fs = FixedString::from(format!("{}", state._fs_f));
}

/// READ F
fn f_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_f.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(2);
            if _len > 0 { let _end = _len.min(0+2); state.hs = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_f = FileStatus::Success;
    state.fs = FixedString::from(format!("{}", state._fs_f));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_f = FileStatus::AtEnd;
    state.fs = FixedString::from(format!("{}", state._fs_f));
        }
        Err(e) => {
            state._fs_f = e.clone();
    state.fs = FixedString::from(format!("{}", state._fs_f));
        }
    }
    Ok(())
}

/// WRITE to F
fn f_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 2];
    { let _src = state.hs.as_bytes(); let _end = (0+2).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_f.write_record(&_buf) {
        Ok(()) => state._fs_f = FileStatus::Success,
        Err(e) => state._fs_f = e,
    }
}

/// CLOSE F
fn f_close(state: &mut ProgramState) {
    match state._fh_f.close() {
        Ok(()) => state._fs_f = FileStatus::Success,
        Err(e) => state._fs_f = e,
    }
    state.fs = FixedString::from(format!("{}", state._fs_f));
}

/// OPEN I-O F
fn f_open_io(state: &mut ProgramState) {
    let path = std::env::var("F").unwrap_or("f.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_f = handle; state._fs_f = FileStatus::Success; }
        Err(_) => { state._fs_f = FileStatus::Error("35".to_string()); }
    }
    state.fs = FixedString::from(format!("{}", state._fs_f));
}

/// OPEN EXTEND F
fn f_open_extend(state: &mut ProgramState) {
    let path = std::env::var("F").unwrap_or("f.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_f = handle; state._fs_f = FileStatus::Success; }
        Err(_) => { state._fs_f = FileStatus::Error("35".to_string()); }
    }
    state.fs = FixedString::from(format!("{}", state._fs_f));
}

/// OPEN INPUT G
fn g_open_input(state: &mut ProgramState) {
    let path = std::env::var("G").unwrap_or("g.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_g = handle; state._fs_g = FileStatus::Success; }
        Err(_) => { state._fs_g = FileStatus::Error("35".to_string()); }
    }
    state.gs = format!("{}", state._fs_g).trim().parse().unwrap_or(0);
}

/// OPEN OUTPUT G
fn g_open_output(state: &mut ProgramState) {
    let path = std::env::var("G").unwrap_or("g.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_g = handle; state._fs_g = FileStatus::Success; }
        Err(_) => { state._fs_g = FileStatus::Error("35".to_string()); }
    }
    state.gs = format!("{}", state._fs_g).trim().parse().unwrap_or(0);
}

/// READ G
fn g_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_g.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(1);
            if _len > 0 { let _end = _len.min(0+1); state.g_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_g = FileStatus::Success;
    state.gs = format!("{}", state._fs_g).trim().parse().unwrap_or(0);
        }
        Err(FileStatus::AtEnd) => {
            state._fs_g = FileStatus::AtEnd;
    state.gs = format!("{}", state._fs_g).trim().parse().unwrap_or(0);
        }
        Err(e) => {
            state._fs_g = e.clone();
    state.gs = format!("{}", state._fs_g).trim().parse().unwrap_or(0);
        }
    }
    Ok(())
}

/// WRITE to G
fn g_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 1];
    { let _src = state.g_rec.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_g.write_record(&_buf) {
        Ok(()) => state._fs_g = FileStatus::Success,
        Err(e) => state._fs_g = e,
    }
}

/// CLOSE G
fn g_close(state: &mut ProgramState) {
    match state._fh_g.close() {
        Ok(()) => state._fs_g = FileStatus::Success,
        Err(e) => state._fs_g = e,
    }
    state.gs = format!("{}", state._fs_g).trim().parse().unwrap_or(0);
}

/// OPEN I-O G
fn g_open_io(state: &mut ProgramState) {
    let path = std::env::var("G").unwrap_or("g.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_g = handle; state._fs_g = FileStatus::Success; }
        Err(_) => { state._fs_g = FileStatus::Error("35".to_string()); }
    }
    state.gs = format!("{}", state._fs_g).trim().parse().unwrap_or(0);
}

/// OPEN EXTEND G
fn g_open_extend(state: &mut ProgramState) {
    let path = std::env::var("G").unwrap_or("g.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_g = handle; state._fs_g = FileStatus::Success; }
        Err(_) => { state._fs_g = FileStatus::Error("35".to_string()); }
    }
    state.gs = format!("{}", state._fs_g).trim().parse().unwrap_or(0);
}

/// OPEN INPUT H
fn h_open_input(state: &mut ProgramState) {
    let path = std::env::var("H").unwrap_or("h.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_h = handle; state._fs_h = FileStatus::Success; }
        Err(_) => { state._fs_h = FileStatus::Error("35".to_string()); }
    }
    state.hs = FixedString::from(format!("{}", state._fs_h));
}

/// OPEN OUTPUT H
fn h_open_output(state: &mut ProgramState) {
    let path = std::env::var("H").unwrap_or("h.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_h = handle; state._fs_h = FileStatus::Success; }
        Err(_) => { state._fs_h = FileStatus::Error("35".to_string()); }
    }
    state.hs = FixedString::from(format!("{}", state._fs_h));
}

/// READ H
fn h_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_h.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(1);
            if _len > 0 { let _end = _len.min(0+1); state.h_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_h = FileStatus::Success;
    state.hs = FixedString::from(format!("{}", state._fs_h));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_h = FileStatus::AtEnd;
    state.hs = FixedString::from(format!("{}", state._fs_h));
        }
        Err(e) => {
            state._fs_h = e.clone();
    state.hs = FixedString::from(format!("{}", state._fs_h));
        }
    }
    Ok(())
}

/// WRITE to H
fn h_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 1];
    { let _src = state.h_rec.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_h.write_record(&_buf) {
        Ok(()) => state._fs_h = FileStatus::Success,
        Err(e) => state._fs_h = e,
    }
}

/// CLOSE H
fn h_close(state: &mut ProgramState) {
    match state._fh_h.close() {
        Ok(()) => state._fs_h = FileStatus::Success,
        Err(e) => state._fs_h = e,
    }
    state.hs = FixedString::from(format!("{}", state._fs_h));
}

/// OPEN I-O H
fn h_open_io(state: &mut ProgramState) {
    let path = std::env::var("H").unwrap_or("h.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_h = handle; state._fs_h = FileStatus::Success; }
        Err(_) => { state._fs_h = FileStatus::Error("35".to_string()); }
    }
    state.hs = FixedString::from(format!("{}", state._fs_h));
}

/// OPEN EXTEND H
fn h_open_extend(state: &mut ProgramState) {
    let path = std::env::var("H").unwrap_or("h.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_h = handle; state._fs_h = FileStatus::Success; }
        Err(_) => { state._fs_h = FileStatus::Error("35".to_string()); }
    }
    state.hs = FixedString::from(format!("{}", state._fs_h));
}

/// OPEN INPUT J
fn j_open_input(state: &mut ProgramState) {
    let path = std::env::var("J").unwrap_or("j.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_j = handle; state._fs_j = FileStatus::Success; }
        Err(_) => { state._fs_j = FileStatus::Error("35".to_string()); }
    }
    state.js = format!("{}", state._fs_j).trim().parse().unwrap_or(0);
}

/// OPEN OUTPUT J
fn j_open_output(state: &mut ProgramState) {
    let path = std::env::var("J").unwrap_or("j.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_j = handle; state._fs_j = FileStatus::Success; }
        Err(_) => { state._fs_j = FileStatus::Error("35".to_string()); }
    }
    state.js = format!("{}", state._fs_j).trim().parse().unwrap_or(0);
}

/// READ J
fn j_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_j.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(1);
            if _len > 0 { let _end = _len.min(0+1); state.j_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_j = FileStatus::Success;
    state.js = format!("{}", state._fs_j).trim().parse().unwrap_or(0);
        }
        Err(FileStatus::AtEnd) => {
            state._fs_j = FileStatus::AtEnd;
    state.js = format!("{}", state._fs_j).trim().parse().unwrap_or(0);
        }
        Err(e) => {
            state._fs_j = e.clone();
    state.js = format!("{}", state._fs_j).trim().parse().unwrap_or(0);
        }
    }
    Ok(())
}

/// WRITE to J
fn j_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 1];
    { let _src = state.j_rec.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_j.write_record(&_buf) {
        Ok(()) => state._fs_j = FileStatus::Success,
        Err(e) => state._fs_j = e,
    }
}

/// CLOSE J
fn j_close(state: &mut ProgramState) {
    match state._fh_j.close() {
        Ok(()) => state._fs_j = FileStatus::Success,
        Err(e) => state._fs_j = e,
    }
    state.js = format!("{}", state._fs_j).trim().parse().unwrap_or(0);
}

/// OPEN I-O J
fn j_open_io(state: &mut ProgramState) {
    let path = std::env::var("J").unwrap_or("j.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_j = handle; state._fs_j = FileStatus::Success; }
        Err(_) => { state._fs_j = FileStatus::Error("35".to_string()); }
    }
    state.js = format!("{}", state._fs_j).trim().parse().unwrap_or(0);
}

/// OPEN EXTEND J
fn j_open_extend(state: &mut ProgramState) {
    let path = std::env::var("J").unwrap_or("j.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_j = handle; state._fs_j = FileStatus::Success; }
        Err(_) => { state._fs_j = FileStatus::Error("35".to_string()); }
    }
    state.js = format!("{}", state._fs_j).trim().parse().unwrap_or(0);
}

/// OPEN INPUT K
fn k_open_input(state: &mut ProgramState) {
    let path = std::env::var("K").unwrap_or("k.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_k = handle; state._fs_k = FileStatus::Success; }
        Err(_) => { state._fs_k = FileStatus::Error("35".to_string()); }
    }
    state.ks = FixedString::from(format!("{}", state._fs_k));
}

/// OPEN OUTPUT K
fn k_open_output(state: &mut ProgramState) {
    let path = std::env::var("K").unwrap_or("k.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_k = handle; state._fs_k = FileStatus::Success; }
        Err(_) => { state._fs_k = FileStatus::Error("35".to_string()); }
    }
    state.ks = FixedString::from(format!("{}", state._fs_k));
}

/// READ K
fn k_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_k.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(1);
            if _len > 0 { let _end = _len.min(0+1); state.k_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_k = FileStatus::Success;
    state.ks = FixedString::from(format!("{}", state._fs_k));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_k = FileStatus::AtEnd;
    state.ks = FixedString::from(format!("{}", state._fs_k));
        }
        Err(e) => {
            state._fs_k = e.clone();
    state.ks = FixedString::from(format!("{}", state._fs_k));
        }
    }
    Ok(())
}

/// WRITE to K
fn k_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 1];
    { let _src = state.k_rec.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_k.write_record(&_buf) {
        Ok(()) => state._fs_k = FileStatus::Success,
        Err(e) => state._fs_k = e,
    }
}

/// CLOSE K
fn k_close(state: &mut ProgramState) {
    match state._fh_k.close() {
        Ok(()) => state._fs_k = FileStatus::Success,
        Err(e) => state._fs_k = e,
    }
    state.ks = FixedString::from(format!("{}", state._fs_k));
}

/// OPEN I-O K
fn k_open_io(state: &mut ProgramState) {
    let path = std::env::var("K").unwrap_or("k.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_k = handle; state._fs_k = FileStatus::Success; }
        Err(_) => { state._fs_k = FileStatus::Error("35".to_string()); }
    }
    state.ks = FixedString::from(format!("{}", state._fs_k));
}

/// OPEN EXTEND K
fn k_open_extend(state: &mut ProgramState) {
    let path = std::env::var("K").unwrap_or("k.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_k = handle; state._fs_k = FileStatus::Success; }
        Err(_) => { state._fs_k = FileStatus::Error("35".to_string()); }
    }
    state.ks = FixedString::from(format!("{}", state._fs_k));
}

/// OPEN INPUT L
fn l_open_input(state: &mut ProgramState) {
    let path = std::env::var("L").unwrap_or("l.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_l = handle; state._fs_l = FileStatus::Success; }
        Err(_) => { state._fs_l = FileStatus::Error("35".to_string()); }
    }
    state.ls = Decimal::from(format!("{}", state._fs_l).trim().parse::<i64>().unwrap_or(0));
}

/// OPEN OUTPUT L
fn l_open_output(state: &mut ProgramState) {
    let path = std::env::var("L").unwrap_or("l.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_l = handle; state._fs_l = FileStatus::Success; }
        Err(_) => { state._fs_l = FileStatus::Error("35".to_string()); }
    }
    state.ls = Decimal::from(format!("{}", state._fs_l).trim().parse::<i64>().unwrap_or(0));
}

/// READ L
fn l_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_l.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(1);
            if _len > 0 { let _end = _len.min(0+1); state.l_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_l = FileStatus::Success;
    state.ls = Decimal::from(format!("{}", state._fs_l).trim().parse::<i64>().unwrap_or(0));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_l = FileStatus::AtEnd;
    state.ls = Decimal::from(format!("{}", state._fs_l).trim().parse::<i64>().unwrap_or(0));
        }
        Err(e) => {
            state._fs_l = e.clone();
    state.ls = Decimal::from(format!("{}", state._fs_l).trim().parse::<i64>().unwrap_or(0));
        }
    }
    Ok(())
}

/// WRITE to L
fn l_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 1];
    { let _src = state.l_rec.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_l.write_record(&_buf) {
        Ok(()) => state._fs_l = FileStatus::Success,
        Err(e) => state._fs_l = e,
    }
}

/// CLOSE L
fn l_close(state: &mut ProgramState) {
    match state._fh_l.close() {
        Ok(()) => state._fs_l = FileStatus::Success,
        Err(e) => state._fs_l = e,
    }
    state.ls = Decimal::from(format!("{}", state._fs_l).trim().parse::<i64>().unwrap_or(0));
}

/// OPEN I-O L
fn l_open_io(state: &mut ProgramState) {
    let path = std::env::var("L").unwrap_or("l.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_l = handle; state._fs_l = FileStatus::Success; }
        Err(_) => { state._fs_l = FileStatus::Error("35".to_string()); }
    }
    state.ls = Decimal::from(format!("{}", state._fs_l).trim().parse::<i64>().unwrap_or(0));
}

/// OPEN EXTEND L
fn l_open_extend(state: &mut ProgramState) {
    let path = std::env::var("L").unwrap_or("l.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_l = handle; state._fs_l = FileStatus::Success; }
        Err(_) => { state._fs_l = FileStatus::Error("35".to_string()); }
    }
    state.ls = Decimal::from(format!("{}", state._fs_l).trim().parse::<i64>().unwrap_or(0));
}

/// OPEN INPUT M
fn m_open_input(state: &mut ProgramState) {
    let path = std::env::var("M").unwrap_or("m.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_m = handle; state._fs_m = FileStatus::Success; }
        Err(_) => { state._fs_m = FileStatus::Error("35".to_string()); }
    }
    state.ms = format!("{}", state._fs_m).trim().parse().unwrap_or(0);
}

/// OPEN OUTPUT M
fn m_open_output(state: &mut ProgramState) {
    let path = std::env::var("M").unwrap_or("m.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_m = handle; state._fs_m = FileStatus::Success; }
        Err(_) => { state._fs_m = FileStatus::Error("35".to_string()); }
    }
    state.ms = format!("{}", state._fs_m).trim().parse().unwrap_or(0);
}

/// READ M
fn m_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_m.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(1);
            if _len > 0 { let _end = _len.min(0+1); state.m_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_m = FileStatus::Success;
    state.ms = format!("{}", state._fs_m).trim().parse().unwrap_or(0);
        }
        Err(FileStatus::AtEnd) => {
            state._fs_m = FileStatus::AtEnd;
    state.ms = format!("{}", state._fs_m).trim().parse().unwrap_or(0);
        }
        Err(e) => {
            state._fs_m = e.clone();
    state.ms = format!("{}", state._fs_m).trim().parse().unwrap_or(0);
        }
    }
    Ok(())
}

/// WRITE to M
fn m_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 1];
    { let _src = state.m_rec.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_m.write_record(&_buf) {
        Ok(()) => state._fs_m = FileStatus::Success,
        Err(e) => state._fs_m = e,
    }
}

/// CLOSE M
fn m_close(state: &mut ProgramState) {
    match state._fh_m.close() {
        Ok(()) => state._fs_m = FileStatus::Success,
        Err(e) => state._fs_m = e,
    }
    state.ms = format!("{}", state._fs_m).trim().parse().unwrap_or(0);
}

/// OPEN I-O M
fn m_open_io(state: &mut ProgramState) {
    let path = std::env::var("M").unwrap_or("m.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_m = handle; state._fs_m = FileStatus::Success; }
        Err(_) => { state._fs_m = FileStatus::Error("35".to_string()); }
    }
    state.ms = format!("{}", state._fs_m).trim().parse().unwrap_or(0);
}

/// OPEN EXTEND M
fn m_open_extend(state: &mut ProgramState) {
    let path = std::env::var("M").unwrap_or("m.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_m = handle; state._fs_m = FileStatus::Success; }
        Err(_) => { state._fs_m = FileStatus::Error("35".to_string()); }
    }
    state.ms = format!("{}", state._fs_m).trim().parse().unwrap_or(0);
}

/// OPEN INPUT N
fn n_open_input(state: &mut ProgramState) {
    let path = std::env::var("N").unwrap_or("n.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_n = handle; state._fs_n = FileStatus::Success; }
        Err(_) => { state._fs_n = FileStatus::Error("35".to_string()); }
    }
    state.ns = FixedString::from(format!("{}", state._fs_n));
}

/// OPEN OUTPUT N
fn n_open_output(state: &mut ProgramState) {
    let path = std::env::var("N").unwrap_or("n.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_n = handle; state._fs_n = FileStatus::Success; }
        Err(_) => { state._fs_n = FileStatus::Error("35".to_string()); }
    }
    state.ns = FixedString::from(format!("{}", state._fs_n));
}

/// READ N
fn n_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_n.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(1);
            if _len > 0 { let _end = _len.min(0+1); state.n_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_n = FileStatus::Success;
    state.ns = FixedString::from(format!("{}", state._fs_n));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_n = FileStatus::AtEnd;
    state.ns = FixedString::from(format!("{}", state._fs_n));
        }
        Err(e) => {
            state._fs_n = e.clone();
    state.ns = FixedString::from(format!("{}", state._fs_n));
        }
    }
    Ok(())
}

/// WRITE to N
fn n_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 1];
    { let _src = state.n_rec.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_n.write_record(&_buf) {
        Ok(()) => state._fs_n = FileStatus::Success,
        Err(e) => state._fs_n = e,
    }
}

/// CLOSE N
fn n_close(state: &mut ProgramState) {
    match state._fh_n.close() {
        Ok(()) => state._fs_n = FileStatus::Success,
        Err(e) => state._fs_n = e,
    }
    state.ns = FixedString::from(format!("{}", state._fs_n));
}

/// OPEN I-O N
fn n_open_io(state: &mut ProgramState) {
    let path = std::env::var("N").unwrap_or("n.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_n = handle; state._fs_n = FileStatus::Success; }
        Err(_) => { state._fs_n = FileStatus::Error("35".to_string()); }
    }
    state.ns = FixedString::from(format!("{}", state._fs_n));
}

/// OPEN EXTEND N
fn n_open_extend(state: &mut ProgramState) {
    let path = std::env::var("N").unwrap_or("n.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_n = handle; state._fs_n = FileStatus::Success; }
        Err(_) => { state._fs_n = FileStatus::Error("35".to_string()); }
    }
    state.ns = FixedString::from(format!("{}", state._fs_n));
}

/// OPEN INPUT O
fn o_open_input(state: &mut ProgramState) {
    let path = std::env::var("O").unwrap_or("o.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_o = handle; state._fs_o = FileStatus::Success; }
        Err(_) => { state._fs_o = FileStatus::Error("35".to_string()); }
    }
    state.os = FixedString::from(format!("{}", state._fs_o));
}

/// OPEN OUTPUT O
fn o_open_output(state: &mut ProgramState) {
    let path = std::env::var("O").unwrap_or("o.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_o = handle; state._fs_o = FileStatus::Success; }
        Err(_) => { state._fs_o = FileStatus::Error("35".to_string()); }
    }
    state.os = FixedString::from(format!("{}", state._fs_o));
}

/// READ O
fn o_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_o.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(1);
            if _len > 0 { let _end = _len.min(0+1); state.o_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_o = FileStatus::Success;
    state.os = FixedString::from(format!("{}", state._fs_o));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_o = FileStatus::AtEnd;
    state.os = FixedString::from(format!("{}", state._fs_o));
        }
        Err(e) => {
            state._fs_o = e.clone();
    state.os = FixedString::from(format!("{}", state._fs_o));
        }
    }
    Ok(())
}

/// WRITE to O
fn o_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 1];
    { let _src = state.o_rec.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_o.write_record(&_buf) {
        Ok(()) => state._fs_o = FileStatus::Success,
        Err(e) => state._fs_o = e,
    }
}

/// CLOSE O
fn o_close(state: &mut ProgramState) {
    match state._fh_o.close() {
        Ok(()) => state._fs_o = FileStatus::Success,
        Err(e) => state._fs_o = e,
    }
    state.os = FixedString::from(format!("{}", state._fs_o));
}

/// OPEN I-O O
fn o_open_io(state: &mut ProgramState) {
    let path = std::env::var("O").unwrap_or("o.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_o = handle; state._fs_o = FileStatus::Success; }
        Err(_) => { state._fs_o = FileStatus::Error("35".to_string()); }
    }
    state.os = FixedString::from(format!("{}", state._fs_o));
}

/// OPEN EXTEND O
fn o_open_extend(state: &mut ProgramState) {
    let path = std::env::var("O").unwrap_or("o.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_o = handle; state._fs_o = FileStatus::Success; }
        Err(_) => { state._fs_o = FileStatus::Error("35".to_string()); }
    }
    state.os = FixedString::from(format!("{}", state._fs_o));
}

/// OPEN INPUT P
fn p_open_input(state: &mut ProgramState) {
    let path = std::env::var("P").unwrap_or("p.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_p = handle; state._fs_p = FileStatus::Success; }
        Err(_) => { state._fs_p = FileStatus::Error("35".to_string()); }
    }
    state.ps = FixedString::from(format!("{}", state._fs_p));
}

/// OPEN OUTPUT P
fn p_open_output(state: &mut ProgramState) {
    let path = std::env::var("P").unwrap_or("p.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_p = handle; state._fs_p = FileStatus::Success; }
        Err(_) => { state._fs_p = FileStatus::Error("35".to_string()); }
    }
    state.ps = FixedString::from(format!("{}", state._fs_p));
}

/// READ P
fn p_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_p.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(1);
            if _len > 0 { let _end = _len.min(0+1); state.p_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_p = FileStatus::Success;
    state.ps = FixedString::from(format!("{}", state._fs_p));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_p = FileStatus::AtEnd;
    state.ps = FixedString::from(format!("{}", state._fs_p));
        }
        Err(e) => {
            state._fs_p = e.clone();
    state.ps = FixedString::from(format!("{}", state._fs_p));
        }
    }
    Ok(())
}

/// WRITE to P
fn p_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 1];
    { let _src = state.p_rec.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_p.write_record(&_buf) {
        Ok(()) => state._fs_p = FileStatus::Success,
        Err(e) => state._fs_p = e,
    }
}

/// CLOSE P
fn p_close(state: &mut ProgramState) {
    match state._fh_p.close() {
        Ok(()) => state._fs_p = FileStatus::Success,
        Err(e) => state._fs_p = e,
    }
    state.ps = FixedString::from(format!("{}", state._fs_p));
}

/// OPEN I-O P
fn p_open_io(state: &mut ProgramState) {
    let path = std::env::var("P").unwrap_or("p.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_p = handle; state._fs_p = FileStatus::Success; }
        Err(_) => { state._fs_p = FileStatus::Error("35".to_string()); }
    }
    state.ps = FixedString::from(format!("{}", state._fs_p));
}

/// OPEN EXTEND P
fn p_open_extend(state: &mut ProgramState) {
    let path = std::env::var("P").unwrap_or("p.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_p = handle; state._fs_p = FileStatus::Success; }
        Err(_) => { state._fs_p = FileStatus::Error("35".to_string()); }
    }
    state.ps = FixedString::from(format!("{}", state._fs_p));
}

/// OPEN INPUT Q
fn q_open_input(state: &mut ProgramState) {
    let path = std::env::var("Q").unwrap_or("q.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_q = handle; state._fs_q = FileStatus::Success; }
        Err(_) => { state._fs_q = FileStatus::Error("35".to_string()); }
    }
    state.non_existent = FixedString::from(format!("{}", state._fs_q));
}

/// OPEN OUTPUT Q
fn q_open_output(state: &mut ProgramState) {
    let path = std::env::var("Q").unwrap_or("q.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_q = handle; state._fs_q = FileStatus::Success; }
        Err(_) => { state._fs_q = FileStatus::Error("35".to_string()); }
    }
    state.non_existent = FixedString::from(format!("{}", state._fs_q));
}

/// READ Q
fn q_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_q.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(1);
            if _len > 0 { let _end = _len.min(0+1); state.q_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_q = FileStatus::Success;
    state.non_existent = FixedString::from(format!("{}", state._fs_q));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_q = FileStatus::AtEnd;
    state.non_existent = FixedString::from(format!("{}", state._fs_q));
        }
        Err(e) => {
            state._fs_q = e.clone();
    state.non_existent = FixedString::from(format!("{}", state._fs_q));
        }
    }
    Ok(())
}

/// WRITE to Q
fn q_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 1];
    { let _src = state.q_rec.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_q.write_record(&_buf) {
        Ok(()) => state._fs_q = FileStatus::Success,
        Err(e) => state._fs_q = e,
    }
}

/// CLOSE Q
fn q_close(state: &mut ProgramState) {
    match state._fh_q.close() {
        Ok(()) => state._fs_q = FileStatus::Success,
        Err(e) => state._fs_q = e,
    }
    state.non_existent = FixedString::from(format!("{}", state._fs_q));
}

/// OPEN I-O Q
fn q_open_io(state: &mut ProgramState) {
    let path = std::env::var("Q").unwrap_or("q.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_q = handle; state._fs_q = FileStatus::Success; }
        Err(_) => { state._fs_q = FileStatus::Error("35".to_string()); }
    }
    state.non_existent = FixedString::from(format!("{}", state._fs_q));
}

/// OPEN EXTEND Q
fn q_open_extend(state: &mut ProgramState) {
    let path = std::env::var("Q").unwrap_or("q.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_q = handle; state._fs_q = FileStatus::Success; }
        Err(_) => { state._fs_q = FileStatus::Error("35".to_string()); }
    }
    state.non_existent = FixedString::from(format!("{}", state._fs_q));
}

/// OPEN INPUT R
fn r_open_input(state: &mut ProgramState) {
    let path = std::env::var("R").unwrap_or("r.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_r = handle; state._fs_r = FileStatus::Success; }
        Err(_) => { state._fs_r = FileStatus::Error("35".to_string()); }
    }
    state.rs = FixedString::from(format!("{}", state._fs_r));
}

/// OPEN OUTPUT R
fn r_open_output(state: &mut ProgramState) {
    let path = std::env::var("R").unwrap_or("r.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_r = handle; state._fs_r = FileStatus::Success; }
        Err(_) => { state._fs_r = FileStatus::Error("35".to_string()); }
    }
    state.rs = FixedString::from(format!("{}", state._fs_r));
}

/// READ R
fn r_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_r.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(1);
            if _len > 0 { let _end = _len.min(0+1); state.r_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_r = FileStatus::Success;
    state.rs = FixedString::from(format!("{}", state._fs_r));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_r = FileStatus::AtEnd;
    state.rs = FixedString::from(format!("{}", state._fs_r));
        }
        Err(e) => {
            state._fs_r = e.clone();
    state.rs = FixedString::from(format!("{}", state._fs_r));
        }
    }
    Ok(())
}

/// WRITE to R
fn r_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 1];
    { let _src = state.r_rec.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_r.write_record(&_buf) {
        Ok(()) => state._fs_r = FileStatus::Success,
        Err(e) => state._fs_r = e,
    }
}

/// CLOSE R
fn r_close(state: &mut ProgramState) {
    match state._fh_r.close() {
        Ok(()) => state._fs_r = FileStatus::Success,
        Err(e) => state._fs_r = e,
    }
    state.rs = FixedString::from(format!("{}", state._fs_r));
}

/// OPEN I-O R
fn r_open_io(state: &mut ProgramState) {
    let path = std::env::var("R").unwrap_or("r.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_r = handle; state._fs_r = FileStatus::Success; }
        Err(_) => { state._fs_r = FileStatus::Error("35".to_string()); }
    }
    state.rs = FixedString::from(format!("{}", state._fs_r));
}

/// OPEN EXTEND R
fn r_open_extend(state: &mut ProgramState) {
    let path = std::env::var("R").unwrap_or("r.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_r = handle; state._fs_r = FileStatus::Success; }
        Err(_) => { state._fs_r = FileStatus::Error("35".to_string()); }
    }
    state.rs = FixedString::from(format!("{}", state._fs_r));
}

fn main() {
    let mut state = ProgramState::default();
    p_prog(&mut state);
}

