// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct TspflRecord {
    /// TSPFL-REC
    pub tspfl_rec: TspflRec,
}
impl std::fmt::Display for TspflRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.tspfl_rec)
    }
}
impl From<&str> for TspflRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TspflRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl TspflRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TspflRec {
    /// CM-CUST-NUM
    pub cm_cust_num: CmCustNum,
    /// CM-STATUS
    pub cm_status: FixedString<1>,
    /// CM-COMPANY
    pub cm_company: FixedString<25>,
    /// CM-ADDRESS-1
    pub cm_address_1: FixedString<25>,
    /// CM-ADDRESS-2
    pub cm_address_2: FixedString<25>,
    /// CM-ADDRESS-3
    pub cm_address_3: FixedString<25>,
    /// CM-TELEPHONE
    pub cm_telephone: u64,
    /// CM-DP-MGR
    pub cm_dp_mgr: FixedString<25>,
    /// CM-MACHINE
    pub cm_machine: FixedString<8>,
    /// CM-MEMORY
    pub cm_memory: FixedString<4>,
    /// CM-DISK
    pub cm_disk: FixedString<8>,
    /// CM-TAPE
    pub cm_tape: FixedString<8>,
    /// CM-NO-TERMINALS
    pub cm_no_terminals: u32,
}
impl std::fmt::Display for TspflRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}", self.cm_cust_num, self.cm_status, self.cm_company, self.cm_address_1, self.cm_address_2, self.cm_address_3, self.cm_telephone, self.cm_dp_mgr, self.cm_machine, self.cm_memory, self.cm_disk, self.cm_tape, self.cm_no_terminals)
    }
}
impl From<&str> for TspflRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TspflRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl TspflRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CmCustNum {
    /// CM-CUST-PRE
    pub cm_cust_pre: FixedString<3>,
    /// CM-CUST-NNN
    pub cm_cust_nnn: FixedString<5>,
}
impl std::fmt::Display for CmCustNum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.cm_cust_pre, self.cm_cust_nnn)
    }
}
impl From<&str> for CmCustNum {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CmCustNum {
    fn from(_s: String) -> Self { Self::default() }
}
impl CmCustNum {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Tspfile {
    /// TSPFL-RECORD
    pub tspfl_record: TspflRecord,
}
impl std::fmt::Display for Tspfile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.tspfl_record)
    }
}
impl From<&str> for Tspfile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Tspfile {
    fn from(_s: String) -> Self { Self::default() }
}
impl Tspfile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CustStat {
    /// STAT-1
    pub stat_1: u32,
    /// FILLER PIC FILLER
    pub _filler_54: Filler54,
}
impl std::fmt::Display for CustStat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.stat_1, self._filler_54)
    }
}
impl From<&str> for CustStat {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CustStat {
    fn from(_s: String) -> Self { Self::default() }
}
impl CustStat {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Filler54 {
    /// STAT-X1
    pub stat_x1: FixedString<1>,
    /// STAT-X2
    pub stat_x2: StatX2,
}
impl std::fmt::Display for Filler54 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.stat_x1, self.stat_x2)
    }
}
impl From<&str> for Filler54 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Filler54 {
    fn from(_s: String) -> Self { Self::default() }
}
impl Filler54 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct StatX2 {
    /// BYTE-1
    pub byte_1: u32,
    /// BYTE-2
    pub byte_2: Byte2,
    /// IDX
    pub idx: u32,
    /// IDX2
    pub idx2: u32,
    /// OUT-FILE-NAME
    pub out_file_name: FixedString<9>,
}
impl std::fmt::Display for StatX2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}", self.byte_1, self.byte_2, self.idx, self.idx2, self.out_file_name)
    }
}
impl From<&str> for StatX2 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for StatX2 {
    fn from(_s: String) -> Self { Self::default() }
}
impl StatX2 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Byte2 {
    /// MAX-SUB
    pub max_sub: FixedString<1>,
}
impl std::fmt::Display for Byte2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.max_sub)
    }
}
impl From<&str> for Byte2 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Byte2 {
    fn from(_s: String) -> Self { Self::default() }
}
impl Byte2 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TestData {
    /// DATA-CUST-NUM-TBL
    pub data_cust_num_tbl: DataCustNumTbl,
    /// DATA-CUST-NUM
    pub data_cust_num: [FixedString<8>; 0],
    /// DATA-COMPANY-TBL
    pub data_company_tbl: DataCompanyTbl,
    /// DATA-COMPANY
    pub data_company: [FixedString<25>; 0],
    /// DATA-ADDRESS-1-TBL
    pub data_address_1_tbl: DataAddress1Tbl,
    /// DATA-ADDRESS-1
    pub data_address_1: [FixedString<25>; 0],
    /// DATA-ADDRESS-2-TBL
    pub data_address_2_tbl: DataAddress2Tbl,
    /// DATA-ADDRESS-2
    pub data_address_2: [FixedString<10>; 0],
    /// DATA-ADDRESS-3-TBL
    pub data_address_3_tbl: DataAddress3Tbl,
    /// DATA-ADDRESS-3
    pub data_address_3: [FixedString<10>; 0],
    /// DATA-TELEPHONE-TBL
    pub data_telephone_tbl: DataTelephoneTbl,
    /// DATA-TELEPHONE
    pub data_telephone: [u64; 0],
    /// DATA-DP-MGR-TBL
    pub data_dp_mgr_tbl: DataDpMgrTbl,
    /// DATA-DP-MGR
    pub data_dp_mgr: [FixedString<20>; 0],
    /// DATA-MACHINE-TBL
    pub data_machine_tbl: DataMachineTbl,
    /// DATA-MACHINE
    pub data_machine: [FixedString<8>; 0],
    /// DATA-NO-TERMINALS-TBL
    pub data_no_terminals_tbl: DataNoTerminalsTbl,
    /// DATA-NO-TERMINALS
    pub data_no_terminals: [PackedDecimal<3> /* Unsigned */; 0],
}
impl std::fmt::Display for TestData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}", self.data_cust_num_tbl, self.data_company_tbl, self.data_address_1_tbl, self.data_address_2_tbl, self.data_address_3_tbl, self.data_telephone_tbl, self.data_dp_mgr_tbl, self.data_machine_tbl, self.data_no_terminals_tbl)
    }
}
impl From<&str> for TestData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TestData {
    fn from(_s: String) -> Self { Self::default() }
}
impl TestData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataCustNumTbl {
    /// FILLER PIC FILLER
    pub _filler_69: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_70: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_71: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_72: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_73: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_74: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_75: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_76: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_77: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_78: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_79: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_80: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_81: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_82: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_83: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_84: FixedString<8>,
}
impl std::fmt::Display for DataCustNumTbl {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self._filler_69, self._filler_70, self._filler_71, self._filler_72, self._filler_73, self._filler_74, self._filler_75, self._filler_76, self._filler_77, self._filler_78, self._filler_79, self._filler_80, self._filler_81, self._filler_82, self._filler_83, self._filler_84)
    }
}
impl From<&str> for DataCustNumTbl {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataCustNumTbl {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataCustNumTbl {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataCompanyTbl {
    /// FILLER PIC FILLER
    pub _filler_90: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_91: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_92: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_93: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_94: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_95: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_96: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_97: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_98: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_99: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_100: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_101: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_102: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_103: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_104: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_105: FixedString<25>,
}
impl std::fmt::Display for DataCompanyTbl {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self._filler_90, self._filler_91, self._filler_92, self._filler_93, self._filler_94, self._filler_95, self._filler_96, self._filler_97, self._filler_98, self._filler_99, self._filler_100, self._filler_101, self._filler_102, self._filler_103, self._filler_104, self._filler_105)
    }
}
impl From<&str> for DataCompanyTbl {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataCompanyTbl {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataCompanyTbl {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataAddress1Tbl {
    /// FILLER PIC FILLER
    pub _filler_111: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_112: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_113: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_114: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_115: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_116: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_117: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_118: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_119: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_120: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_121: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_122: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_123: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_124: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_125: FixedString<25>,
    /// FILLER PIC FILLER
    pub _filler_126: FixedString<25>,
}
impl std::fmt::Display for DataAddress1Tbl {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self._filler_111, self._filler_112, self._filler_113, self._filler_114, self._filler_115, self._filler_116, self._filler_117, self._filler_118, self._filler_119, self._filler_120, self._filler_121, self._filler_122, self._filler_123, self._filler_124, self._filler_125, self._filler_126)
    }
}
impl From<&str> for DataAddress1Tbl {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataAddress1Tbl {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataAddress1Tbl {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataAddress2Tbl {
    /// FILLER PIC FILLER
    pub _filler_132: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_133: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_134: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_135: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_136: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_137: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_138: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_139: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_140: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_141: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_142: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_143: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_144: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_145: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_146: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_147: FixedString<10>,
}
impl std::fmt::Display for DataAddress2Tbl {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self._filler_132, self._filler_133, self._filler_134, self._filler_135, self._filler_136, self._filler_137, self._filler_138, self._filler_139, self._filler_140, self._filler_141, self._filler_142, self._filler_143, self._filler_144, self._filler_145, self._filler_146, self._filler_147)
    }
}
impl From<&str> for DataAddress2Tbl {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataAddress2Tbl {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataAddress2Tbl {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataAddress3Tbl {
    /// FILLER PIC FILLER
    pub _filler_153: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_154: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_155: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_156: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_157: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_158: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_159: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_160: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_161: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_162: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_163: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_164: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_165: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_166: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_167: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_168: FixedString<10>,
}
impl std::fmt::Display for DataAddress3Tbl {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self._filler_153, self._filler_154, self._filler_155, self._filler_156, self._filler_157, self._filler_158, self._filler_159, self._filler_160, self._filler_161, self._filler_162, self._filler_163, self._filler_164, self._filler_165, self._filler_166, self._filler_167, self._filler_168)
    }
}
impl From<&str> for DataAddress3Tbl {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataAddress3Tbl {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataAddress3Tbl {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataTelephoneTbl {
    /// FILLER PIC FILLER
    pub _filler_174: u64,
    /// FILLER PIC FILLER
    pub _filler_175: u64,
    /// FILLER PIC FILLER
    pub _filler_176: u64,
    /// FILLER PIC FILLER
    pub _filler_177: u64,
    /// FILLER PIC FILLER
    pub _filler_178: u64,
    /// FILLER PIC FILLER
    pub _filler_179: u64,
    /// FILLER PIC FILLER
    pub _filler_180: u64,
    /// FILLER PIC FILLER
    pub _filler_181: u64,
    /// FILLER PIC FILLER
    pub _filler_182: u64,
    /// FILLER PIC FILLER
    pub _filler_183: u64,
    /// FILLER PIC FILLER
    pub _filler_184: u64,
    /// FILLER PIC FILLER
    pub _filler_185: u64,
    /// FILLER PIC FILLER
    pub _filler_186: u64,
    /// FILLER PIC FILLER
    pub _filler_187: u64,
    /// FILLER PIC FILLER
    pub _filler_188: u64,
    /// FILLER PIC FILLER
    pub _filler_189: u64,
}
impl std::fmt::Display for DataTelephoneTbl {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self._filler_174, self._filler_175, self._filler_176, self._filler_177, self._filler_178, self._filler_179, self._filler_180, self._filler_181, self._filler_182, self._filler_183, self._filler_184, self._filler_185, self._filler_186, self._filler_187, self._filler_188, self._filler_189)
    }
}
impl From<&str> for DataTelephoneTbl {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataTelephoneTbl {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataTelephoneTbl {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataDpMgrTbl {
    /// FILLER PIC FILLER
    pub _filler_195: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_196: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_197: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_198: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_199: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_200: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_201: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_202: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_203: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_204: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_205: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_206: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_207: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_208: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_209: FixedString<20>,
    /// FILLER PIC FILLER
    pub _filler_210: FixedString<20>,
}
impl std::fmt::Display for DataDpMgrTbl {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self._filler_195, self._filler_196, self._filler_197, self._filler_198, self._filler_199, self._filler_200, self._filler_201, self._filler_202, self._filler_203, self._filler_204, self._filler_205, self._filler_206, self._filler_207, self._filler_208, self._filler_209, self._filler_210)
    }
}
impl From<&str> for DataDpMgrTbl {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataDpMgrTbl {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataDpMgrTbl {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataMachineTbl {
    /// FILLER PIC FILLER
    pub _filler_216: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_217: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_218: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_219: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_220: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_221: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_222: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_223: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_224: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_225: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_226: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_227: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_228: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_229: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_230: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_231: FixedString<8>,
}
impl std::fmt::Display for DataMachineTbl {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self._filler_216, self._filler_217, self._filler_218, self._filler_219, self._filler_220, self._filler_221, self._filler_222, self._filler_223, self._filler_224, self._filler_225, self._filler_226, self._filler_227, self._filler_228, self._filler_229, self._filler_230, self._filler_231)
    }
}
impl From<&str> for DataMachineTbl {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataMachineTbl {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataMachineTbl {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataNoTerminalsTbl {
    /// FILLER PIC FILLER
    pub _filler_237: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_238: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_239: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_240: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_241: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_242: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_243: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_244: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_245: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_246: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_247: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_248: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_249: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_250: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_251: PackedDecimal<3> /* Unsigned */,
    /// FILLER PIC FILLER
    pub _filler_252: PackedDecimal<3> /* Unsigned */,
}
impl std::fmt::Display for DataNoTerminalsTbl {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self._filler_237, self._filler_238, self._filler_239, self._filler_240, self._filler_241, self._filler_242, self._filler_243, self._filler_244, self._filler_245, self._filler_246, self._filler_247, self._filler_248, self._filler_249, self._filler_250, self._filler_251, self._filler_252)
    }
}
impl From<&str> for DataNoTerminalsTbl {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataNoTerminalsTbl {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataNoTerminalsTbl {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WorkArea {
    /// REC-NUM
    pub rec_num: u32,
    /// SUB
    pub sub: FixedString<1>,
    /// TSPFL-KEY
    pub tspfl_key: FixedString<8>,
    /// KC-PTR
    pub kc_ptr: FixedString<1>,
}
impl std::fmt::Display for WorkArea {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.rec_num, self.sub, self.tspfl_key, self.kc_ptr)
    }
}
impl From<&str> for WorkArea {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WorkArea {
    fn from(_s: String) -> Self { Self::default() }
}
impl WorkArea {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct KeyDef {
    /// KDB-LEN
    pub kdb_len: u32,
    /// FILLER PIC FILLER
    pub _filler_273: FixedString<4>,
    /// KEY-NKEYS
    pub key_nkeys: u32,
    /// FILLER PIC FILLER
    pub _filler_275: FixedString<6>,
    /// KEY-DEFS
    pub key_defs: [KeyDefs; 1],
}
impl std::fmt::Display for KeyDef {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.kdb_len, self._filler_273, self.key_nkeys, self._filler_275)
    }
}
impl From<&str> for KeyDef {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for KeyDef {
    fn from(_s: String) -> Self { Self::default() }
}
impl KeyDef {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct KeyDefs {
    /// KEY-COUNT
    pub key_count: u32,
    /// KEY-OFFSET
    pub key_offset: u32,
    /// KEY-FLAGS
    pub key_flags: FixedString<1>,
    /// KEY-COMPRESSION
    pub key_compression: FixedString<1>,
    /// KEY-SPARSE
    pub key_sparse: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_282: FixedString<9>,
}
impl std::fmt::Display for KeyDefs {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}", self.key_count, self.key_offset, self.key_flags, self.key_compression, self.key_sparse, self._filler_282)
    }
}
impl From<&str> for KeyDefs {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for KeyDefs {
    fn from(_s: String) -> Self { Self::default() }
}
impl KeyDefs {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct KeyComp {
    /// KC-DESC
    pub kc_desc: FixedString<1>,
    /// KC-TYPE
    pub kc_type: FixedString<1>,
    /// KC-POS
    pub kc_pos: u32,
    /// KC-LEN
    pub kc_len: u32,
}
impl std::fmt::Display for KeyComp {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.kc_desc, self.kc_type, self.kc_pos, self.kc_len)
    }
}
impl From<&str> for KeyComp {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for KeyComp {
    fn from(_s: String) -> Self { Self::default() }
}
impl KeyComp {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// FD group: TSPFL-RECORD
    pub tspfl_record: FixedString<174>,
    /// FD group: TSPFL-REC
    pub tspfl_rec: FixedString<174>,
    /// FD group: CM-CUST-NUM
    pub cm_cust_num: FixedString<8>,
    /// FD: CM-CUST-PRE
    pub cm_cust_pre: FixedString<3>,
    /// FD: CM-CUST-NNN
    pub cm_cust_nnn: FixedString<5>,
    /// FD: CM-STATUS
    pub cm_status: FixedString<1>,
    /// FD: CM-COMPANY
    pub cm_company: FixedString<25>,
    /// FD: CM-ADDRESS-1
    pub cm_address_1: FixedString<25>,
    /// FD: CM-ADDRESS-2
    pub cm_address_2: FixedString<25>,
    /// FD: CM-ADDRESS-3
    pub cm_address_3: FixedString<25>,
    /// FD: CM-TELEPHONE
    pub cm_telephone: u64,
    /// FD: CM-DP-MGR
    pub cm_dp_mgr: FixedString<25>,
    /// FD: CM-MACHINE
    pub cm_machine: FixedString<8>,
    /// FD: CM-MEMORY
    pub cm_memory: FixedString<4>,
    /// FD: CM-DISK
    pub cm_disk: FixedString<8>,
    /// FD: CM-TAPE
    pub cm_tape: FixedString<8>,
    /// FD: CM-NO-TERMINALS
    pub cm_no_terminals: u32,
    /// CUST-STAT
    pub cust_stat: CustStat,
    /// STAT-1
    pub stat_1: u32,
    /// TEST-DATA
    pub test_data: TestData,
    /// DATA-CUST-NUM-TBL
    pub data_cust_num_tbl: DataCustNumTbl,
    /// DATA-COMPANY-TBL
    pub data_company_tbl: DataCompanyTbl,
    /// DATA-ADDRESS-1-TBL
    pub data_address_1_tbl: DataAddress1Tbl,
    /// DATA-ADDRESS-2-TBL
    pub data_address_2_tbl: DataAddress2Tbl,
    /// DATA-ADDRESS-3-TBL
    pub data_address_3_tbl: DataAddress3Tbl,
    /// DATA-TELEPHONE-TBL
    pub data_telephone_tbl: DataTelephoneTbl,
    /// DATA-DP-MGR-TBL
    pub data_dp_mgr_tbl: DataDpMgrTbl,
    /// DATA-MACHINE-TBL
    pub data_machine_tbl: DataMachineTbl,
    /// DATA-NO-TERMINALS-TBL
    pub data_no_terminals_tbl: DataNoTerminalsTbl,
    /// WORK-AREA
    pub work_area: WorkArea,
    /// REC-NUM
    pub rec_num: u32,
    /// SUB
    pub sub: FixedString<1>,
    /// TSPFL-KEY
    pub tspfl_key: FixedString<8>,
    /// KC-PTR
    pub kc_ptr: FixedString<1>,
    /// LINKAGE: TSP-FCD
    pub tsp_fcd: FixedString<1>,
    /// LINKAGE: KEY-DEF
    pub key_def: KeyDef,
    /// LINKAGE: KEY-COMP
    pub key_comp: KeyComp,
    /// LINKAGE: TSP-FILENAME
    pub tsp_filename: FixedString<256>,
    /// File status for TSPFILE
    pub _fs_tspfile: FileStatus,
    /// File handle for TSPFILE
    pub _fh_tspfile: CobolFile,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            tspfl_record: Default::default(),
            tspfl_rec: Default::default(),
            cm_cust_num: Default::default(),
            cm_cust_pre: Default::default(),
            cm_cust_nnn: Default::default(),
            cm_status: Default::default(),
            cm_company: Default::default(),
            cm_address_1: Default::default(),
            cm_address_2: Default::default(),
            cm_address_3: Default::default(),
            cm_telephone: Default::default(),
            cm_dp_mgr: Default::default(),
            cm_machine: Default::default(),
            cm_memory: Default::default(),
            cm_disk: Default::default(),
            cm_tape: Default::default(),
            cm_no_terminals: Default::default(),
            cust_stat: Default::default(),
            stat_1: Default::default(),
            test_data: Default::default(),
            data_cust_num_tbl: Default::default(),
            data_company_tbl: Default::default(),
            data_address_1_tbl: Default::default(),
            data_address_2_tbl: Default::default(),
            data_address_3_tbl: Default::default(),
            data_telephone_tbl: Default::default(),
            data_dp_mgr_tbl: Default::default(),
            data_machine_tbl: Default::default(),
            data_no_terminals_tbl: Default::default(),
            work_area: Default::default(),
            rec_num: Default::default(),
            sub: Default::default(),
            tspfl_key: Default::default(),
            kc_ptr: Default::default(),
            tsp_fcd: Default::default(),
            key_def: Default::default(),
            key_comp: Default::default(),
            tsp_filename: Default::default(),
            _fs_tspfile: FileStatus::Success,
            _fh_tspfile: CobolFile::Closed,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// MAINFILE
fn p_mainfile(state: &mut ProgramState) {
    println!();
    println!();
    // SKIP: unresolved display ref
    println!("{}{}{}", "File has ", state.key_def.key_nkeys, " keys.");
    println!("{}{}{}", "Key def  ", state.key_def.kdb_len, " bytes.");
    println!();
    // SKIP: unresolved display ref
    // SKIP: unresolved ref: state._unresolved_fcd_filename_address = &state._unresolved_out_file_name as *const _ as usize;
    // SKIP: unresolved ref: state._unresolved_fcd_name_length = std::mem::size_of_val(&state._unresolved_out_file_name) as i64;
    println!("{}", "*** Dump FCD before changes");
    p_dump_fcd(state);
    state.key_def.key_defs[((2 - 1) as usize).min(0)].key_flags = FixedString::from_str("64");
    state.key_def.key_defs[((3 - 1) as usize).min(0)].key_flags = FixedString::from_str("66");
    state.key_def.key_defs[((3 - 1) as usize).min(0)].key_sparse = "*".into();
    println!("{}", "*** Dump FCD after changes");
    p_dump_fcd(state);
    p_loadfile(state);
    p_listfile(state);
    { let _ = state._fh_tspfile.close();
        std::process::exit(0); }
}

/// DUMP-FCD
fn p_dump_fcd(state: &mut ProgramState) {
    // SKIP: unresolved ref
}

/// LOADFILE
fn p_loadfile(state: &mut ProgramState) {
    tspfile_open_output(state);
    println!();
    // SKIP: unresolved display ref
    if ({ let _s = format!("{}", state.cust_stat); _s.trim().to_string() } != "00".to_string()) && ({ let _s = format!("{}", state.cust_stat); _s.trim().to_string() } != "05".to_string()) {
        // SKIP: unresolved display ref
        { let _ = state._fh_tspfile.close();
            std::process::exit(0); }
    }
    p_1000_load_record(state);
}

/// MAX-SUB
fn p_max_sub(state: &mut ProgramState) {
    println!("{}", "Sample data file load complete.");
    tspfile_close(state);
}

/// 1000-LOAD-RECORD
fn p_1000_load_record(state: &mut ProgramState) {
    state.tspfl_record = Default::default();
    state.cm_cust_num = FixedString::copy_from(&state.test_data.data_cust_num[((state.work_area.sub.trimmed().parse::<i64>().unwrap_or(1) - 1) as usize).min(0)]);
    state.work_area.tspfl_key = FixedString::copy_from(&state.cm_cust_num);
    state.cm_company = FixedString::copy_from(&state.test_data.data_company[((state.work_area.sub.trimmed().parse::<i64>().unwrap_or(1) - 1) as usize).min(0)]);
    state.cm_address_1 = FixedString::copy_from(&state.test_data.data_address_1[((state.work_area.sub.trimmed().parse::<i64>().unwrap_or(1) - 1) as usize).min(0)]);
    state.cm_address_2 = FixedString::copy_from(&state.test_data.data_address_2[((state.work_area.sub.trimmed().parse::<i64>().unwrap_or(1) - 1) as usize).min(0)]);
    state.cm_address_3 = FixedString::copy_from(&state.test_data.data_address_3[((state.work_area.sub.trimmed().parse::<i64>().unwrap_or(1) - 1) as usize).min(0)]);
    state.cm_telephone = state.test_data.data_telephone[((state.work_area.sub.trimmed().parse::<i64>().unwrap_or(1) - 1) as usize).min(0)];
    state.cm_dp_mgr = FixedString::copy_from(&state.test_data.data_dp_mgr[((state.work_area.sub.trimmed().parse::<i64>().unwrap_or(1) - 1) as usize).min(0)]);
    state.cm_machine = FixedString::copy_from(&state.test_data.data_machine[((state.work_area.sub.trimmed().parse::<i64>().unwrap_or(1) - 1) as usize).min(0)]);
    state.cm_no_terminals = u32::from(state.test_data.data_no_terminals[((state.work_area.sub.trimmed().parse::<i64>().unwrap_or(1) - 1) as usize).min(0)]);
    if state.work_area.sub == "" {
        state.cm_disk = "8417".into();
        state.cm_tape = "1600 BPI".into();
        state.cm_memory = "1MEG".into();
    } else {
        state.cm_disk = "8470".into();
        state.cm_tape = "6250 BPI".into();
        state.cm_memory = "3MEG".into();
        if state.work_area.sub == "" {
            state.cm_disk = FixedString::from_str(&format!("{}", "*"));
            state.cm_tape = FixedString::from_str(&format!("{}", "*"));
            // SKIP: unresolved condition
        }
    }
}

/// LISTFILE
fn p_listfile(state: &mut ProgramState) {
    state.work_area.rec_num = 0;
    tspfile_open_input(state);
    println!();
    // SKIP: unresolved display ref
    if { let _s = format!("{}", state.cust_stat); _s.trim().to_string() } != "00".to_string() {
        println!("{}{}{}", "ERROR ", state.cust_stat, " OPENING INPUT FILE");
        if { let _s = format!("{}", { let _rm_s = state.cust_stat.to_string(); String::from(&_rm_s[(1 - 1) as usize..(1 - 1 + 1) as usize]) }); _s.trim().to_string() } == "9".to_string() {
            // SKIP: unresolved display ref
        }
        { let _ = state._fh_tspfile.close();
            std::process::exit(0); }
    }
    state.tspfl_record = Default::default();
    // START TSPFILE
    tspfile_read(state);
    if { let _s = format!("{}", state.cust_stat); _s.trim().to_string() } != "00".to_string() {
        println!("{}{}{}", "Error ", state.cust_stat, " on 1st read of file");
        if { let _s = format!("{}", { let _rm_s = state.cust_stat.to_string(); String::from(&_rm_s[(1 - 1) as usize..(1 - 1 + 1) as usize]) }); _s.trim().to_string() } == "9".to_string() {
            // SKIP: unresolved display ref
        }
        { let _ = state._fh_tspfile.close();
            std::process::exit(0); }
    }
    while !(({ let _s = format!("{}", state.cust_stat); _s.trim().to_string() } != "00".to_string()) || (&format!("{}", state.work_area.rec_num) > &"".to_string())) {
        // SKIP: unresolved ref
    }
    {
        let _bytes = b"99";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+2); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.cust_stat.stat_1 = _s.parse().unwrap_or_default(); }
    }
    state.work_area.rec_num += 1 as u32;
    if { let _s = format!("{}", state.cust_stat); _s.trim().to_string() } == "99".to_string() {
        println!("{}{}", "Hit End of File after ", state.work_area.rec_num);
    }
    println!("{}", "LIST SAMPLE FILE DESCENDING");
    state.work_area.rec_num = 0;
    state.tspfl_record = Default::default();
    // START TSPFILE
    tspfile_read(state);
    if { let _s = format!("{}", state.cust_stat); _s.trim().to_string() } != "00".to_string() {
        println!("{}{}{}", "Error ", state.cust_stat, " on 1st read of file");
        { let _ = state._fh_tspfile.close();
            std::process::exit(0); }
    }
    while !(({ let _s = format!("{}", state.cust_stat); _s.trim().to_string() } != "00".to_string()) || (&format!("{}", state.work_area.rec_num) > &"".to_string())) {
        // SKIP: unresolved ref
    }
    {
        let _bytes = b"99";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+2); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.cust_stat.stat_1 = _s.parse().unwrap_or_default(); }
    }
    state.work_area.rec_num += 1 as u32;
    if { let _s = format!("{}", state.cust_stat); _s.trim().to_string() } == "99".to_string() {
        println!("{}{}", "Hit End of File after ", state.work_area.rec_num);
    }
    println!("{}", "LIST SAMPLE FILE BY KEY3");
    state.work_area.rec_num = 0;
    state.tspfl_record = Default::default();
    // START TSPFILE
    tspfile_read(state);
    if ({ let _s = format!("{}", state.cust_stat); _s.trim().to_string() } != "00".to_string()) && ({ let _s = format!("{}", state.cust_stat); _s.trim().to_string() } != "02".to_string()) {
        println!("{}{}{}", "Error ", state.cust_stat, " on 1st read of file");
        { let _ = state._fh_tspfile.close();
            std::process::exit(0); }
    }
    // SKIP: unresolved condition
    println!("{}{}{}{}{}{}{}", "Key: ", state.cm_cust_num, " is ", state.cm_company, " Disk=", state.cm_disk, ".");
    tspfile_read(state);
    {
        let _bytes = b"99";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+2); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.cust_stat.stat_1 = _s.parse().unwrap_or_default(); }
    }
    state.work_area.rec_num += 1 as u32;
    if { let _s = format!("{}", state.cust_stat); _s.trim().to_string() } == "99".to_string() {
        println!("{}{}", "Hit End of File after ", state.work_area.rec_num);
    }
    tspfile_close(state);
}

/// STUB: p__unnamed
fn p__unnamed(state: &mut ProgramState) {
    // SKIP: unresolved ref
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT TSPFILE
fn tspfile_open_input(state: &mut ProgramState) {
    let path = std::env::var("TSPFILE").unwrap_or("tspfile.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_tspfile = handle; state._fs_tspfile = FileStatus::Success; }
        Err(_) => { state._fs_tspfile = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_tspfile); let _b = _s.as_bytes(); unsafe { let p = &mut state.cust_stat as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN OUTPUT TSPFILE
fn tspfile_open_output(state: &mut ProgramState) {
    let path = std::env::var("TSPFILE").unwrap_or("tspfile.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_tspfile = handle; state._fs_tspfile = FileStatus::Success; }
        Err(_) => { state._fs_tspfile = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_tspfile); let _b = _s.as_bytes(); unsafe { let p = &mut state.cust_stat as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// READ TSPFILE
fn tspfile_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_tspfile.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(177);
            if _len > 0 { let _end = _len.min(0+3); state.cm_cust_pre = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 3 { let _end = _len.min(3+5); state.cm_cust_nnn = FixedString::from(String::from_utf8_lossy(&_bytes[3.._end])); }
            if _len > 8 { let _end = _len.min(8+1); state.cm_status = FixedString::from(String::from_utf8_lossy(&_bytes[8.._end])); }
            if _len > 9 { let _end = _len.min(9+25); state.cm_company = FixedString::from(String::from_utf8_lossy(&_bytes[9.._end])); }
            if _len > 34 { let _end = _len.min(34+25); state.cm_address_1 = FixedString::from(String::from_utf8_lossy(&_bytes[34.._end])); }
            if _len > 59 { let _end = _len.min(59+25); state.cm_address_2 = FixedString::from(String::from_utf8_lossy(&_bytes[59.._end])); }
            if _len > 84 { let _end = _len.min(84+25); state.cm_address_3 = FixedString::from(String::from_utf8_lossy(&_bytes[84.._end])); }
            if _len > 109 { let _end = _len.min(109+10); let _s = String::from_utf8_lossy(&_bytes[109.._end]).trim().to_string(); state.cm_telephone = _s.parse().unwrap_or_default(); }
            if _len > 119 { let _end = _len.min(119+25); state.cm_dp_mgr = FixedString::from(String::from_utf8_lossy(&_bytes[119.._end])); }
            if _len > 144 { let _end = _len.min(144+8); state.cm_machine = FixedString::from(String::from_utf8_lossy(&_bytes[144.._end])); }
            if _len > 152 { let _end = _len.min(152+4); state.cm_memory = FixedString::from(String::from_utf8_lossy(&_bytes[152.._end])); }
            if _len > 156 { let _end = _len.min(156+8); state.cm_disk = FixedString::from(String::from_utf8_lossy(&_bytes[156.._end])); }
            if _len > 164 { let _end = _len.min(164+8); state.cm_tape = FixedString::from(String::from_utf8_lossy(&_bytes[164.._end])); }
            if _len > 172 { let _end = _len.min(172+5); let _s = String::from_utf8_lossy(&_bytes[172.._end]).trim().to_string(); state.cm_no_terminals = _s.parse().unwrap_or_default(); }
            state._fs_tspfile = FileStatus::Success;
    { let _s = format!("{}", state._fs_tspfile); let _b = _s.as_bytes(); unsafe { let p = &mut state.cust_stat as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(FileStatus::AtEnd) => {
            state._fs_tspfile = FileStatus::AtEnd;
    { let _s = format!("{}", state._fs_tspfile); let _b = _s.as_bytes(); unsafe { let p = &mut state.cust_stat as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(e) => {
            state._fs_tspfile = e.clone();
    { let _s = format!("{}", state._fs_tspfile); let _b = _s.as_bytes(); unsafe { let p = &mut state.cust_stat as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
    }
    Ok(())
}

/// WRITE to TSPFILE
fn tspfile_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 177];
    { let _src = state.cm_cust_pre.as_bytes(); let _end = (0+3).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.cm_cust_nnn.as_bytes(); let _end = (3+5).min(_buf.len()); let _cl = _src.len().min(_end-3); _buf[3..3+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.cm_status.as_bytes(); let _end = (8+1).min(_buf.len()); let _cl = _src.len().min(_end-8); _buf[8..8+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.cm_company.as_bytes(); let _end = (9+25).min(_buf.len()); let _cl = _src.len().min(_end-9); _buf[9..9+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.cm_address_1.as_bytes(); let _end = (34+25).min(_buf.len()); let _cl = _src.len().min(_end-34); _buf[34..34+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.cm_address_2.as_bytes(); let _end = (59+25).min(_buf.len()); let _cl = _src.len().min(_end-59); _buf[59..59+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.cm_address_3.as_bytes(); let _end = (84+25).min(_buf.len()); let _cl = _src.len().min(_end-84); _buf[84..84+_cl].copy_from_slice(&_src[.._cl]); }
    { let _s = format!("{:>width$}", state.cm_telephone, width = 10); let _b = _s.as_bytes(); let _cl = _b.len().min(10); _buf[109..109+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _src = state.cm_dp_mgr.as_bytes(); let _end = (119+25).min(_buf.len()); let _cl = _src.len().min(_end-119); _buf[119..119+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.cm_machine.as_bytes(); let _end = (144+8).min(_buf.len()); let _cl = _src.len().min(_end-144); _buf[144..144+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.cm_memory.as_bytes(); let _end = (152+4).min(_buf.len()); let _cl = _src.len().min(_end-152); _buf[152..152+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.cm_disk.as_bytes(); let _end = (156+8).min(_buf.len()); let _cl = _src.len().min(_end-156); _buf[156..156+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.cm_tape.as_bytes(); let _end = (164+8).min(_buf.len()); let _cl = _src.len().min(_end-164); _buf[164..164+_cl].copy_from_slice(&_src[.._cl]); }
    { let _s = format!("{:>width$}", state.cm_no_terminals, width = 5); let _b = _s.as_bytes(); let _cl = _b.len().min(5); _buf[172..172+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    match state._fh_tspfile.write_record(&_buf) {
        Ok(()) => state._fs_tspfile = FileStatus::Success,
        Err(e) => state._fs_tspfile = e,
    }
}

/// CLOSE TSPFILE
fn tspfile_close(state: &mut ProgramState) {
    match state._fh_tspfile.close() {
        Ok(()) => state._fs_tspfile = FileStatus::Success,
        Err(e) => state._fs_tspfile = e,
    }
    { let _s = format!("{}", state._fs_tspfile); let _b = _s.as_bytes(); unsafe { let p = &mut state.cust_stat as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN I-O TSPFILE
fn tspfile_open_io(state: &mut ProgramState) {
    let path = std::env::var("TSPFILE").unwrap_or("tspfile.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_tspfile = handle; state._fs_tspfile = FileStatus::Success; }
        Err(_) => { state._fs_tspfile = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_tspfile); let _b = _s.as_bytes(); unsafe { let p = &mut state.cust_stat as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN EXTEND TSPFILE
fn tspfile_open_extend(state: &mut ProgramState) {
    let path = std::env::var("TSPFILE").unwrap_or("tspfile.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_tspfile = handle; state._fs_tspfile = FileStatus::Success; }
        Err(_) => { state._fs_tspfile = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_tspfile); let _b = _s.as_bytes(); unsafe { let p = &mut state.cust_stat as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// WRITE TSPFL-RECORD
fn tspfl_record_write(state: &mut ProgramState) {
    // Write TSPFL-RECORD via tspfile_write (byte buffer)
    tspfile_write(state);
}

fn main() {
    let mut state = ProgramState::default();
    p_mainfile(&mut state);
}

