// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct TbwRecord {
    /// TBW-KEY
    pub tbw_key: FixedString<100>,
    /// TBW-ALT
    pub tbw_alt: TbwAlt,
    /// TBW-F1
    pub tbw_f1: FixedString<1>,
    /// TBW-F2
    pub tbw_f2: FixedString<255>,
}
impl std::fmt::Display for TbwRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.tbw_key, self.tbw_alt, self.tbw_f1, self.tbw_f2)
    }
}
impl From<&str> for TbwRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TbwRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl TbwRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TbwAlt {
    /// TBW-ALT-1
    pub tbw_alt_1: u32,
    /// TBW-ALT-2
    pub tbw_alt_2: u32,
}
impl std::fmt::Display for TbwAlt {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.tbw_alt_1, self.tbw_alt_2)
    }
}
impl From<&str> for TbwAlt {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TbwAlt {
    fn from(_s: String) -> Self { Self::default() }
}
impl TbwAlt {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Tbw {
    /// TBW-RECORD
    pub tbw_record: TbwRecord,
}
impl std::fmt::Display for Tbw {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.tbw_record)
    }
}
impl From<&str> for Tbw {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Tbw {
    fn from(_s: String) -> Self { Self::default() }
}
impl Tbw {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// FD group: TBW-RECORD
    pub tbw_record: FixedString<364>,
    /// FD: TBW-KEY
    pub tbw_key: FixedString<100>,
    /// FD group: TBW-ALT
    pub tbw_alt: FixedString<8>,
    /// FD: TBW-ALT-1
    pub tbw_alt_1: u32,
    /// FD: TBW-ALT-2
    pub tbw_alt_2: u32,
    /// FD: TBW-F1
    pub tbw_f1: FixedString<1>,
    /// FD: TBW-F2
    pub tbw_f2: FixedString<255>,
    /// FS-FILE-STATUS
    pub fs_file_status: FixedString<2>,
    /// END-TBW-RECORD
    pub end_tbw_record: u32,
    /// FLAG-TBW
    pub flag_tbw: FixedString<1>,
    /// PATH-TBW
    pub path_tbw: FixedString<255>,
    /// File status for TBW
    pub _fs_tbw: FileStatus,
    /// File handle for TBW
    pub _fh_tbw: CobolFile,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            tbw_record: Default::default(),
            tbw_key: Default::default(),
            tbw_alt: Default::default(),
            tbw_alt_1: Default::default(),
            tbw_alt_2: Default::default(),
            tbw_f1: Default::default(),
            tbw_f2: Default::default(),
            fs_file_status: Default::default(),
            end_tbw_record: Default::default(),
            flag_tbw: FixedString::low_values(),
            path_tbw: FixedString::new(),
            _fs_tbw: FileStatus::Success,
            _fh_tbw: CobolFile::Closed,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// PATH-TBW
fn p_path_tbw(state: &mut ProgramState) {
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    p_tbw_open_i_o(state);
    p_tbw_start_primary_greater(state);
    p_tbw_start_alternate(state);
    p_tbw_read_next(state);
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    state.tbw_key = FixedString::low_values();
    p_tbw_start_primary_greater(state);
    p_tbw_start_alternate(state);
    p_tbw_read_next(state);
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    p_tbw_read_next(state);
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    state.end_tbw_record = 122 as u32;
    state.tbw_key = "aaaaa".into();
    state.tbw_alt = Default::default();
    state.tbw_f1 = FixedString::spaces();
    state.tbw_f2 = FixedString::spaces();
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    state.tbw_alt = Default::default();
    p_tbw_start_alternate(state);
    p_tbw_read_next(state);
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    state.tbw_key = FixedString::low_values();
    p_tbw_start_primary_greater(state);
    p_tbw_start_alternate(state);
    p_tbw_read_next(state);
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    p_tbw_read_next(state);
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    p_tbw_read_next(state);
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    p_tbw_open_i_o(state);
    p_tbw_start_primary_greater(state);
    p_tbw_start_alternate(state);
    p_tbw_read_next(state);
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    state.tbw_key = FixedString::low_values();
    p_tbw_start_primary_greater(state);
    p_tbw_start_alternate(state);
    p_tbw_read_next(state);
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    p_tbw_read_next(state);
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    state.end_tbw_record = 163 as u32;
    state.tbw_key = "aaaaa".into();
    state.tbw_alt_1 = 1 as u32;
    state.tbw_alt_2 = 1 as u32;
    state.tbw_f1 = FixedString::spaces();
    state.tbw_f2 = FixedString::spaces();
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    state.end_tbw_record = 122 as u32;
    state.tbw_key = "aaaab".into();
    state.tbw_alt = Default::default();
    state.tbw_f1 = FixedString::spaces();
    state.tbw_f2 = FixedString::spaces();
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    state.tbw_alt = Default::default();
    p_tbw_start_alternate(state);
    p_tbw_read_next(state);
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    p_tbw_read_next(state);
    p_tbw_write(state);
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    state.tbw_alt = Default::default();
    p_tbw_rewrite(state);
    p_tbw_delete_file(state);
    p_tbw(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    p_tbw_close(state);
    p_tbw_close_exit(state);
    p_tbw_exit(state);
    println!("{}", "Test completed");
    { let _ = state._fh_tbw.close();
        std::process::exit(0); }
}

/// TBW-OPEN-I-O
fn p_tbw_open_i_o(state: &mut ProgramState) {
    if state.flag_tbw == "\u{FF}" {
        p_tbw_close(state);
        p_tbw_close_exit(state);
        println!("{}", "open");
        tbw_open_io(state);
        println!("{}", "open done");
        if state.fs_file_status.trimmed() != "" {
        }
    }
    state.flag_tbw = FixedString::high_values();
    p_tbw_exit(state); return;
}

/// TBW-START-PRIMARY-GREATER
fn p_tbw_start_primary_greater(state: &mut ProgramState) {
    println!("{}", "start > tbw-key");
    // START TBW
    println!("{}{}", "start > tbw-key ", state.fs_file_status);
    p_tbw_exit(state); return;
}

/// TBW-START-ALTERNATE
fn p_tbw_start_alternate(state: &mut ProgramState) {
    println!("{}", "start >= tbw-alt");
    // START TBW
    println!("{}{}", "start >= tbw-alt ", state.fs_file_status);
    p_tbw_exit(state); return;
}

/// TBW-READ-NEXT
fn p_tbw_read_next(state: &mut ProgramState) {
    println!("{}", "read next");
    tbw_read(state);
    println!("{}", "read next end");
    p_tbw_exit(state); return;
    println!("{}", "read next done");
    p_tbw_exit(state); return;
    println!("{}{}", "read next ", state.fs_file_status);
    p_tbw_exit(state); return;
}

/// TBW-WRITE
fn p_tbw_write(state: &mut ProgramState) {
    println!("{}", "write");
    tbw_record_write(state);
    println!("{}", "write inv");
    p_tbw_exit(state); return;
    println!("{}", "write done");
    p_tbw_exit(state); return;
    println!("{}{}", "write ", state.fs_file_status);
    p_tbw_exit(state); return;
}

/// TBW-REWRITE
fn p_tbw_rewrite(state: &mut ProgramState) {
    println!("{}", "rewrite");
    // REWRITE TBW-RECORD
    println!("{}{}", "rewrite inv ", state.fs_file_status);
    p_tbw_exit(state); return;
    println!("{}{}", "rewrite done ", state.fs_file_status);
    p_tbw_exit(state); return;
    println!("{}{}", "rewrite ", state.fs_file_status);
    p_tbw_exit(state); return;
}

/// TBW-DELETE-FILE
fn p_tbw_delete_file(state: &mut ProgramState) {
    if state.flag_tbw == "\u{FF}" {
        p_tbw_close(state);
        p_tbw_close_exit(state);
        state.fs_file_status = "xx".into();
        println!("{}", "delete file");
        // DELETE FILE
    }
}

/// TBW
fn p_tbw(state: &mut ProgramState) {
    println!("{}", "delete file done");
    p_tbw_exit(state); return;
}

/// TBW-CLOSE
fn p_tbw_close(state: &mut ProgramState) {
    if state.flag_tbw == "\u{FF}" {
        println!("{}", "close");
        tbw_close(state);
        println!("{}", "close done");
        state.flag_tbw = FixedString::low_values();
    }
}

/// TBW-CLOSE-EXIT
fn p_tbw_close_exit(state: &mut ProgramState) {
}

/// TBW-EXIT
fn p_tbw_exit(state: &mut ProgramState) {
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT TBW
fn tbw_open_input(state: &mut ProgramState) {
    let path = std::env::var("TBW").unwrap_or("tbw.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_tbw = handle; state._fs_tbw = FileStatus::Success; }
        Err(_) => { state._fs_tbw = FileStatus::Error("35".to_string()); }
    }
    state.fs_file_status = FixedString::from(format!("{}", state._fs_tbw));
}

/// OPEN OUTPUT TBW
fn tbw_open_output(state: &mut ProgramState) {
    let path = std::env::var("TBW").unwrap_or("tbw.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_tbw = handle; state._fs_tbw = FileStatus::Success; }
        Err(_) => { state._fs_tbw = FileStatus::Error("35".to_string()); }
    }
    state.fs_file_status = FixedString::from(format!("{}", state._fs_tbw));
}

/// READ TBW
fn tbw_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_tbw.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(362);
            if _len > 0 { let _end = _len.min(0+100); state.tbw_key = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 100 { let _end = _len.min(100+2); let _s = String::from_utf8_lossy(&_bytes[100.._end]).trim().to_string(); state.tbw_alt_1 = _s.parse().unwrap_or_default(); }
            if _len > 102 { let _end = _len.min(102+4); let _s = String::from_utf8_lossy(&_bytes[102.._end]).trim().to_string(); state.tbw_alt_2 = _s.parse().unwrap_or_default(); }
            if _len > 106 { let _end = _len.min(106+1); state.tbw_f1 = FixedString::from(String::from_utf8_lossy(&_bytes[106.._end])); }
            if _len > 107 { let _end = _len.min(107+255); state.tbw_f2 = FixedString::from(String::from_utf8_lossy(&_bytes[107.._end])); }
            state._fs_tbw = FileStatus::Success;
    state.fs_file_status = FixedString::from(format!("{}", state._fs_tbw));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_tbw = FileStatus::AtEnd;
    state.fs_file_status = FixedString::from(format!("{}", state._fs_tbw));
        }
        Err(e) => {
            state._fs_tbw = e.clone();
    state.fs_file_status = FixedString::from(format!("{}", state._fs_tbw));
        }
    }
    Ok(())
}

/// WRITE to TBW
fn tbw_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 362];
    { let _src = state.tbw_key.as_bytes(); let _end = (0+100).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    { let _s = format!("{:>width$}", state.tbw_alt_1, width = 2); let _b = _s.as_bytes(); let _cl = _b.len().min(2); _buf[100..100+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _s = format!("{:>width$}", state.tbw_alt_2, width = 4); let _b = _s.as_bytes(); let _cl = _b.len().min(4); _buf[102..102+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _src = state.tbw_f1.as_bytes(); let _end = (106+1).min(_buf.len()); let _cl = _src.len().min(_end-106); _buf[106..106+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.tbw_f2.as_bytes(); let _end = (107+255).min(_buf.len()); let _cl = _src.len().min(_end-107); _buf[107..107+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_tbw.write_record(&_buf) {
        Ok(()) => state._fs_tbw = FileStatus::Success,
        Err(e) => state._fs_tbw = e,
    }
}

/// CLOSE TBW
fn tbw_close(state: &mut ProgramState) {
    match state._fh_tbw.close() {
        Ok(()) => state._fs_tbw = FileStatus::Success,
        Err(e) => state._fs_tbw = e,
    }
    state.fs_file_status = FixedString::from(format!("{}", state._fs_tbw));
}

/// OPEN I-O TBW
fn tbw_open_io(state: &mut ProgramState) {
    let path = std::env::var("TBW").unwrap_or("tbw.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_tbw = handle; state._fs_tbw = FileStatus::Success; }
        Err(_) => { state._fs_tbw = FileStatus::Error("35".to_string()); }
    }
    state.fs_file_status = FixedString::from(format!("{}", state._fs_tbw));
}

/// OPEN EXTEND TBW
fn tbw_open_extend(state: &mut ProgramState) {
    let path = std::env::var("TBW").unwrap_or("tbw.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_tbw = handle; state._fs_tbw = FileStatus::Success; }
        Err(_) => { state._fs_tbw = FileStatus::Error("35".to_string()); }
    }
    state.fs_file_status = FixedString::from(format!("{}", state._fs_tbw));
}

/// WRITE TBW-RECORD
fn tbw_record_write(state: &mut ProgramState) {
    // Write TBW-RECORD via tbw_write (byte buffer)
    tbw_write(state);
}

fn main() {
    let mut state = ProgramState::default();
    p_path_tbw(&mut state);
}

