// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataRecord {
    /// DATA-LINE
    pub data_line: FixedString<80>,
}
impl std::fmt::Display for DataRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.data_line)
    }
}
impl From<&str> for DataRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct DataFile {
    /// DATA-RECORD
    pub data_record: DataRecord,
}
impl std::fmt::Display for DataFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.data_record)
    }
}
impl From<&str> for DataFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for DataFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl DataFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct MiniReport {
    /// REPORT-LINE
    pub report_line: FixedString<80>,
}
impl std::fmt::Display for MiniReport {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.report_line)
    }
}
impl From<&str> for MiniReport {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for MiniReport {
    fn from(_s: String) -> Self { Self::default() }
}
impl MiniReport {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ReportLineBlank {
    /// FILLER PIC FILLER
    pub _filler_30: FixedString<18>,
    /// FILLER PIC FILLER
    pub _filler_31: FixedString<5>,
    /// FILLER PIC FILLER
    pub _filler_32: FixedString<34>,
    /// FILLER PIC FILLER
    pub _filler_34: FixedString<5>,
    /// FILLER PIC FILLER
    pub _filler_35: FixedString<18>,
}
impl std::fmt::Display for ReportLineBlank {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}", self._filler_30, self._filler_31, self._filler_32, self._filler_34, self._filler_35)
    }
}
impl From<&str> for ReportLineBlank {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ReportLineBlank {
    fn from(_s: String) -> Self { Self::default() }
}
impl ReportLineBlank {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ReportLineData {
    /// BODY-TAG
    pub body_tag: u32,
    /// LINE-3
    pub line_3: FixedString<74>,
}
impl std::fmt::Display for ReportLineData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.body_tag, self.line_3)
    }
}
impl From<&str> for ReportLineData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ReportLineData {
    fn from(_s: String) -> Self { Self::default() }
}
impl ReportLineData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ReportLineHeader {
    /// FILLER PIC FILLER
    pub _filler_40: FixedString<6>,
    /// PAGE-NO
    pub page_no: u32,
    /// FILLER PIC FILLER
    pub _filler_42: FixedString<24>,
    /// FILLER PIC FILLER
    pub _filler_43: FixedString<5>,
    /// HEADER-TAG
    pub header_tag: u32,
}
impl std::fmt::Display for ReportLineHeader {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}", self._filler_40, self.page_no, self._filler_42, self._filler_43, self.header_tag)
    }
}
impl From<&str> for ReportLineHeader {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ReportLineHeader {
    fn from(_s: String) -> Self { Self::default() }
}
impl ReportLineHeader {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// FD group: DATA-RECORD
    pub data_record: FixedString<80>,
    /// FD: DATA-LINE
    pub data_line: FixedString<80>,
    /// FD: REPORT-LINE
    pub report_line: FixedString<80>,
    /// COMMAND-ARGUMENTS
    pub command_arguments: FixedString<1024>,
    /// FILE-NAME
    pub file_name: FixedString<160>,
    /// DATA-FILE-STATUS
    pub data_file_status: FixedString<2>,
    /// LC
    pub lc: u32,
    /// REPORT-LINE-BLANK
    pub report_line_blank: ReportLineBlank,
    /// REPORT-LINE-DATA
    pub report_line_data: ReportLineData,
    /// BODY-TAG
    pub body_tag: u32,
    /// LINE-3
    pub line_3: FixedString<74>,
    /// REPORT-LINE-HEADER
    pub report_line_header: ReportLineHeader,
    /// PAGE-NO
    pub page_no: u32,
    /// HEADER-TAG
    pub header_tag: u32,
    /// PAGE-COUNT
    pub page_count: u32,
    /// File status for DATA-FILE
    pub _fs_data_file: FileStatus,
    /// File handle for DATA-FILE
    pub _fh_data_file: CobolFile,
    /// File status for MINI-REPORT
    pub _fs_mini_report: FileStatus,
    /// File handle for MINI-REPORT
    pub _fh_mini_report: CobolFile,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            data_record: Default::default(),
            data_line: Default::default(),
            report_line: Default::default(),
            command_arguments: Default::default(),
            file_name: Default::default(),
            data_file_status: Default::default(),
            lc: Default::default(),
            report_line_blank: Default::default(),
            report_line_data: Default::default(),
            body_tag: Default::default(),
            line_3: Default::default(),
            report_line_header: Default::default(),
            page_no: Default::default(),
            header_tag: Default::default(),
            page_count: Default::default(),
            _fs_data_file: FileStatus::Success,
            _fh_data_file: CobolFile::Closed,
            _fs_mini_report: FileStatus::Success,
            _fh_mini_report: CobolFile::Closed,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// MAIN
fn p_main(state: &mut ProgramState) {
    data_file_open_input(state);
    match data_file_read(state) {
        Ok(()) => {
            // record read successfully
        }
        Err(FileStatus::AtEnd) => {
            println!("{}{}", "File open error: ", state._fs_data_file);
            { let _ = state._fh_data_file.close();
                let _ = state._fh_mini_report.close();
                std::process::exit(0); }
        }
        Err(_) => {
            // other file error
        }
    }
    mini_report_open_output(state);
    {
    let mut _bytes = vec![b' '; 80];
    state.report_line = FixedString::from(String::from_utf8_lossy(&_bytes));
    }
    report_line_write(state);
    state.page_count = 1 as u32;
    state.report_line_header.page_no = state.page_count as u32;
    {
    let mut _bytes = vec![b' '; 45];
    { let _s = format!("{:>width$}", state.report_line_header.page_no, width = 4); let _b = _s.as_bytes(); let _cl = _b.len().min(4); _bytes[6..6+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _s = format!("{:>width$}", state.report_line_header.header_tag, width = 6); let _b = _s.as_bytes(); let _cl = _b.len().min(6); _bytes[39..39+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    state.report_line = FixedString::from(String::from_utf8_lossy(&_bytes));
    }
    print!("\x0C"); // AFTER PAGE (form feed)
    report_line_write(state);
    while !(state.data_record == "\u{FF}") {
        p_readwrite_loop(state);
    }
    println!("{}{}", "Normal termination, ending status: ", state._fs_data_file);
    mini_report_close(state);
    data_file_close(state);
    { let _ = state._fh_data_file.close();
        let _ = state._fh_mini_report.close();
        std::process::exit(0); }
}

/// READWRITE-LOOP
fn p_readwrite_loop(state: &mut ProgramState) {
    {
        let _bytes = state.data_record.as_bytes();
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+6); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.report_line_data.body_tag = _s.parse().unwrap_or_default(); }
        if _len > 6 { let _end = _len.min(6+74); state.report_line_data.line_3 = FixedString::from(String::from_utf8_lossy(&_bytes[6.._end])); }
    }
    // SKIP: unresolved ref: state.report_line_data.body_tag = format!("{}", state._unresolved_linage_counter).trim().parse::<u32>().unwrap_or(0);
    {
    let mut _bytes = vec![b' '; 80];
    { let _s = format!("{:>width$}", state.report_line_data.body_tag, width = 6); let _b = _s.as_bytes(); let _cl = _b.len().min(6); _bytes[0..0+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _src = state.report_line_data.line_3.as_bytes(); let _end = (6+74).min(_bytes.len()); let _cl = _src.len().min(_end-6); _bytes[6..6+_cl].copy_from_slice(&_src[.._cl]); }
    state.report_line = FixedString::from(String::from_utf8_lossy(&_bytes));
    }
    report_line_write(state);
    state.page_count += 1 as u32;
    state.report_line_header.page_no = state.page_count as u32;
    // SKIP: unresolved ref: state.report_line_header.header_tag = format!("{}", state._unresolved_linage_counter).trim().parse::<u32>().unwrap_or(0);
    {
    let mut _bytes = vec![b' '; 45];
    { let _s = format!("{:>width$}", state.report_line_header.page_no, width = 4); let _b = _s.as_bytes(); let _cl = _b.len().min(4); _bytes[6..6+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _s = format!("{:>width$}", state.report_line_header.header_tag, width = 6); let _b = _s.as_bytes(); let _cl = _b.len().min(6); _bytes[39..39+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    state.report_line = FixedString::from(String::from_utf8_lossy(&_bytes));
    }
    print!("\x0C"); // AFTER PAGE (form feed)
    report_line_write(state);
    match data_file_read(state) {
        Ok(()) => {
            // record read successfully
        }
        Err(FileStatus::AtEnd) => {
            state.data_record = "1".into();
        }
        Err(_) => {
            // other file error
        }
    }
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT DATA-FILE
fn data_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("DATA_FILE").unwrap_or("data_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_data_file = handle; state._fs_data_file = FileStatus::Success; }
        Err(_) => { state._fs_data_file = FileStatus::Error("35".to_string()); }
    }
    state.data_file_status = FixedString::from(format!("{}", state._fs_data_file));
}

/// OPEN OUTPUT DATA-FILE
fn data_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("DATA_FILE").unwrap_or("data_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_data_file = handle; state._fs_data_file = FileStatus::Success; }
        Err(_) => { state._fs_data_file = FileStatus::Error("35".to_string()); }
    }
    state.data_file_status = FixedString::from(format!("{}", state._fs_data_file));
}

/// READ DATA-FILE
fn data_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_data_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(80);
            if _len > 0 { let _end = _len.min(0+80); state.data_line = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_data_file = FileStatus::Success;
    state.data_file_status = FixedString::from(format!("{}", state._fs_data_file));
        }
        Err(FileStatus::AtEnd) => {
            state._fs_data_file = FileStatus::AtEnd;
    state.data_file_status = FixedString::from(format!("{}", state._fs_data_file));
        }
        Err(e) => {
            state._fs_data_file = e.clone();
    state.data_file_status = FixedString::from(format!("{}", state._fs_data_file));
        }
    }
    Ok(())
}

/// WRITE to DATA-FILE
fn data_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 80];
    { let _src = state.data_line.as_bytes(); let _end = (0+80).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_data_file.write_record(&_buf) {
        Ok(()) => state._fs_data_file = FileStatus::Success,
        Err(e) => state._fs_data_file = e,
    }
}

/// CLOSE DATA-FILE
fn data_file_close(state: &mut ProgramState) {
    match state._fh_data_file.close() {
        Ok(()) => state._fs_data_file = FileStatus::Success,
        Err(e) => state._fs_data_file = e,
    }
    state.data_file_status = FixedString::from(format!("{}", state._fs_data_file));
}

/// OPEN I-O DATA-FILE
fn data_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("DATA_FILE").unwrap_or("data_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_data_file = handle; state._fs_data_file = FileStatus::Success; }
        Err(_) => { state._fs_data_file = FileStatus::Error("35".to_string()); }
    }
    state.data_file_status = FixedString::from(format!("{}", state._fs_data_file));
}

/// OPEN EXTEND DATA-FILE
fn data_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("DATA_FILE").unwrap_or("data_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_data_file = handle; state._fs_data_file = FileStatus::Success; }
        Err(_) => { state._fs_data_file = FileStatus::Error("35".to_string()); }
    }
    state.data_file_status = FixedString::from(format!("{}", state._fs_data_file));
}

/// OPEN INPUT MINI-REPORT
fn mini_report_open_input(state: &mut ProgramState) {
    let path = std::env::var("MINI_REPORT").unwrap_or("mini_report.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_mini_report = handle; state._fs_mini_report = FileStatus::Success; }
        Err(_) => { state._fs_mini_report = FileStatus::Error("35".to_string()); }
    }
}

/// OPEN OUTPUT MINI-REPORT
fn mini_report_open_output(state: &mut ProgramState) {
    let path = std::env::var("MINI_REPORT").unwrap_or("mini_report.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_mini_report = handle; state._fs_mini_report = FileStatus::Success; }
        Err(_) => { state._fs_mini_report = FileStatus::Error("35".to_string()); }
    }
}

/// READ MINI-REPORT
fn mini_report_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_mini_report.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(80);
            if _len > 0 { let _end = _len.min(0+80); state.report_line = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_mini_report = FileStatus::Success;
        }
        Err(FileStatus::AtEnd) => {
            state._fs_mini_report = FileStatus::AtEnd;
        }
        Err(e) => {
            state._fs_mini_report = e.clone();
        }
    }
    Ok(())
}

/// WRITE to MINI-REPORT
fn mini_report_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 80];
    { let _src = state.report_line.as_bytes(); let _end = (0+80).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_mini_report.write_record(&_buf) {
        Ok(()) => state._fs_mini_report = FileStatus::Success,
        Err(e) => state._fs_mini_report = e,
    }
}

/// CLOSE MINI-REPORT
fn mini_report_close(state: &mut ProgramState) {
    match state._fh_mini_report.close() {
        Ok(()) => state._fs_mini_report = FileStatus::Success,
        Err(e) => state._fs_mini_report = e,
    }
}

/// OPEN I-O MINI-REPORT
fn mini_report_open_io(state: &mut ProgramState) {
    let path = std::env::var("MINI_REPORT").unwrap_or("mini_report.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_mini_report = handle; state._fs_mini_report = FileStatus::Success; }
        Err(_) => { state._fs_mini_report = FileStatus::Error("35".to_string()); }
    }
}

/// OPEN EXTEND MINI-REPORT
fn mini_report_open_extend(state: &mut ProgramState) {
    let path = std::env::var("MINI_REPORT").unwrap_or("mini_report.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_mini_report = handle; state._fs_mini_report = FileStatus::Success; }
        Err(_) => { state._fs_mini_report = FileStatus::Error("35".to_string()); }
    }
}

/// WRITE REPORT-LINE
fn report_line_write(state: &mut ProgramState) {
    // Write REPORT-LINE via mini_report_write (byte buffer)
    mini_report_write(state);
}

fn main() {
    let mut state = ProgramState::default();
    p_main(&mut state);
}

