// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;


#[derive(Debug, Clone)]
pub struct ProgramState {
    /// TEST-NO
    pub test_no: u32,
    /// CHAINING-PARAM
    pub chaining_param: FixedString<20>,
    /// CHAINING-PARAM-2
    pub chaining_param_2: FixedString<20>,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            test_no: 0,
            chaining_param: Default::default(),
            chaining_param_2: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
        }
    }
}

/// CHAINING-PARAM-2
fn p_chaining_param_2(state: &mut ProgramState) {
}

/// MAIN
fn p_main(state: &mut ProgramState) {
    match state.chaining_param.as_str() {
        FixedString::spaces() => {}
        "1" => {}
        "\"1\"" => {}
        "a v" => {}
        "\"a v\"" => {}
        "a" => {}
        "start" => {}
        _ => {
            println!("{}{}{}{}{}{}", "called with unexpected -", 0, "?MISSING?", state.chaining_param, "?MISSING?", "-");
        }
    }
    { std::process::exit(0); }
}

/// CALLME
fn p_callme(state: &mut ProgramState) {
    state.test_no += 1;
    println!("{}{}{}", "Test #", state.test_no, ":");
    println!("{}{}{}{}{}{}", "  CALL 'SYSTEM' with ", 0, "?MISSING?", state.chaining_param, "?MISSING?", ":");
    {
        let mut _p1 = 0.clone();
        let mut _p2 = "?MISSING?".into().clone();
        let mut _p3 = state.chaining_param.clone();
        let mut _p4 = "?MISSING?".into().clone();
        system(&mut _p1, &mut _p2, &mut _p3, &mut _p4);
        0 = _p1;
        "?MISSING?".into() = _p2;
        state.chaining_param = _p3;
        "?MISSING?".into() = _p4;
    }
    println!("{}{}", "  --> return of the given CALL 'SYSTEM': ", state.return_code);
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// External: CALL 'SYSTEM'
fn system(_param1: &mut impl std::fmt::Debug, _param2: &mut impl std::fmt::Debug, _param3: &mut impl std::fmt::Debug, _param4: &mut impl std::fmt::Debug) {
    todo!("External subroutine 'SYSTEM' not yet linked — implement or link the SYSTEM module")
}

fn main() {
    let mut state = ProgramState::default();
    p_chaining_param_2(&mut state);
}

