// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;


#[derive(Debug, Clone, Default)]
pub struct WData {
    /// GA
    pub ga: Ga,
    /// GB
    pub gb: Gb,
    /// GC
    pub gc: Gc,
}

#[derive(Debug, Clone, Default)]
pub struct Ga {
    /// X
    pub x: FixedString<1>,
    /// YZ
    pub yz: FixedString<2>,
    /// X1
    pub x1: FixedString<6>,
}

#[derive(Debug, Clone, Default)]
pub struct Gb {
    /// X1
    pub x1: FixedString<6>,
    /// X
    pub x: FixedString<1>,
}

#[derive(Debug, Clone, Default)]
pub struct Gc {
    /// X1
    pub x1: FixedString<5>,
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// W-DATA
    pub w_data: WData,
    /// LGX
    pub lgx: f32,
    /// CNT
    pub cnt: f32,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            w_data: Default::default(),
            lgx: "",
            cnt: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
        }
    }
}

/// MAIN
fn p_main(state: &mut ProgramState) {
    state.w_data.gc.x1 = "AAAAA".into();
    state.of = "AAAAA".into();
    {
        let _bytes = b"AAAAA";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+1); state.w_data.gb.x = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
        if _len > 1 { let _end = _len.min(1+2); state.w_data.ga.yz = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        if _len > 3 { let _end = _len.min(3+6); state.w_data.gc.x1 = FixedString::from(String::from_utf8_lossy(&_bytes[3.._end])); }
    }
    state.w_data.gc.x1 = "BBBBB".into();
    state.of = "BBBBB".into();
    {
        let _bytes = b"BBBBB";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+6); state.w_data.gc.x1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
        if _len > 6 { let _end = _len.min(6+1); state.w_data.gb.x = FixedString::from(String::from_utf8_lossy(&_bytes[6.._end])); }
    }
    if state.x1 {
    }
    println!("{}", "GLOBAL INITIALIZATION FAILED");
    p_show_vars(state);
    state.lgx = 2;
    if state.w_data.as_str() != "XYZAAAAABBBBB +++++" {
        println!("{}", "GROUP COMPARISON FAILED");
        println!("{}", state.w_data.ga);
        p_show_vars(state);
    }
    {
        let mut _bytes = vec![b' '; 5];
        { let _src = state.w_data.gc.x1.as_bytes(); let _end = (0+5).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+1); state.w_data.gb.x = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
        if _len > 1 { let _end = _len.min(1+2); state.w_data.ga.yz = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        if _len > 3 { let _end = _len.min(3+6); state.w_data.gc.x1 = FixedString::from(String::from_utf8_lossy(&_bytes[3.._end])); }
    }
    if state.x1 {
    }
    println!("{}", "MOVE CORRESPONDING GC TO GA: FAILED");
    p_show_vars(state);
    {
        let mut _bytes = vec![b' '; 7];
        { let _src = state.w_data.gc.x1.as_bytes(); let _end = (0+6).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
        { let _src = state.w_data.gb.x.as_bytes(); let _end = (6+1).min(_bytes.len()); let _cl = _src.len().min(_end-6); _bytes[6..6+_cl].copy_from_slice(&_src[.._cl]); }
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+5); state.w_data.gc.x1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
    }
    {
    }
    if state.x1 {
    }
    println!("{}", "MOVE CORRESPONDING GB TO GC: FAILED");
    p_show_vars(state);
    {
        let mut _bytes = vec![b' '; 9];
        { let _src = state.w_data.gb.x.as_bytes(); let _end = (0+1).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
        { let _src = state.w_data.ga.yz.as_bytes(); let _end = (1+2).min(_bytes.len()); let _cl = _src.len().min(_end-1); _bytes[1..1+_cl].copy_from_slice(&_src[.._cl]); }
        { let _src = state.w_data.gc.x1.as_bytes(); let _end = (3+6).min(_bytes.len()); let _cl = _src.len().min(_end-3); _bytes[3..3+_cl].copy_from_slice(&_src[.._cl]); }
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+6); state.w_data.gc.x1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
        if _len > 6 { let _end = _len.min(6+1); state.w_data.gb.x = FixedString::from(String::from_utf8_lossy(&_bytes[6.._end])); }
    }
    state.cnt = 0;
    {
    }
    state.lgx = 5;
    if state.x1 {
    }
    println!("{}", "MOVE CORRESPONDING GA TO GB: FAILED");
    p_show_vars(state);
    { std::process::exit(0); }
}

/// SHOW-VARS
fn p_show_vars(state: &mut ProgramState) {
    println!("{}{}", "LGX: ", state.lgx);
    println!("{}{}{}", "W-DATA: *", state.w_data, "*");
    println!("{}{}", "CNT: ", state.cnt);
}

fn main() {
    let mut state = ProgramState::default();
    p_main(&mut state);
}

