// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;


#[derive(Debug, Clone, Default)]
pub struct File0 {
    /// F0REC
    pub f0rec: FixedString<80>,
}

#[derive(Debug, Clone, Default)]
pub struct FileOpt {
    /// FOREC
    pub forec: FixedString<80>,
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// FD: F0REC
    pub f0rec: FixedString<80>,
    /// FD: FOREC
    pub forec: FixedString<80>,
    /// WSFS
    pub wsfs: FixedString<2>,
    /// File status for FILE0
    pub file0_status: FileStatus,
    /// File handle for FILE0
    pub file0_handle: CobolFile,
    /// File status for FILE-OPT
    pub file_opt_status: FileStatus,
    /// File handle for FILE-OPT
    pub file_opt_handle: CobolFile,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            f0rec: Default::default(),
            forec: Default::default(),
            wsfs: Default::default(),
            file0_status: FileStatus::Success,
            file0_handle: CobolFile::Closed,
            file_opt_status: FileStatus::Success,
            file_opt_handle: CobolFile::Closed,
            return_code: 0,
            tally: 0,
            sort_return: 0,
        }
    }
}

/// WSFS
fn p_wsfs(state: &mut ProgramState) {
    state.?missing? = state.all;
    state.to = state.all;
    state.forec = state.all;
    forec_write(state);
    if state.wsfs != "00" {
        println!("{}{}", "STATUS WRITE A:", state.wsfs);
        file_opt_close(state);
        if state.wsfs != "00" {
            println!("{}{}", "STATUS CLOSE:", state.wsfs);
            file0_open_extend(state);
            if state.wsfs != "00" {
                println!("{}{}", "STATUS EXTEND, empty file:", state.wsfs);
                state.?missing? = state.all;
                state.to = state.all;
                state.f0rec = state.all;
                f0rec_write(state);
                if state.wsfs != "00" {
                    println!("{}{}", "STATUS WRITE B:", state.wsfs);
                    file0_close(state);
                    ?missing?_close(state);
                    file_opt_open_input(state);
                    if state.wsfs != "00" {
                        println!("{}{}", "STATUS INPUT:", state.wsfs);
                        file_opt_read(state);
                    } else {
                        if state.wsfs != "00" {
                            println!("{}{}", "STATUS READ A:", state.wsfs);
                            file_opt_read(state);
                        } else {
                            if state.wsfs != "00" {
                                println!("{}{}", "STATUS READ B:", state.wsfs);
                                file_opt_close(state);
                                ?missing?_close(state);
                                { let _ = state.file0_handle.close();
                                    let _ = state.file_opt_handle.close();
                                    std::process::exit(0); }
                            }
                        }
                    }
                }
            }
        }
    }
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT FILE0
fn file0_open_input(state: &mut ProgramState) {
    let path = std::env::var("FILE0").unwrap_or("file0.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state.file0_handle = handle; state.file0_status = FileStatus::Success; }
        Err(_) => { state.file0_status = FileStatus::Error("35".to_string()); }
    }
    state.wsfs = match &state.file0_status { FileStatus::Success => FixedString::from("00"), FileStatus::AtEnd => FixedString::from("10"), FileStatus::Error(c) => FixedString::from(c.as_str()), };
}

/// OPEN OUTPUT FILE0
fn file0_open_output(state: &mut ProgramState) {
    let path = std::env::var("FILE0").unwrap_or("file0.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state.file0_handle = handle; state.file0_status = FileStatus::Success; }
        Err(_) => { state.file0_status = FileStatus::Error("35".to_string()); }
    }
    state.wsfs = match &state.file0_status { FileStatus::Success => FixedString::from("00"), FileStatus::AtEnd => FixedString::from("10"), FileStatus::Error(c) => FixedString::from(c.as_str()), };
}

/// READ FILE0
fn file0_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state.file0_handle.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(80);
            if _len > 0 { let _end = _len.min(0+80); state.f0rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state.file0_status = FileStatus::Success;
    state.wsfs = match &state.file0_status { FileStatus::Success => FixedString::from("00"), FileStatus::AtEnd => FixedString::from("10"), FileStatus::Error(c) => FixedString::from(c.as_str()), };
        }
        Err(FileStatus::AtEnd) => {
            state.file0_status = FileStatus::AtEnd;
    state.wsfs = match &state.file0_status { FileStatus::Success => FixedString::from("00"), FileStatus::AtEnd => FixedString::from("10"), FileStatus::Error(c) => FixedString::from(c.as_str()), };
        }
        Err(e) => {
            state.file0_status = e.clone();
    state.wsfs = match &state.file0_status { FileStatus::Success => FixedString::from("00"), FileStatus::AtEnd => FixedString::from("10"), FileStatus::Error(c) => FixedString::from(c.as_str()), };
        }
    }
    Ok(())
}

/// WRITE to FILE0
fn file0_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 80];
    { let _src = state.f0rec.as_bytes(); let _end = (0+80).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state.file0_handle.write_record(&_buf) {
        Ok(()) => state.file0_status = FileStatus::Success,
        Err(e) => state.file0_status = e,
    }
}

/// CLOSE FILE0
fn file0_close(state: &mut ProgramState) {
    match state.file0_handle.close() {
        Ok(()) => state.file0_status = FileStatus::Success,
        Err(e) => state.file0_status = e,
    }
    state.wsfs = match &state.file0_status { FileStatus::Success => FixedString::from("00"), FileStatus::AtEnd => FixedString::from("10"), FileStatus::Error(c) => FixedString::from(c.as_str()), };
}

/// OPEN INPUT FILE-OPT
fn file_opt_open_input(state: &mut ProgramState) {
    let path = std::env::var("FILE_OPT").unwrap_or("file_opt.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state.file_opt_handle = handle; state.file_opt_status = FileStatus::Success; }
        Err(_) => { state.file_opt_status = FileStatus::Error("35".to_string()); }
    }
    state.wsfs = match &state.file_opt_status { FileStatus::Success => FixedString::from("00"), FileStatus::AtEnd => FixedString::from("10"), FileStatus::Error(c) => FixedString::from(c.as_str()), };
}

/// OPEN OUTPUT FILE-OPT
fn file_opt_open_output(state: &mut ProgramState) {
    let path = std::env::var("FILE_OPT").unwrap_or("file_opt.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state.file_opt_handle = handle; state.file_opt_status = FileStatus::Success; }
        Err(_) => { state.file_opt_status = FileStatus::Error("35".to_string()); }
    }
    state.wsfs = match &state.file_opt_status { FileStatus::Success => FixedString::from("00"), FileStatus::AtEnd => FixedString::from("10"), FileStatus::Error(c) => FixedString::from(c.as_str()), };
}

/// READ FILE-OPT
fn file_opt_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state.file_opt_handle.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(80);
            if _len > 0 { let _end = _len.min(0+80); state.forec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state.file_opt_status = FileStatus::Success;
    state.wsfs = match &state.file_opt_status { FileStatus::Success => FixedString::from("00"), FileStatus::AtEnd => FixedString::from("10"), FileStatus::Error(c) => FixedString::from(c.as_str()), };
        }
        Err(FileStatus::AtEnd) => {
            state.file_opt_status = FileStatus::AtEnd;
    state.wsfs = match &state.file_opt_status { FileStatus::Success => FixedString::from("00"), FileStatus::AtEnd => FixedString::from("10"), FileStatus::Error(c) => FixedString::from(c.as_str()), };
        }
        Err(e) => {
            state.file_opt_status = e.clone();
    state.wsfs = match &state.file_opt_status { FileStatus::Success => FixedString::from("00"), FileStatus::AtEnd => FixedString::from("10"), FileStatus::Error(c) => FixedString::from(c.as_str()), };
        }
    }
    Ok(())
}

/// WRITE to FILE-OPT
fn file_opt_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 80];
    { let _src = state.forec.as_bytes(); let _end = (0+80).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state.file_opt_handle.write_record(&_buf) {
        Ok(()) => state.file_opt_status = FileStatus::Success,
        Err(e) => state.file_opt_status = e,
    }
}

/// CLOSE FILE-OPT
fn file_opt_close(state: &mut ProgramState) {
    match state.file_opt_handle.close() {
        Ok(()) => state.file_opt_status = FileStatus::Success,
        Err(e) => state.file_opt_status = e,
    }
    state.wsfs = match &state.file_opt_status { FileStatus::Success => FixedString::from("00"), FileStatus::AtEnd => FixedString::from("10"), FileStatus::Error(c) => FixedString::from(c.as_str()), };
}

/// WRITE F0REC
fn f0rec_write(state: &mut ProgramState) {
    // Write F0REC via file0_write (byte buffer)
    file0_write(state);
}

/// WRITE FOREC
fn forec_write(state: &mut ProgramState) {
    // Write FOREC via file_opt_write (byte buffer)
    file_opt_write(state);
}

fn main() {
    let mut state = ProgramState::default();
    p_wsfs(&mut state);
}

