// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use cobol_runtime::chrono_shim::Local;
use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;


#[derive(Debug, Clone, Default)]
pub struct File1Rec {
    /// FILE1-KEY
    pub file1_key: FixedString<1>,
}

#[derive(Debug, Clone, Default)]
pub struct File1 {
    /// FILE1-REC
    pub file1_rec: File1Rec,
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// FD group: FILE1-REC
    pub file1_rec: FixedString<1>,
    /// FD: FILE1-KEY
    pub file1_key: FixedString<1>,
    /// FS
    pub fs: FixedString<2>,
    /// OS-CHECK
    pub os_check: FixedString<7>,
    /// File status for FILE1
    pub file1_status: FileStatus,
    /// File handle for FILE1
    pub file1_handle: CobolFile,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            file1_rec: Default::default(),
            file1_key: Default::default(),
            fs: Default::default(),
            os_check: Default::default(),
            file1_status: FileStatus::Success,
            file1_handle: CobolFile::Closed,
            return_code: 0,
            tally: 0,
            sort_return: 0,
        }
    }
}

/// FILE1
fn p_file1(state: &mut ProgramState) {
    file1_close(state);
    file1_open_input(state);
    with_open_input(state);
    lock_open_input(state);
    // ACCEPT OS-CHECK FROM ENVIRONMENT
    if state.os_check == FixedString::spaces() {
        // ACCEPT OS-CHECK FROM ENVIRONMENT
    }
    if state.os_check == FixedString::spaces() {
        // ACCEPT OS-CHECK FROM ENVIRONMENT
    }
    {
        inspect_converting(state.os_check.as_bytes_mut(), b"werfdosin", b"WERFDOSIN", None, None);
    }
    if () {
        {
            let mut _p1 = state.callee_wdos.clone();
            system(&mut _p1);
            state.callee_wdos = _p1;
        }
    } else {
        {
            let mut _p1 = state.callee.clone();
            system(&mut _p1);
            state.callee = _p1;
        }
        file1_close(state);
        { let _ = state.file1_handle.close();
            std::process::exit(0); }
    }
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT FILE1
fn file1_open_input(state: &mut ProgramState) {
    let path = std::env::var("FILE1").unwrap_or("file1.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state.file1_handle = handle; state.file1_status = FileStatus::Success; }
        Err(_) => { state.file1_status = FileStatus::Error("35".to_string()); }
    }
}

/// OPEN OUTPUT FILE1
fn file1_open_output(state: &mut ProgramState) {
    let path = std::env::var("FILE1").unwrap_or("file1.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state.file1_handle = handle; state.file1_status = FileStatus::Success; }
        Err(_) => { state.file1_status = FileStatus::Error("35".to_string()); }
    }
}

/// READ FILE1
fn file1_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state.file1_handle.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(1);
            if _len > 0 { let _end = _len.min(0+1); state.file1_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 0 { let _end = _len.min(0+1); state.file1_key = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state.file1_status = FileStatus::Success;
        }
        Err(FileStatus::AtEnd) => {
            state.file1_status = FileStatus::AtEnd;
        }
        Err(e) => {
            state.file1_status = e.clone();
        }
    }
    Ok(())
}

/// WRITE to FILE1
fn file1_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 1];
    { let _src = state.file1_key.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state.file1_handle.write_record(&_buf) {
        Ok(()) => state.file1_status = FileStatus::Success,
        Err(e) => state.file1_status = e,
    }
}

/// CLOSE FILE1
fn file1_close(state: &mut ProgramState) {
    match state.file1_handle.close() {
        Ok(()) => state.file1_status = FileStatus::Success,
        Err(e) => state.file1_status = e,
    }
}

/// External: CALL 'SYSTEM'
fn system(_param1: &mut impl std::fmt::Debug) {
    todo!("External subroutine 'SYSTEM' not yet linked — implement or link the SYSTEM module")
}

fn main() {
    let mut state = ProgramState::default();
    p_file1(&mut state);
}

