// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;


#[derive(Debug, Clone, Default)]
pub struct File1Rec {
    /// FILE1-KEY
    pub file1_key: u32,
    /// FILE1-DATA
    pub file1_data: FixedString<10>,
}

#[derive(Debug, Clone, Default)]
pub struct File1 {
    /// FILE1-REC
    pub file1_rec: File1Rec,
}

#[derive(Debug, Clone, Default)]
pub struct 1Values {
    /// FILLER PIC FILLER
    pub _filler_16: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_17: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_18: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_19: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_20: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_21: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_22: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_23: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_24: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_25: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_26: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_27: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_28: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_29: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_30: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_31: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_32: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_33: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_34: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_35: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_36: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_37: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_38: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_39: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_40: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_41: FixedString<14>,
}

#[derive(Debug, Clone, Default)]
pub struct Filler42 {
    /// 1-RECORD
    pub p_1_record: [1Record; 26],
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// FD group: FILE1-REC
    pub file1_rec: FixedString<14>,
    /// FD: FILE1-KEY
    pub file1_key: u32,
    /// FD: FILE1-DATA
    pub file1_data: FixedString<10>,
    /// W-EOF
    pub w_eof: u32,
    /// 1-VALUES
    pub p_1_values: 1Values,
    /// FILLER
    pub _filler_42: Filler42,
    /// File status for FILE1
    pub file1_status: FileStatus,
    /// File handle for FILE1
    pub file1_handle: CobolFile,
    /// INDEXED BY IX-1
    pub ix_1: usize,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            file1_rec: Default::default(),
            file1_key: Default::default(),
            file1_data: Default::default(),
            w_eof: 0,
            p_1_values: Default::default(),
            _filler_42: Default::default(),
            file1_status: FileStatus::Success,
            file1_handle: CobolFile::Closed,
            ix_1: 1,
            return_code: 0,
            tally: 0,
            sort_return: 0,
        }
    }
}

/// A01-MAIN
fn p_a01_main(state: &mut ProgramState) {
    // // SORT FILE1 ON ASC FILE1-KEY
    { let _ = state.file1_handle.close();
        std::process::exit(0); }
}

/// A02-RELEASE-TO-SORT
fn p_a02_release_to_sort(state: &mut ProgramState) {
    state.ix_1 = 1;
    while !(state.ix_1 > 26) {
        state.file1_rec = state.filler.p_1_record;  // RELEASE FROM
        state.ix_1 += 2;
    }
    state.ix_1 = 2;
    while !(state.ix_1 > 26) {
        state.file1_rec = state.filler.p_1_record;  // RELEASE FROM
        state.ix_1 += 2;
    }
}

/// A03-RETURN-FROM-SORT
fn p_a03_return_from_sort(state: &mut ProgramState) {
    state.ix_1 = 1;
    while !(state.?) {
    
        state.ix_1 += 1;
    }
    // // RETURN FILE1 (AT END handler present)
    state.w_eof = 1;
    if state.? {
    }
    println!("{}", "FAILED: unexpected eof");
    // // RETURN FILE1 (AT END handler present)
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT FILE1
fn file1_open_input(state: &mut ProgramState) {
    let path = std::env::var("FILE1").unwrap_or("file1.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state.file1_handle = handle; state.file1_status = FileStatus::Success; }
        Err(_) => { state.file1_status = FileStatus::Error("35".to_string()); }
    }
}

/// OPEN OUTPUT FILE1
fn file1_open_output(state: &mut ProgramState) {
    let path = std::env::var("FILE1").unwrap_or("file1.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state.file1_handle = handle; state.file1_status = FileStatus::Success; }
        Err(_) => { state.file1_status = FileStatus::Error("35".to_string()); }
    }
}

/// READ FILE1
fn file1_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state.file1_handle.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(14);
            if _len > 0 { let _end = _len.min(0+14); state.file1_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 0 { let _end = _len.min(0+4); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.file1_key = _s.parse().unwrap_or_default(); }
            if _len > 4 { let _end = _len.min(4+10); state.file1_data = FixedString::from(String::from_utf8_lossy(&_bytes[4.._end])); }
            state.file1_status = FileStatus::Success;
        }
        Err(FileStatus::AtEnd) => {
            state.file1_status = FileStatus::AtEnd;
        }
        Err(e) => {
            state.file1_status = e.clone();
        }
    }
    Ok(())
}

/// WRITE to FILE1
fn file1_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 14];
    { let _s = format!("{:>width$}", state.file1_key, width = 4); let _b = _s.as_bytes(); let _cl = _b.len().min(4); _buf[0..0+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _src = state.file1_data.as_bytes(); let _end = (4+10).min(_buf.len()); let _cl = _src.len().min(_end-4); _buf[4..4+_cl].copy_from_slice(&_src[.._cl]); }
    match state.file1_handle.write_record(&_buf) {
        Ok(()) => state.file1_status = FileStatus::Success,
        Err(e) => state.file1_status = e,
    }
}

/// CLOSE FILE1
fn file1_close(state: &mut ProgramState) {
    match state.file1_handle.close() {
        Ok(()) => state.file1_status = FileStatus::Success,
        Err(e) => state.file1_status = e,
    }
}

fn main() {
    let mut state = ProgramState::default();
    p_a01_main(&mut state);
}

