// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;


#[derive(Debug, Clone, Default)]
pub struct Tab1 {
    /// TAB1-ENTRY
    pub tab1_entry: [i32; 5],
}

#[derive(Debug, Clone, Default)]
pub struct Tab2 {
    /// TAB2-ENTRY
    pub tab2_entry: [i32; 7],
    /// TAB2B-ENTRY
    pub tab2b_entry: [Tab2bEntry; 7],
}

#[derive(Debug, Clone, Default)]
pub struct Tab3 {
    /// SUB-TAB-3
    pub sub_tab_3: [SubTab3; 2],
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// TAB1
    pub tab1: Tab1,
    /// TAB2
    pub tab2: Tab2,
    /// TAB3
    pub tab3: Tab3,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            tab1: Default::default(),
            tab2: Default::default(),
            tab3: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
        }
    }
}

/// TAB2-ENTRY
fn p_tab2_entry(state: &mut ProgramState) {
    state.tab2.tab2_entry -= state.table;
}

/// TAB1-ENTRY
fn p_tab1_entry(state: &mut ProgramState) {
    state.tab1.tab1_entry += state.table;
    state.tab2.tab2_entry -= state.table;
    state.tab1.tab1_entry += state.table;
}

/// X
fn p_x(state: &mut ProgramState) {
    state.tab2.tab2b_entry.x -= state.table;
}

/// TAB1-ENTRY
fn p_tab1_entry(state: &mut ProgramState) {
    state.tab1.tab1_entry += state.table;
}

/// TAB2B-ENTRY
fn p_tab2b_entry(state: &mut ProgramState) {
    return;
}

fn main() {
    let mut state = ProgramState::default();
    p_tab2_entry(&mut state);
}

