// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;


#[derive(Debug, Clone, Default)]
pub struct Str {
    /// STR-1
    pub str_1: FixedString<2>,
}

#[derive(Debug, Clone, Default)]
pub struct Str2 {
    /// STR-2A
    pub str_2a: FixedString<1>,
    /// STR-2B
    pub str_2b: u32,
}

#[derive(Debug, Clone, Default)]
pub struct One {
    /// SEVEN
    pub seven: u32,
    /// VAR
    pub var: u32,
    /// PTR
    pub ptr: FixedString<1>,
}

#[derive(Debug, Clone, Default)]
pub struct Scrn {
    /// SCRN-FIELD
    pub scrn_field: FixedString<1>,
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// STR
    pub str: Str,
    /// STR-2
    pub str_2: Str2,
    /// ONE
    pub one: One,
    /// SCRN
    pub scrn: Scrn,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            str: Default::default(),
            str_2: Default::default(),
            one: Default::default(),
            scrn: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
        }
    }
}

/// PTR
fn p_ptr(state: &mut ProgramState) {
    state.one.ptr = &state.one.seven as *const _ as usize;
    state.free = &state.one.seven as *const _ as usize;
    state.one.ptr = &state.one.seven as *const _ as usize;
    return;
}

fn main() {
    let mut state = ProgramState::default();
    p_ptr(&mut state);
}

