// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;


#[derive(Debug, Clone)]
pub struct ProgramState {
    /// X
    pub x: FixedString<1>,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            x: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
        }
    }
}

/// SECTION
fn p_section(state: &mut ProgramState) {
    p_p(state);
    { std::process::exit(0); }
}

/// P
fn p_p(state: &mut ProgramState) {
    return;
}

fn main() {
    let mut state = ProgramState::default();
    p_section(&mut state);
}

